name: template-create-minted-key
pins:
  inputs:
    events: [validation.triggered]
  outputs:
    events: [validation.triggered]
connect:
  - event: validation.triggered
    from: .
    to: producer
  - event: validation.requested
    from: producer
    to: validator
  - event: validation.started
    from: validator
    to: producer
