name: operating
mode: template
instance: operating_id
pins:
  inputs:
    events:
      - event: operating.report.requested
        resolution:
          mode: create
          from: event.id
  outputs:
    events:
      - operating.reported
