package serveapp

import (
	"context"
	"fmt"
	"log"
	"time"

	"github.com/division-sh/swarm/internal/runtime/core/worklifetime"
	"github.com/division-sh/swarm/internal/runtime/decisioncard"
)

// reconcileInitialDeliveries traverses canonical sources before selected
// responsibilities. A receipt, including an uncertain one, is never inferred
// from a provider response or regenerated by this scan.
func (d *serveChannelDeliveryDispatcher) reconcileInitialDeliveries(ctx context.Context) error {
	if d == nil || d.store == nil || d.cards == nil {
		return fmt.Errorf("channel delivery source owners are unavailable")
	}
	for _, status := range []string{decisioncard.StatusPending, "deferred"} {
		cursor := ""
		for {
			cards, next, err := d.cards.ListDecisionCards(ctx, decisioncard.ListOptions{Status: status, Limit: 200, Cursor: cursor})
			if err != nil {
				return err
			}
			for _, card := range cards {
				if _, err := d.store.PlanOpenChannelCard(ctx, card.CardID); err != nil {
					return fmt.Errorf("plan open channel card %s: %w", card.CardID, err)
				}
			}
			if next == "" {
				break
			}
			if next == cursor {
				return fmt.Errorf("channel card pagination did not advance")
			}
			cursor = next
		}
	}
	activationID, found, err := d.store.CurrentChannelDeliveryActivationID(ctx)
	if err != nil {
		return err
	}
	if !found || activationID == "" {
		return nil
	}
	cursor := ""
	for {
		plans, err := d.store.ListCurrentChannelDeliveryPlans(ctx, cursor, 200)
		if err != nil {
			return err
		}
		for _, candidate := range plans {
			if candidate.State != "planned" && candidate.State != "rendered" {
				continue
			}
			if candidate.CurrentReceiptID != "" {
				continue // An existing receipt requires edit reconciliation, never another deliver.
			}
			prepared, err := d.store.FreezeAndPersistChannelRender(ctx, candidate.DeliveryID)
			if err != nil {
				return fmt.Errorf("freeze channel delivery %s: %w", candidate.DeliveryID, err)
			}
			current, found, err := d.store.GetCurrentChannelDeliveryPlan(ctx, candidate.DeliveryID)
			if err != nil {
				return err
			}
			if !found || current.State != "rendered" || current.CurrentRenderID != prepared.RenderID || current.CurrentReceiptID != "" {
				continue
			}
			if err := d.dispatchInitial(ctx, current, prepared); err != nil {
				return fmt.Errorf("dispatch channel delivery %s: %w", candidate.DeliveryID, err)
			}
		}
		if len(plans) < 200 {
			break
		}
		last := plans[len(plans)-1].DeliveryID
		if last == cursor {
			return fmt.Errorf("channel delivery pagination did not advance")
		}
		cursor = last
	}
	return nil
}

func startServeChannelDelivery(ctx context.Context, owner *worklifetime.Process, dispatcher *serveChannelDeliveryDispatcher) error {
	if owner == nil || dispatcher == nil {
		return fmt.Errorf("channel delivery worker requires process and dispatcher")
	}
	lease, err := owner.Begin(ctx)
	if err != nil {
		return fmt.Errorf("admit channel delivery worker: %w", err)
	}
	go func() {
		defer func() { _ = lease.Done() }()
		workCtx := lease.Context()
		ticker := time.NewTicker(time.Second)
		defer ticker.Stop()
		for {
			if err := dispatcher.reconcileInitialDeliveries(workCtx); err != nil && workCtx.Err() == nil {
				log.Printf("channel delivery reconciliation: %v", err)
			}
			select {
			case <-workCtx.Done():
				return
			case <-ticker.C:
			}
		}
	}()
	return nil
}
