package serveapp

import (
	"context"
	"errors"
	"fmt"
	"log"
	"time"

	"github.com/division-sh/swarm/internal/apiv1"
	"github.com/division-sh/swarm/internal/mailbox"
	runtimechanneldelivery "github.com/division-sh/swarm/internal/runtime/channeldelivery"
	"github.com/division-sh/swarm/internal/runtime/core/worklifetime"
	"github.com/division-sh/swarm/internal/runtime/decisioncard"
)

// reconcileDeliveries traverses canonical sources before selected
// responsibilities. A receipt, including an uncertain one, is never inferred
// from a provider response or regenerated by this scan.
func (d *serveChannelDeliveryDispatcher) reconcileDeliveries(ctx context.Context) error {
	if d == nil || d.store == nil || d.cards == nil {
		return fmt.Errorf("channel delivery source owners are unavailable")
	}
	if err := d.reconcileCardChanges(ctx); err != nil {
		return err
	}
	for _, status := range []string{decisioncard.StatusPending, "deferred"} {
		cursor := ""
		for {
			cards, next, err := d.cards.ListDecisionCards(ctx, decisioncard.ListOptions{Status: status, Limit: 200, Cursor: cursor})
			if err != nil {
				return err
			}
			for _, card := range cards {
				if _, err := d.store.PlanOpenChannelCard(ctx, card.CardID); err != nil {
					return fmt.Errorf("plan open channel card %s: %w", card.CardID, err)
				}
			}
			if next == "" {
				break
			}
			if next == cursor {
				return fmt.Errorf("channel card pagination did not advance")
			}
			cursor = next
		}
	}
	activationID, found, err := d.store.CurrentChannelDeliveryActivationID(ctx)
	if err != nil {
		return err
	}
	if !found || activationID == "" {
		return nil
	}
	cursor := ""
	var failures error
	for {
		plans, err := d.store.ListCurrentChannelDeliveryPlans(ctx, cursor, 200)
		if err != nil {
			return errors.Join(failures, err)
		}
		for _, candidate := range plans {
			if candidate.State == "uncertain" || candidate.State == "retired" {
				continue
			}
			if candidate.State != "planned" && candidate.State != "rendered" && candidate.State != "sent" {
				failures = errors.Join(failures, fmt.Errorf("channel delivery %s has unsupported state %q", candidate.DeliveryID, candidate.State))
				continue
			}
			capacity := 0
			if candidate.SourceKind == "card" {
				capacity, err = d.selectedActionCapacity(ctx, candidate)
				if err != nil {
					failures = errors.Join(failures, fmt.Errorf("select channel delivery %s action capacity: %w", candidate.DeliveryID, err))
					continue
				}
			}
			prepared, err := d.store.FreezeAndPersistChannelRender(ctx, candidate.DeliveryID, capacity)
			if err != nil {
				failures = errors.Join(failures, fmt.Errorf("freeze channel delivery %s: %w", candidate.DeliveryID, err))
				continue
			}
			current, found, err := d.store.GetCurrentChannelDeliveryPlan(ctx, candidate.DeliveryID)
			if err != nil {
				failures = errors.Join(failures, fmt.Errorf("read channel delivery %s: %w", candidate.DeliveryID, err))
				continue
			}
			if !found || current.CurrentRenderID != prepared.RenderID {
				continue
			}
			if current.CurrentReceiptID == "" {
				if current.State != "rendered" {
					continue
				}
				if err := d.dispatchInitial(ctx, current, prepared); err != nil {
					failures = errors.Join(failures, fmt.Errorf("dispatch channel delivery %s: %w", candidate.DeliveryID, err))
				}
				continue
			}
			receipt, found, err := d.store.GetCurrentChannelSentReceipt(ctx, candidate.DeliveryID, current.CurrentReceiptID)
			if err != nil {
				failures = errors.Join(failures, fmt.Errorf("read channel delivery receipt %s: %w", current.CurrentReceiptID, err))
				continue
			}
			if !found {
				failures = errors.Join(failures, fmt.Errorf("current channel delivery receipt %s is absent", current.CurrentReceiptID))
				continue
			}
			if receipt.RenderID == prepared.RenderID {
				continue
			}
			if current.State != "rendered" {
				failures = errors.Join(failures, fmt.Errorf("channel delivery %s has a changed render outside edit state", candidate.DeliveryID))
				continue
			}
			if err := d.dispatchEdit(ctx, current, prepared, receipt); err != nil {
				failures = errors.Join(failures, fmt.Errorf("edit channel delivery %s: %w", candidate.DeliveryID, err))
			}
		}
		if len(plans) < 200 {
			break
		}
		last := plans[len(plans)-1].DeliveryID
		if last == cursor {
			return errors.Join(failures, fmt.Errorf("channel delivery pagination did not advance"))
		}
		cursor = last
	}
	return failures
}

func (d *serveChannelDeliveryDispatcher) reconcileCardChanges(ctx context.Context) error {
	cursor, current, err := d.store.CurrentChannelCardChangeCursor(ctx)
	if err != nil || !current {
		return err
	}
	for {
		changes, err := d.cards.ListDecisionCardChanges(ctx, decisioncard.SubscriptionOptions{After: cursor, Limit: 200})
		if err != nil {
			return err
		}
		for _, change := range changes {
			if change.Sequence <= cursor {
				return fmt.Errorf("channel card change cursor did not advance")
			}
			if err := d.store.PlanChangedChannelCard(ctx, change.Sequence, change.CardID); err != nil {
				return fmt.Errorf("plan channel card change %d: %w", change.Sequence, err)
			}
			cursor = change.Sequence
		}
		if len(changes) < 200 {
			return nil
		}
	}
}

func (d *serveChannelDeliveryDispatcher) reconcileCardActions(ctx context.Context) error {
	if d == nil || d.store == nil || d.cards == nil {
		return fmt.Errorf("channel action owners are unavailable")
	}
	cursor := ""
	var failures error
	for {
		pending, err := d.store.ListPendingChannelActions(ctx, cursor, 200)
		if err != nil {
			return errors.Join(failures, err)
		}
		for _, intent := range pending {
			resolved, found, err := d.store.ResolveChannelActionFact(ctx, intent.Fact.ActionFact)
			if err != nil {
				failures = errors.Join(failures, fmt.Errorf("resolve channel action %s: %w", intent.PublicationID, err))
				continue
			}
			if !found || !resolved.CurrentRender {
				if err := d.store.SettleUnappliedChannelAction(ctx, intent.Fact, runtimechanneldelivery.ActionRejected); err != nil {
					failures = errors.Join(failures, fmt.Errorf("reject channel action %s: %w", intent.PublicationID, err))
				}
				continue
			}
			if err := d.acknowledgeChannelAction(ctx, intent, resolved); err != nil {
				failures = errors.Join(failures, fmt.Errorf("acknowledge channel action %s: %w", intent.PublicationID, err))
			}
			if resolved.Action.Kind == "open_inbox" || resolved.Action.Kind == "view_full" ||
				resolved.Action.Kind == "next_page" || resolved.Action.Kind == "next_draft_page" ||
				resolved.Action.Kind == "next_recovery_page" {
				inboxText := ""
				if resolved.Action.Kind == "open_inbox" {
					inboxText, err = d.inboxContent(ctx)
				}
				if err == nil {
					_, err = d.store.PlanChannelActionResponse(ctx, intent.Fact, resolved, inboxText)
				}
				if err != nil {
					failures = errors.Join(failures, fmt.Errorf("plan channel navigation %s: %w", intent.PublicationID, err))
				}
				continue
			}
			if resolved.SourceKind == "card" && resolved.Action.Kind == "more_controls" {
				if err := d.store.AdvanceChannelCardActionPage(ctx, intent.Fact, resolved); err != nil {
					failures = errors.Join(failures, fmt.Errorf("advance channel card controls %s: %w", intent.PublicationID, err))
				}
				continue
			}
			if resolved.SourceKind == "notice" && resolved.Action.Kind == "acknowledge_notice" {
				if err := d.processNoticeAction(ctx, intent, resolved); err != nil {
					failures = errors.Join(failures, fmt.Errorf("acknowledge channel notice %s: %w", intent.PublicationID, err))
				}
				continue
			}
			if resolved.SourceKind == "response" && resolved.Action.Kind == "select_draft" {
				if err := d.processDraftChoice(ctx, intent, resolved); err != nil {
					failures = errors.Join(failures, fmt.Errorf("select channel draft %s: %w", intent.PublicationID, err))
				}
				continue
			}
			if resolved.SourceKind == "response" && resolved.Action.Kind == "resend" {
				if _, err := d.store.PlanManualChannelResend(ctx, intent.Fact, resolved); err != nil {
					failures = errors.Join(failures, fmt.Errorf("plan manual channel resend %s: %w", intent.PublicationID, err))
				}
				continue
			}
			if resolved.SourceKind == "card" && resolved.Action.Kind == "skip_input" {
				if err := d.processInputSkip(ctx, intent, resolved); err != nil {
					failures = errors.Join(failures, fmt.Errorf("skip channel input %s: %w", intent.PublicationID, err))
				}
				continue
			}
			if resolved.SourceKind != "card" || (resolved.Action.Kind != "verdict" && resolved.Action.Kind != "cancel_input") {
				if err := d.store.SettleUnappliedChannelAction(ctx, intent.Fact, runtimechanneldelivery.ActionUnsupported); err != nil {
					failures = errors.Join(failures, fmt.Errorf("reject unsupported channel action %s: %w", intent.PublicationID, err))
				}
				continue
			}
			card, err := d.cards.GetDecisionCard(ctx, resolved.SourceID)
			if errors.Is(err, decisioncard.ErrNotFound) {
				err = d.store.SettleUnappliedChannelAction(ctx, intent.Fact, runtimechanneldelivery.ActionStale)
			} else if err == nil && card.Status != decisioncard.StatusPending {
				err = d.store.SettleUnappliedChannelAction(ctx, intent.Fact, runtimechanneldelivery.ActionStale)
			} else if err == nil {
				_, err = d.processCardAction(ctx, intent)
			}
			if err != nil {
				failures = errors.Join(failures, fmt.Errorf("process channel action %s: %w", intent.PublicationID, err))
			}
		}
		if len(pending) < 200 {
			return failures
		}
		last := pending[len(pending)-1].PublicationID
		if last == cursor {
			return errors.Join(failures, fmt.Errorf("channel action pagination did not advance"))
		}
		cursor = last
	}
}

func (d *serveChannelDeliveryDispatcher) processInputSkip(ctx context.Context, intent runtimechanneldelivery.PendingAction,
	expected runtimechanneldelivery.ResolvedAction) error {
	resolved, progress, draft, err := d.store.PreviewChannelInputSkip(ctx, intent.Fact, intent.ReceivedAt)
	if err != nil {
		return err
	}
	if resolved != expected || draft.InputDraftID != resolved.Action.DraftID {
		return fmt.Errorf("channel skip changed before processing")
	}
	if progress.Complete {
		return d.processFinalCardSkip(ctx, intent, resolved, draft, progress)
	}
	_, err = d.store.AdvancePartialChannelInputSkip(ctx, intent.Fact, intent.ReceivedAt)
	return err
}

func (d *serveChannelDeliveryDispatcher) processDraftChoice(ctx context.Context, intent runtimechanneldelivery.PendingAction,
	resolved runtimechanneldelivery.ResolvedAction) error {
	candidate, text, progress, principalID, err := d.store.PreviewChosenChannelInputDraftText(ctx, intent.Fact, intent.ReceivedAt)
	if err != nil {
		if errors.Is(err, decisioncard.ErrInvalidInput) {
			_, err = d.store.PlanChannelActionResponse(ctx, intent.Fact, resolved, "")
		}
		return err
	}
	if candidate.DraftID != resolved.Action.DraftID || candidate.CardID != resolved.Action.CardID ||
		text.PublicationID != resolved.Action.TextPublicationID {
		return fmt.Errorf("chosen channel draft changed before processing")
	}
	if progress.Complete {
		return d.processFinalCardText(ctx, text, candidate, progress, principalID, &intent)
	}
	_, err = d.store.AdvancePartialChosenChannelInputDraftText(ctx, intent.Fact, intent.ReceivedAt)
	return err
}

func (d *serveChannelDeliveryDispatcher) reconcileNativeInboxEntries(ctx context.Context) error {
	if d == nil || d.store == nil || d.cards == nil || d.mailbox == nil || d.proposedEffects == nil {
		return fmt.Errorf("channel inbox response owners are unavailable")
	}
	cursor := ""
	var failures error
	for {
		pending, err := d.store.ListPendingChannelTexts(ctx, cursor, 200)
		if err != nil {
			return errors.Join(failures, err)
		}
		for _, intent := range pending {
			if intent.Fact.EntryReference == "" {
				if err := d.processPendingInputText(ctx, intent); err != nil {
					failures = errors.Join(failures, fmt.Errorf("process channel input %s: %w", intent.PublicationID, err))
				}
				continue
			}
			entry, found, err := d.resolveNativeInboxEntry(ctx, intent.Fact)
			if err != nil {
				failures = errors.Join(failures, fmt.Errorf("resolve native inbox entry %s: %w", intent.PublicationID, err))
				continue
			}
			if !found {
				continue
			}
			content, err := d.inboxContent(ctx)
			if err != nil {
				failures = errors.Join(failures, err)
				continue
			}
			if _, err := d.store.PlanNativeInboxResponse(ctx, intent.Fact, entry, content); err != nil {
				failures = errors.Join(failures, fmt.Errorf("plan native inbox response %s: %w", intent.PublicationID, err))
			}
		}
		if len(pending) < 200 {
			return failures
		}
		last := pending[len(pending)-1].PublicationID
		if last == cursor {
			return errors.Join(failures, fmt.Errorf("channel text pagination did not advance"))
		}
		cursor = last
	}
}

func (d *serveChannelDeliveryDispatcher) processPendingInputText(ctx context.Context, intent runtimechanneldelivery.PendingText) error {
	var selected runtimechanneldelivery.InputDraftCandidate
	multiple := false
	cursor := ""
	for {
		candidates, next, err := d.store.ListCurrentChannelInputDrafts(ctx, intent.Fact, intent.ReceivedAt, cursor, 200)
		if err != nil {
			return err
		}
		for _, candidate := range candidates {
			if selected.DraftID != "" {
				multiple = true
				break
			}
			selected = candidate
		}
		if multiple {
			break
		}
		if next == "" {
			break
		}
		if next == cursor {
			return fmt.Errorf("channel input draft cursor did not advance")
		}
		cursor = next
	}
	if multiple {
		if intent.Fact.ReplyToReference != "" {
			return fmt.Errorf("quoted channel input selects multiple current drafts")
		}
		_, err := d.store.PlanChannelDraftChooser(ctx, intent.Fact, intent.ReceivedAt)
		return err
	}
	if selected.DraftID == "" {
		_, err := d.store.PlanChannelTextResponse(ctx, intent.Fact,
			"That reply does not match a current card prompt. Open inbox to review current actions.", "teaching")
		return err
	}
	progress, principalID, err := d.store.PreviewCurrentChannelInputDraftText(ctx, intent.Fact, intent.ReceivedAt, selected.DraftID)
	if err != nil {
		if errors.Is(err, decisioncard.ErrInvalidInput) {
			_, err = d.store.PlanChannelTextResponse(ctx, intent.Fact,
				"That answer does not match the requested field. Reply with a value of the required type, or use the card controls.", "teaching")
		}
		return err
	}
	if progress.Complete {
		return d.processFinalCardText(ctx, intent, selected, progress, principalID, nil)
	}
	_, err = d.store.AdvancePartialChannelInputDraftText(ctx, intent.Fact, intent.ReceivedAt, selected.DraftID)
	return err
}

func (d *serveChannelDeliveryDispatcher) inboxContent(ctx context.Context) (string, error) {
	if d == nil || d.cards == nil || d.mailbox == nil || d.proposedEffects == nil {
		return "", fmt.Errorf("channel inbox projection owners are unavailable")
	}
	owners := apiv1.DecisionCardHandlerOptions{
		Cards: d.cards, ProposedEffects: d.proposedEffects, Mailbox: d.mailbox,
	}
	entries := make([]runtimechanneldelivery.InboxEntry, 0)
	cursor := ""
	seen := map[string]struct{}{}
	unread := 0
	for {
		page, err := apiv1.ListMailboxProjectionPage(ctx, owners, decisioncard.StatusPending, cursor, 5)
		if err != nil {
			return "", err
		}
		if cursor == "" {
			unread = page.UnreadInformationalNotices
		}
		for _, item := range page.Items {
			projection, ok := item.(map[string]any)
			if !ok {
				return "", fmt.Errorf("mailbox projection item is not tagged")
			}
			var entry runtimechanneldelivery.InboxEntry
			switch projection["kind"] {
			case decisioncard.KindNotice:
				notice, ok := projection["notice"].(mailbox.V1Item)
				if !ok {
					return "", fmt.Errorf("mailbox notice projection is not typed")
				}
				entry, err = runtimechanneldelivery.InboxNoticeEntry(notice)
			case decisioncard.KindDecisionCard:
				card, ok := projection["decision_card"].(decisioncard.ListItem)
				if !ok {
					return "", fmt.Errorf("mailbox card projection is not typed")
				}
				entry, err = runtimechanneldelivery.InboxCardEntry(card)
			default:
				return "", fmt.Errorf("mailbox projection item has unknown kind")
			}
			if err != nil {
				return "", err
			}
			entries = append(entries, entry)
		}
		if page.NextCursor == "" {
			break
		}
		if page.NextCursor == cursor {
			return "", fmt.Errorf("channel inbox cursor did not advance")
		}
		if _, duplicate := seen[page.NextCursor]; duplicate {
			return "", fmt.Errorf("channel inbox cursor repeated")
		}
		seen[page.NextCursor] = struct{}{}
		cursor = page.NextCursor
	}
	return runtimechanneldelivery.InboxText(unread, entries, false)
}

func startServeChannelDelivery(ctx context.Context, owner *worklifetime.Process, dispatcher *serveChannelDeliveryDispatcher) error {
	if owner == nil || dispatcher == nil {
		return fmt.Errorf("channel delivery worker requires process and dispatcher")
	}
	lease, err := owner.Begin(ctx)
	if err != nil {
		return fmt.Errorf("admit channel delivery worker: %w", err)
	}
	go func() {
		defer func() { _ = lease.Done() }()
		workCtx := lease.Context()
		ticker := time.NewTicker(time.Second)
		nativeTicker := time.NewTicker(5 * time.Second)
		defer ticker.Stop()
		defer nativeTicker.Stop()
		if err := dispatcher.reconcileNativeInboxSettings(workCtx); err != nil && workCtx.Err() == nil {
			log.Printf("native inbox setting reconciliation: %v", err)
		}
		for {
			if err := dispatcher.reconcileNativeInboxEntries(workCtx); err != nil && workCtx.Err() == nil {
				log.Printf("channel inbox entry reconciliation: %v", err)
			}
			if err := dispatcher.reconcileDeliveries(workCtx); err != nil && workCtx.Err() == nil {
				log.Printf("channel delivery reconciliation: %v", err)
			}
			if err := dispatcher.reconcileCardActions(workCtx); err != nil && workCtx.Err() == nil {
				log.Printf("channel action reconciliation: %v", err)
			}
			select {
			case <-workCtx.Done():
				return
			case <-nativeTicker.C:
				if err := dispatcher.reconcileNativeInboxSettings(workCtx); err != nil && workCtx.Err() == nil {
					log.Printf("native inbox setting reconciliation: %v", err)
				}
			case <-ticker.C:
			}
		}
	}()
	return nil
}
