package serveapp

import (
	"context"
	"errors"
	"fmt"
	"log"
	"time"

	"github.com/division-sh/swarm/internal/apiv1"
	"github.com/division-sh/swarm/internal/mailbox"
	runtimechanneldelivery "github.com/division-sh/swarm/internal/runtime/channeldelivery"
	"github.com/division-sh/swarm/internal/runtime/core/worklifetime"
	"github.com/division-sh/swarm/internal/runtime/decisioncard"
)

// reconcileDeliveries traverses canonical sources before selected
// responsibilities. A receipt, including an uncertain one, is never inferred
// from a provider response or regenerated by this scan.
func (d *serveChannelDeliveryDispatcher) reconcileDeliveries(ctx context.Context) error {
	if d == nil || d.store == nil || d.cards == nil {
		return fmt.Errorf("channel delivery source owners are unavailable")
	}
	for _, status := range []string{decisioncard.StatusPending, "deferred"} {
		cursor := ""
		for {
			cards, next, err := d.cards.ListDecisionCards(ctx, decisioncard.ListOptions{Status: status, Limit: 200, Cursor: cursor})
			if err != nil {
				return err
			}
			for _, card := range cards {
				if _, err := d.store.PlanOpenChannelCard(ctx, card.CardID); err != nil {
					return fmt.Errorf("plan open channel card %s: %w", card.CardID, err)
				}
			}
			if next == "" {
				break
			}
			if next == cursor {
				return fmt.Errorf("channel card pagination did not advance")
			}
			cursor = next
		}
	}
	activationID, found, err := d.store.CurrentChannelDeliveryActivationID(ctx)
	if err != nil {
		return err
	}
	if !found || activationID == "" {
		return nil
	}
	cursor := ""
	for {
		plans, err := d.store.ListCurrentChannelDeliveryPlans(ctx, cursor, 200)
		if err != nil {
			return err
		}
		for _, candidate := range plans {
			if candidate.State == "uncertain" || candidate.State == "retired" {
				continue
			}
			if candidate.State != "planned" && candidate.State != "rendered" && candidate.State != "sent" {
				return fmt.Errorf("channel delivery %s has unsupported state %q", candidate.DeliveryID, candidate.State)
			}
			prepared, err := d.store.FreezeAndPersistChannelRender(ctx, candidate.DeliveryID)
			if err != nil {
				return fmt.Errorf("freeze channel delivery %s: %w", candidate.DeliveryID, err)
			}
			current, found, err := d.store.GetCurrentChannelDeliveryPlan(ctx, candidate.DeliveryID)
			if err != nil {
				return err
			}
			if !found || current.CurrentRenderID != prepared.RenderID {
				continue
			}
			if current.CurrentReceiptID == "" {
				if current.State != "rendered" {
					continue
				}
				if err := d.dispatchInitial(ctx, current, prepared); err != nil {
					return fmt.Errorf("dispatch channel delivery %s: %w", candidate.DeliveryID, err)
				}
				continue
			}
			receipt, found, err := d.store.GetCurrentChannelSentReceipt(ctx, candidate.DeliveryID, current.CurrentReceiptID)
			if err != nil {
				return fmt.Errorf("read channel delivery receipt %s: %w", current.CurrentReceiptID, err)
			}
			if !found {
				return fmt.Errorf("current channel delivery receipt %s is absent", current.CurrentReceiptID)
			}
			if receipt.RenderID == prepared.RenderID {
				continue
			}
			if current.State != "rendered" {
				return fmt.Errorf("channel delivery %s has a changed render outside edit state", candidate.DeliveryID)
			}
			if err := d.dispatchEdit(ctx, current, prepared, receipt); err != nil {
				return fmt.Errorf("edit channel delivery %s: %w", candidate.DeliveryID, err)
			}
		}
		if len(plans) < 200 {
			break
		}
		last := plans[len(plans)-1].DeliveryID
		if last == cursor {
			return fmt.Errorf("channel delivery pagination did not advance")
		}
		cursor = last
	}
	return nil
}

func (d *serveChannelDeliveryDispatcher) reconcileCardActions(ctx context.Context) error {
	if d == nil || d.store == nil || d.cards == nil {
		return fmt.Errorf("channel action owners are unavailable")
	}
	cursor := ""
	var failures error
	for {
		pending, err := d.store.ListPendingChannelActions(ctx, cursor, 200)
		if err != nil {
			return errors.Join(failures, err)
		}
		for _, intent := range pending {
			resolved, found, err := d.store.ResolveChannelActionFact(ctx, intent.Fact.ActionFact)
			if err != nil {
				failures = errors.Join(failures, fmt.Errorf("resolve channel action %s: %w", intent.PublicationID, err))
				continue
			}
			if !found || !resolved.CurrentRender {
				if err := d.store.SettleUnappliedChannelAction(ctx, intent.Fact, runtimechanneldelivery.ActionRejected); err != nil {
					failures = errors.Join(failures, fmt.Errorf("reject channel action %s: %w", intent.PublicationID, err))
				}
				continue
			}
			if err := d.acknowledgeChannelAction(ctx, intent, resolved); err != nil {
				failures = errors.Join(failures, fmt.Errorf("acknowledge channel action %s: %w", intent.PublicationID, err))
			}
			if resolved.Action.Kind == "open_inbox" || resolved.Action.Kind == "view_full" || resolved.Action.Kind == "next_page" {
				inboxText := ""
				if resolved.Action.Kind == "open_inbox" {
					inboxText, err = d.inboxContent(ctx)
				}
				if err == nil {
					_, err = d.store.PlanChannelActionResponse(ctx, intent.Fact, resolved, inboxText)
				}
				if err != nil {
					failures = errors.Join(failures, fmt.Errorf("plan channel navigation %s: %w", intent.PublicationID, err))
				}
				continue
			}
			if resolved.SourceKind == "notice" && resolved.Action.Kind == "acknowledge_notice" {
				if err := d.processNoticeAction(ctx, intent, resolved); err != nil {
					failures = errors.Join(failures, fmt.Errorf("acknowledge channel notice %s: %w", intent.PublicationID, err))
				}
				continue
			}
			if resolved.SourceKind != "card" || resolved.Action.Kind != "verdict" {
				if err := d.store.SettleUnappliedChannelAction(ctx, intent.Fact, runtimechanneldelivery.ActionUnsupported); err != nil {
					failures = errors.Join(failures, fmt.Errorf("reject unsupported channel action %s: %w", intent.PublicationID, err))
				}
				continue
			}
			card, err := d.cards.GetDecisionCard(ctx, resolved.SourceID)
			if errors.Is(err, decisioncard.ErrNotFound) {
				err = d.store.SettleUnappliedChannelAction(ctx, intent.Fact, runtimechanneldelivery.ActionStale)
			} else if err == nil && card.Status != decisioncard.StatusPending {
				err = d.store.SettleUnappliedChannelAction(ctx, intent.Fact, runtimechanneldelivery.ActionStale)
			} else if err == nil {
				_, err = d.processCardAction(ctx, intent)
			}
			if err != nil {
				failures = errors.Join(failures, fmt.Errorf("process channel action %s: %w", intent.PublicationID, err))
			}
		}
		if len(pending) < 200 {
			return failures
		}
		last := pending[len(pending)-1].PublicationID
		if last == cursor {
			return errors.Join(failures, fmt.Errorf("channel action pagination did not advance"))
		}
		cursor = last
	}
}

func (d *serveChannelDeliveryDispatcher) reconcileNativeInboxEntries(ctx context.Context) error {
	if d == nil || d.store == nil || d.cards == nil || d.mailbox == nil || d.proposedEffects == nil {
		return fmt.Errorf("channel inbox response owners are unavailable")
	}
	cursor := ""
	var failures error
	for {
		pending, err := d.store.ListPendingChannelTexts(ctx, cursor, 200)
		if err != nil {
			return errors.Join(failures, err)
		}
		for _, intent := range pending {
			if intent.Fact.EntryReference == "" {
				continue
			}
			entry, found, err := d.resolveNativeInboxEntry(ctx, intent.Fact)
			if err != nil {
				failures = errors.Join(failures, fmt.Errorf("resolve native inbox entry %s: %w", intent.PublicationID, err))
				continue
			}
			if !found {
				continue
			}
			content, err := d.inboxContent(ctx)
			if err != nil {
				failures = errors.Join(failures, err)
				continue
			}
			if _, err := d.store.PlanNativeInboxResponse(ctx, intent.Fact, entry, content); err != nil {
				failures = errors.Join(failures, fmt.Errorf("plan native inbox response %s: %w", intent.PublicationID, err))
			}
		}
		if len(pending) < 200 {
			return failures
		}
		last := pending[len(pending)-1].PublicationID
		if last == cursor {
			return errors.Join(failures, fmt.Errorf("channel text pagination did not advance"))
		}
		cursor = last
	}
}

func (d *serveChannelDeliveryDispatcher) inboxContent(ctx context.Context) (string, error) {
	if d == nil || d.cards == nil || d.mailbox == nil || d.proposedEffects == nil {
		return "", fmt.Errorf("channel inbox projection owners are unavailable")
	}
	owners := apiv1.DecisionCardHandlerOptions{
		Cards: d.cards, ProposedEffects: d.proposedEffects, Mailbox: d.mailbox,
	}
	entries := make([]runtimechanneldelivery.InboxEntry, 0)
	cursor := ""
	seen := map[string]struct{}{}
	unread := 0
	for {
		page, err := apiv1.ListMailboxProjectionPage(ctx, owners, decisioncard.StatusPending, cursor, 5)
		if err != nil {
			return "", err
		}
		if cursor == "" {
			unread = page.UnreadInformationalNotices
		}
		for _, item := range page.Items {
			projection, ok := item.(map[string]any)
			if !ok {
				return "", fmt.Errorf("mailbox projection item is not tagged")
			}
			var entry runtimechanneldelivery.InboxEntry
			switch projection["kind"] {
			case decisioncard.KindNotice:
				notice, ok := projection["notice"].(mailbox.V1Item)
				if !ok {
					return "", fmt.Errorf("mailbox notice projection is not typed")
				}
				entry, err = runtimechanneldelivery.InboxNoticeEntry(notice)
			case decisioncard.KindDecisionCard:
				card, ok := projection["decision_card"].(decisioncard.ListItem)
				if !ok {
					return "", fmt.Errorf("mailbox card projection is not typed")
				}
				entry, err = runtimechanneldelivery.InboxCardEntry(card)
			default:
				return "", fmt.Errorf("mailbox projection item has unknown kind")
			}
			if err != nil {
				return "", err
			}
			entries = append(entries, entry)
		}
		if page.NextCursor == "" {
			break
		}
		if page.NextCursor == cursor {
			return "", fmt.Errorf("channel inbox cursor did not advance")
		}
		if _, duplicate := seen[page.NextCursor]; duplicate {
			return "", fmt.Errorf("channel inbox cursor repeated")
		}
		seen[page.NextCursor] = struct{}{}
		cursor = page.NextCursor
	}
	return runtimechanneldelivery.InboxText(unread, entries, false)
}

func startServeChannelDelivery(ctx context.Context, owner *worklifetime.Process, dispatcher *serveChannelDeliveryDispatcher) error {
	if owner == nil || dispatcher == nil {
		return fmt.Errorf("channel delivery worker requires process and dispatcher")
	}
	lease, err := owner.Begin(ctx)
	if err != nil {
		return fmt.Errorf("admit channel delivery worker: %w", err)
	}
	go func() {
		defer func() { _ = lease.Done() }()
		workCtx := lease.Context()
		ticker := time.NewTicker(time.Second)
		nativeTicker := time.NewTicker(5 * time.Second)
		defer ticker.Stop()
		defer nativeTicker.Stop()
		if err := dispatcher.reconcileNativeInboxSettings(workCtx); err != nil && workCtx.Err() == nil {
			log.Printf("native inbox setting reconciliation: %v", err)
		}
		for {
			if err := dispatcher.reconcileNativeInboxEntries(workCtx); err != nil && workCtx.Err() == nil {
				log.Printf("channel inbox entry reconciliation: %v", err)
			}
			if err := dispatcher.reconcileDeliveries(workCtx); err != nil && workCtx.Err() == nil {
				log.Printf("channel delivery reconciliation: %v", err)
			}
			if err := dispatcher.reconcileCardActions(workCtx); err != nil && workCtx.Err() == nil {
				log.Printf("channel action reconciliation: %v", err)
			}
			select {
			case <-workCtx.Done():
				return
			case <-nativeTicker.C:
				if err := dispatcher.reconcileNativeInboxSettings(workCtx); err != nil && workCtx.Err() == nil {
					log.Printf("native inbox setting reconciliation: %v", err)
				}
			case <-ticker.C:
			}
		}
	}()
	return nil
}
