import { useDashboardPipelineData } from "../hooks/useDashboardPipelineData.js";

export function useDashboardPipelineSources({
  activeView,
  addToast,
  pipelineState,
}) {
  return useDashboardPipelineData({
    activeView,
    addToast,
    setFunnel: pipelineState.setFunnel,
    setShardScans: pipelineState.setShardScans,
    setShardScanDetails: pipelineState.setShardScanDetails,
    selectedShardScanID: pipelineState.selectedShardScanID,
    setSelectedShardScanID: pipelineState.setSelectedShardScanID,
    shardScans: pipelineState.shardScans,
    setTraceRows: pipelineState.setTraceRows,
    setHoldingData: pipelineState.setHoldingData,
    setHoldingDetailModal: pipelineState.setHoldingDetailModal,
    graphMode: pipelineState.graphMode,
    graphVertical: pipelineState.graphVertical,
    setGraphVertical: pipelineState.setGraphVertical,
    setVerticals: pipelineState.setVerticals,
    flowVertical: pipelineState.flowVertical,
    setFlowVertical: pipelineState.setFlowVertical,
    selectedGraphNodeID: pipelineState.selectedGraphNodeID,
    setSelectedGraphNodeID: pipelineState.setSelectedGraphNodeID,
    selectedGraphEdgeID: pipelineState.selectedGraphEdgeID,
    setSelectedGraphEdgeID: pipelineState.setSelectedGraphEdgeID,
    setGraph: pipelineState.setGraph,
    flowView: pipelineState.flowView,
    flowStart: pipelineState.flowStart,
    flowEnd: pipelineState.flowEnd,
    selectedFlowNodeID: pipelineState.selectedFlowNodeID,
    setSelectedFlowNodeID: pipelineState.setSelectedFlowNodeID,
    selectedFlowEdgeID: pipelineState.selectedFlowEdgeID,
    setSelectedFlowEdgeID: pipelineState.setSelectedFlowEdgeID,
    setFlowGraph: pipelineState.setFlowGraph,
    setFlowGraphMeta: pipelineState.setFlowGraphMeta,
    setFlowEvents: pipelineState.setFlowEvents,
    setFlowReplayIndex: pipelineState.setFlowReplayIndex,
    setFlowReplayOn: pipelineState.setFlowReplayOn,
  });
}
