import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { fetchAgents } from "../api/agents.js";
import { getEmpireKey } from "../api/client.js";
import { useDashboardActions } from "../hooks/useDashboardActions.js";
import { useDashboardCoreData } from "../hooks/useDashboardCoreData.js";
import { useDashboardPipelineData } from "../hooks/useDashboardPipelineData.js";
import { useDashboardPolling } from "../hooks/useDashboardPolling.js";
import { useDashboardRuntimeData } from "../hooks/useDashboardRuntimeData.js";
import { useEventStream } from "../hooks/useEventStream.js";
import { useFlowRuntimeStream } from "../hooks/useFlowRuntimeStream.js";
import { useHashTab } from "../hooks/useHashTab.js";
import { usePersistentState } from "../hooks/usePersistentState.js";
import { useReplayTicker } from "../hooks/useReplayTicker.js";
import { VALID_TABS } from "./dashboardTabs.js";
import { useDashboardDerivedState } from "./useDashboardDerivedState.js";
import {
  useDashboardOpsState,
  useDashboardPipelineState,
  useDashboardRuntimeState,
  useDashboardTaskState,
} from "./useDashboardStateBuckets.js";
import { relTime } from "../lib/format.js";

export function useDashboardCoordinator() {
  const [activeView, setActiveView] = useHashTab(VALID_TABS, "agents");
  const [statusText, setStatusText] = useState("Loading...");
  const [apiKey, setApiKey] = usePersistentState("empire_api_key", getEmpireKey());
  const [initialLoading, setInitialLoading] = useState(true);
  const [agentSearch, setAgentSearch] = useState("");
  const [selectedMailboxItem, setSelectedMailboxItem] = useState("");
  const [modalContent, setModalContent] = useState(null);

  const [overview, setOverview] = useState({});
  const [agentsResp, setAgentsResp] = useState({ agents: [], states: {} });
  const [digestResp, setDigestResp] = useState(null);
  const taskState = useDashboardTaskState();
  const runtimeState = useDashboardRuntimeState();
  const opsState = useDashboardOpsState();
  const pipelineState = useDashboardPipelineState();

  const {
    taskStatus,
    setTaskStatus,
    tasksResp,
    setTasksResp,
    selectedTaskID,
    setSelectedTaskID,
    taskResultText,
    setTaskResultText,
    taskOutcome,
    setTaskOutcome,
    taskFollowUpNeeded,
    setTaskFollowUpNeeded,
    taskRejectReason,
    setTaskRejectReason,
    tasksStats,
    setTasksStats,
  } = taskState;
  const {
    eventsFilter,
    setEventsFilter,
    eventsIncludeRuntime,
    setEventsIncludeRuntime,
    eventsRuntimeErrorsOnly,
    setEventsRuntimeErrorsOnly,
    events,
    setEvents,
    runtimeLogs,
    setRuntimeLogs,
    selectedEventID,
    setSelectedEventID,
    eventDetail,
    setEventDetail,
    conversations,
    setConversations,
    selectedConv,
    setSelectedConv,
    conversationDetail,
    setConversationDetail,
    logsFilter,
    setLogsFilter,
    logsRuntimeErrorsOnly,
    setLogsRuntimeErrorsOnly,
    logsData,
    setLogsData,
    selectedLogID,
    setSelectedLogID,
    logsOrder,
    setLogsOrder,
    incidentsFilter,
    setIncidentsFilter,
    incidentsData,
    setIncidentsData,
    selectedIncidentCode,
    setSelectedIncidentCode,
    selectedIncidentAgent,
    setSelectedIncidentAgent,
    incidentLogs,
    setIncidentLogs,
    incidentArtifacts,
    setIncidentArtifacts,
  } = runtimeState;
  const {
    mailStatus,
    setMailStatus,
    mailbox,
    setMailbox,
    health,
    setHealth,
    targets,
    setTargets,
    selectedAgentID,
    setSelectedAgentID,
    controlTarget,
    setControlTarget,
    directiveMessage,
    setDirectiveMessage,
    chatMode,
    setChatMode,
    chatMessage,
    setChatMessage,
    verticalName,
    setVerticalName,
    verticalGeo,
    setVerticalGeo,
    verticalSlug,
    setVerticalSlug,
    requeueEventID,
    setRequeueEventID,
    requeueAgentID,
    setRequeueAgentID,
    mailboxID,
    setMailboxID,
    mailboxAction,
    setMailboxAction,
    mailboxNotes,
    setMailboxNotes,
    resetConfirm,
    setResetConfirm,
    controlOutput,
    setControlOutput,
  } = opsState;
  const {
    funnel,
    setFunnel,
    shardScans,
    setShardScans,
    selectedShardScanID,
    setSelectedShardScanID,
    shardScanDetails,
    setShardScanDetails,
    traceVertical,
    setTraceVertical,
    traceRows,
    setTraceRows,
    verticals,
    setVerticals,
    graphMode,
    setGraphMode,
    graphVertical,
    setGraphVertical,
    graph,
    setGraph,
    graphViewGraph,
    setGraphViewGraph,
    selectedGraphNodeID,
    setSelectedGraphNodeID,
    selectedGraphEdgeID,
    setSelectedGraphEdgeID,
    graphFullscreen,
    setGraphFullscreen,
    flowView,
    setFlowView,
    flowVertical,
    setFlowVertical,
    flowGraph,
    setFlowGraph,
    flowGraphMeta,
    setFlowGraphMeta,
    flowEvents,
    setFlowEvents,
    selectedFlowNodeID,
    setSelectedFlowNodeID,
    selectedFlowEdgeID,
    setSelectedFlowEdgeID,
    flowViewGraph,
    setFlowViewGraph,
    flowStart,
    setFlowStart,
    flowEnd,
    setFlowEnd,
    flowStage,
    setFlowStage,
    flowRubric,
    setFlowRubric,
    flowReplaySpeed,
    setFlowReplaySpeed,
    flowReplayOn,
    setFlowReplayOn,
    flowReplayIndex,
    setFlowReplayIndex,
    holdingData,
    setHoldingData,
    holdingDetailModal,
    setHoldingDetailModal,
  } = pipelineState;

  const [toasts, setToasts] = useState([]);
  const toastSeq = useRef(0);
  const addToast = useCallback((msg, type) => {
    const id = ++toastSeq.current;
    setToasts((prev) => [...prev, { id, msg, type: type || "info" }]);
    setTimeout(() => setToasts((prev) => prev.filter((toast) => toast.id !== id)), 4000);
  }, []);

  const loadAgents = useCallback(async () => {
    setAgentsResp(await fetchAgents());
  }, []);

  const {
    loadOverview,
    loadTasks,
    loadMailbox,
    loadDigest,
    loadHealth,
    loadTargets,
  } = useDashboardCoreData({
    setOverview,
    setStatusText,
    relTime,
    taskStatus,
    setTasksResp,
    mailStatus,
    setMailbox,
    setDigestResp,
    setHealth,
    setTargets,
    setControlTarget,
  });

  const {
    loadEvents,
    loadRuntimeLogs,
    loadLogs,
    loadIncidents,
    loadIncidentLogs,
    loadIncidentArtifacts,
    loadEventDetail,
    loadConversations,
    loadConversationDetail,
  } = useDashboardRuntimeData({
    activeView,
    addToast,
    eventsFilter,
    eventsRuntimeErrorsOnly,
    setEvents,
    setRuntimeLogs,
    logsFilter,
    logsOrder,
    logsRuntimeErrorsOnly,
    setLogsData,
    incidentsFilter,
    setIncidentsData,
    setSelectedIncidentCode,
    selectedIncidentCode,
    setSelectedIncidentAgent,
    selectedIncidentAgent,
    setIncidentLogs,
    setIncidentArtifacts,
    selectedConv,
    setConversations,
    setSelectedConv,
    setConversationDetail,
    selectedEventID,
    setEventDetail,
  });

  const {
    loadFunnel,
    loadShardScans,
    loadShardScanDetail,
    shardAction,
    loadTrace,
    loadHolding,
    openHoldingVerticalDetail,
    loadVerticals,
    loadGraph,
    loadPipelineFlow,
  } = useDashboardPipelineData({
    activeView,
    addToast,
    setFunnel,
    setShardScans,
    setShardScanDetails,
    selectedShardScanID,
    setSelectedShardScanID,
    shardScans,
    setTraceRows,
    setHoldingData,
    setHoldingDetailModal,
    graphMode,
    graphVertical,
    setGraphVertical,
    setVerticals,
    flowVertical,
    setFlowVertical,
    selectedGraphNodeID,
    setSelectedGraphNodeID,
    selectedGraphEdgeID,
    setSelectedGraphEdgeID,
    setGraph,
    flowView,
    flowStart,
    flowEnd,
    selectedFlowNodeID,
    setSelectedFlowNodeID,
    selectedFlowEdgeID,
    setSelectedFlowEdgeID,
    setFlowGraph,
    setFlowGraphMeta,
    setFlowEvents,
    setFlowReplayIndex,
    setFlowReplayOn,
  });

  const refreshAll = useCallback(async () => {
    await Promise.all([
      loadOverview(),
      loadAgents(),
      loadDigest(),
      loadTasks(),
      loadEvents(),
      loadRuntimeLogs(),
      loadConversations(),
      loadTargets(),
      loadFunnel(),
      loadShardScans(),
      loadMailbox(),
      loadHealth(),
      loadVerticals(),
      loadHolding(),
      loadIncidents(),
    ]);
  }, [loadOverview, loadAgents, loadDigest, loadTasks, loadEvents, loadRuntimeLogs, loadConversations, loadTargets, loadFunnel, loadShardScans, loadMailbox, loadHealth, loadVerticals, loadHolding, loadIncidents]);

  useEffect(() => {
    if (!graphFullscreen) return;
    function onKey(event) {
      if (event.key === "Escape") setGraphFullscreen(false);
    }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [graphFullscreen]);

  useEffect(() => {
    refreshAll()
      .catch((err) => { setStatusText(`Dashboard error: ${err.message}`); })
      .finally(() => setInitialLoading(false));
  }, [refreshAll]);

  useEventStream({
    eventsFilter,
    eventsIncludeRuntime,
    eventsRuntimeErrorsOnly,
    getKey: getEmpireKey,
    loadEvents,
    loadRuntimeLogs,
    addToast,
  });

  useFlowRuntimeStream({
    activeView,
    flowView,
    flowVertical,
    getKey: getEmpireKey,
    setFlowEvents,
  });

  useReplayTicker({
    flowView,
    flowReplayOn,
    flowReplaySpeed,
    flowEvents,
    setFlowReplayIndex,
    setFlowReplayOn,
  });

  useDashboardPolling({
    loadOverview,
    loadAgents,
    loadDigest,
    loadTasks,
    loadMailbox,
    loadHealth,
    loadRuntimeLogs,
    loadIncidents,
    loadTargets,
    loadFunnel,
    loadVerticals,
    loadHolding,
    activeView,
    flowView,
    loadPipelineFlow,
  });

  const actions = useDashboardActions({
    addToast,
    setControlOutput,
    loadAgents,
    loadTasks,
    loadEvents,
    loadMailbox,
    loadTargets,
    loadOverview,
    loadFunnel,
    setControlTarget,
    setActiveView,
    setSelectedAgentID,
    selectedTaskID,
    setSelectedTaskID,
    taskResultText,
    setTaskResultText,
    taskOutcome,
    setTaskOutcome,
    taskFollowUpNeeded,
    setTaskFollowUpNeeded,
    taskRejectReason,
    setTaskRejectReason,
    setTasksStats,
    setSelectedEventID,
    setSelectedConv,
    setEventsFilter,
    setEventsRuntimeErrorsOnly,
    setLogsFilter,
    setLogsRuntimeErrorsOnly,
  });

  const derived = useDashboardDerivedState({
    agentSearch,
    agentsResp,
    selectedAgentID,
    setSelectedAgentID,
    events,
    eventsRuntimeErrorsOnly,
    runtimeLogs,
    logsData,
    logsRuntimeErrorsOnly,
    selectedLogID,
    setSelectedLogID,
    incidentsData,
    selectedIncidentCode,
    graph,
    graphViewGraph,
    selectedGraphNodeID,
    setSelectedGraphNodeID,
    selectedGraphEdgeID,
    setSelectedGraphEdgeID,
    flowGraphMeta,
    flowEvents,
    flowView,
    flowReplayIndex,
    flowStage,
    flowRubric,
    flowGraph,
    flowViewGraph,
    selectedFlowNodeID,
    setSelectedFlowNodeID,
    selectedFlowEdgeID,
    setSelectedFlowEdgeID,
    tasksResp,
    selectedTaskID,
    health,
    holdingData,
    mailbox,
    funnel,
  });

  return {
    activeView,
    setActiveView,
    statusText,
    apiKey,
    setApiKey,
    initialLoading,
    agentSearch,
    setAgentSearch,
    selectedMailboxItem,
    setSelectedMailboxItem,
    modalContent,
    setModalContent,
    overview,
    agentsResp,
    digestResp,
    taskStatus,
    setTaskStatus,
    tasksResp,
    selectedTaskID,
    setSelectedTaskID,
    taskResultText,
    setTaskResultText,
    taskOutcome,
    setTaskOutcome,
    taskFollowUpNeeded,
    setTaskFollowUpNeeded,
    taskRejectReason,
    setTaskRejectReason,
    tasksStats,
    eventsFilter,
    setEventsFilter,
    eventsIncludeRuntime,
    setEventsIncludeRuntime,
    eventsRuntimeErrorsOnly,
    setEventsRuntimeErrorsOnly,
    events,
    runtimeLogs,
    selectedEventID,
    setSelectedEventID,
    eventDetail,
    conversations,
    selectedConv,
    setSelectedConv,
    conversationDetail,
    funnel,
    shardScans,
    selectedShardScanID,
    setSelectedShardScanID,
    shardScanDetails,
    traceVertical,
    setTraceVertical,
    traceRows,
    mailStatus,
    setMailStatus,
    mailbox,
    health,
    targets,
    selectedAgentID,
    setSelectedAgentID,
    logsFilter,
    setLogsFilter,
    logsRuntimeErrorsOnly,
    setLogsRuntimeErrorsOnly,
    logsData,
    selectedLogID,
    setSelectedLogID,
    logsOrder,
    setLogsOrder,
    incidentsFilter,
    setIncidentsFilter,
    incidentsData,
    selectedIncidentCode,
    setSelectedIncidentCode,
    selectedIncidentAgent,
    setSelectedIncidentAgent,
    incidentLogs,
    incidentArtifacts,
    controlTarget,
    setControlTarget,
    directiveMessage,
    setDirectiveMessage,
    chatMode,
    setChatMode,
    chatMessage,
    setChatMessage,
    verticalName,
    setVerticalName,
    verticalGeo,
    setVerticalGeo,
    verticalSlug,
    setVerticalSlug,
    requeueEventID,
    setRequeueEventID,
    requeueAgentID,
    setRequeueAgentID,
    mailboxID,
    setMailboxID,
    mailboxAction,
    setMailboxAction,
    mailboxNotes,
    setMailboxNotes,
    resetConfirm,
    setResetConfirm,
    controlOutput,
    verticals,
    graphMode,
    setGraphMode,
    graphVertical,
    setGraphVertical,
    graph,
    graphViewGraph,
    setGraphViewGraph,
    selectedGraphNodeID,
    setSelectedGraphNodeID,
    selectedGraphEdgeID,
    setSelectedGraphEdgeID,
    graphFullscreen,
    setGraphFullscreen,
    flowView,
    setFlowView,
    flowVertical,
    setFlowVertical,
    flowGraph,
    flowGraphMeta,
    flowEvents,
    selectedFlowNodeID,
    setSelectedFlowNodeID,
    selectedFlowEdgeID,
    setSelectedFlowEdgeID,
    flowViewGraph,
    setFlowViewGraph,
    flowStart,
    setFlowStart,
    flowEnd,
    setFlowEnd,
    flowStage,
    setFlowStage,
    flowRubric,
    setFlowRubric,
    flowReplaySpeed,
    setFlowReplaySpeed,
    flowReplayOn,
    setFlowReplayOn,
    flowReplayIndex,
    setFlowReplayIndex,
    holdingData,
    holdingDetailModal,
    setHoldingDetailModal,
    toasts,
    loadAgents,
    loadOverview,
    loadTasks,
    loadMailbox,
    loadDigest,
    loadHealth,
    loadTargets,
    loadEvents,
    loadRuntimeLogs,
    loadLogs,
    loadIncidents,
    loadConversationDetail,
    loadFunnel,
    loadShardScanDetail,
    shardAction,
    loadTrace,
    loadVerticals,
    loadGraph,
    loadPipelineFlow,
    openHoldingVerticalDetail,
    addToast,
    ...derived,
    ...actions,
  };
}
