import { useMemo } from "react";
import { useFlowController } from "../features/flow/useFlowController.js";
import { useGraphController } from "../features/graph/useGraphController.js";
import { useHoldingController } from "../features/holding/useHoldingController.js";
import { usePipelineController } from "../features/pipeline/usePipelineController.js";

export function useDashboardPipelineController({
  verticals,
  visibleFlowEvents,
  flowEvents,
  flowGraph,
  flowGraphMeta,
  flowActiveEdgeKeys,
  selectedFlowSummary,
  agentsResp,
  flowView,
  setFlowView,
  flowStage,
  setFlowStage,
  flowStageOptions,
  flowRubric,
  setFlowRubric,
  flowRubricOptions,
  flowVertical,
  setFlowVertical,
  flowStart,
  setFlowStart,
  flowEnd,
  setFlowEnd,
  flowReplaySpeed,
  setFlowReplaySpeed,
  flowReplayOn,
  setFlowReplayOn,
  flowReplayIndex,
  setFlowReplayIndex,
  loadPipelineFlow,
  addToast,
  selectedFlowNodeID,
  setSelectedFlowNodeID,
  selectedFlowEdgeID,
  setSelectedFlowEdgeID,
  flowViewGraph,
  setFlowViewGraph,
  graphFullscreen,
  setGraphFullscreen,
  graph,
  graphViewGraph,
  setGraphViewGraph,
  graphMode,
  setGraphMode,
  graphVertical,
  setGraphVertical,
  selectedGraphNodeID,
  setSelectedGraphNodeID,
  selectedGraphEdgeID,
  setSelectedGraphEdgeID,
  loadVerticals,
  loadGraph,
  restartAgent,
  openControl,
  inspectAgent,
  navigateToTask,
  funnel,
  shardScans,
  shardScanDetails,
  traceRows,
  traceVertical,
  setTraceVertical,
  selectedShardScanID,
  setSelectedShardScanID,
  loadTrace,
  loadShardScanDetail,
  shardAction,
  holdingViewState,
  openHoldingVerticalDetail,
}) {
  const flow = useFlowController({
    verticals,
    visibleFlowEvents,
    flowEvents,
    flowGraph,
    flowGraphMeta,
    flowActiveEdgeKeys,
    selectedFlowSummary,
    agents: agentsResp.agents,
    flowView,
    flowStage,
    flowStageOptions,
    flowRubric,
    flowRubricOptions,
    flowVertical,
    flowStart,
    flowEnd,
    flowReplaySpeed,
    flowReplayOn,
    flowReplayIndex,
    selectedFlowNodeID,
    selectedFlowEdgeID,
    flowViewGraph,
    graphFullscreen,
    setFlowView,
    setFlowStage,
    setFlowRubric,
    setFlowVertical,
    setFlowStart,
    setFlowEnd,
    setFlowReplaySpeed,
    setFlowReplayOn,
    setFlowReplayIndex,
    refresh: () => loadPipelineFlow().catch((err) => addToast(err.message, "error")),
    addToast,
    setSelectedFlowNodeID,
    setSelectedFlowEdgeID,
    setFlowViewGraph,
    setGraphFullscreen,
  });

  const graphController = useGraphController({
    verticals,
    graph,
    graphViewGraph,
    agents: agentsResp.agents,
    graphMode,
    graphVertical,
    selectedGraphNodeID,
    selectedGraphEdgeID,
    graphFullscreen,
    setGraphMode,
    setGraphVertical,
    setSelectedGraphNodeID,
    setSelectedGraphEdgeID,
    setGraphFullscreen,
    refreshGraph: () => Promise.all([loadVerticals(), loadGraph()]),
    setGraphViewGraph,
    restartAgent,
    openControl,
    inspectAgent,
    navigateToTask,
  });

  const pipeline = usePipelineController({
    funnel,
    shardScans,
    shardScanDetails,
    traceRows,
    traceVertical,
    selectedShardScanID,
    setTraceVertical,
    setSelectedShardScanID,
    traceVerticalFlow: loadTrace,
    loadShardScanDetail,
    shardAction,
  });

  const holding = useHoldingController({
    domain: holdingViewState.domain,
    controls: holdingViewState.controls,
    openHoldingVerticalDetail,
  });

  return useMemo(() => ({
    flow,
    graph: graphController,
    pipeline,
    holding,
  }), [flow, graphController, pipeline, holding]);
}
