import { useMemo } from "react";

export function useTasksController({
  tasksResp,
  tasksStats,
  selectedTask,
  taskStatus,
  selectedTaskID,
  taskResultText,
  taskOutcome,
  taskFollowUpNeeded,
  taskRejectReason,
  setTaskStatus,
  setSelectedTaskID,
  setTaskResultText,
  setTaskOutcome,
  setTaskFollowUpNeeded,
  setTaskRejectReason,
  refreshTasks,
  loadTaskStats,
  claimSelectedTask,
  completeSelectedTask,
  rejectSelectedTask,
}) {
  return useMemo(() => ({
    state: {
      tasksResp,
      tasksStats,
      selectedTask,
      taskStatus,
      selectedTaskID,
      taskResultText,
      taskOutcome,
      taskFollowUpNeeded,
      taskRejectReason,
    },
    actions: {
      setTaskStatus,
      setSelectedTaskID,
      setTaskResultText,
      setTaskOutcome,
      setTaskFollowUpNeeded,
      setTaskRejectReason,
      refreshTasks,
      loadTaskStats,
      claimSelectedTask,
      completeSelectedTask,
      rejectSelectedTask,
    },
  }), [
    claimSelectedTask,
    completeSelectedTask,
    loadTaskStats,
    refreshTasks,
    rejectSelectedTask,
    selectedTask,
    selectedTaskID,
    setSelectedTaskID,
    setTaskFollowUpNeeded,
    setTaskOutcome,
    setTaskRejectReason,
    setTaskResultText,
    setTaskStatus,
    taskFollowUpNeeded,
    taskOutcome,
    taskRejectReason,
    taskResultText,
    taskStatus,
    tasksResp,
    tasksStats,
  ]);
}
