name: notify-all-children
version: "1.0.0"
platform_version: ">=0.7.0 <0.8.0"
flows:
  - id: portfolio
    flow: portfolio
    mode: singleton
  - id: account
    flow: account
    mode: template
connect:
  - event: account.registered
    from: portfolio
    to: account
  - event: account.notify.requested
    from: portfolio
    to: account
