.PHONY: reset-dev run-corpus run-directive run-clear run-clear-directed

CONTRACTS_ROOT ?= /Users/youmew/swarm/empire/contracts
HEALTH_ADDR ?= 0.0.0.0:8081

SWARM_DB_HOST ?= 127.0.0.1
SWARM_DB_PORT ?= 5432
SWARM_DB_NAME ?= swarm
SWARM_DB_USER ?= postgres
SWARM_DB_PASSWORD ?= postgres

LOG_FILE ?= /tmp/swarm-empire.log
PID_FILE ?= /tmp/swarm-empire.pid
TOKEN_FILE ?= /tmp/swarm-empire.token
START_TIMEOUT ?= 60

SWARM_API_TOKEN ?=
DIRECTIVE_AGENT ?=
DIRECTIVE_MESSAGE ?=
CORPUS_PATH ?= /data/test-signals-25.jsonl
CORPUS_MODE ?= corpus
CORPUS_GEOGRAPHY ?= US
RUN_CLEAR_INPUT_EVENT ?=
RUN_CLEAR_INPUT_PAYLOAD_JSON ?=
SWARM_TOOL_GATEWAY_URL ?=
SWARM_TOOL_GATEWAY_CONTAINER_URL ?=

RUN_CLEAR_ENV = CONTRACTS_ROOT="$(CONTRACTS_ROOT)" HEALTH_ADDR="$(HEALTH_ADDR)" SWARM_DB_HOST="$(SWARM_DB_HOST)" SWARM_DB_PORT="$(SWARM_DB_PORT)" SWARM_DB_NAME="$(SWARM_DB_NAME)" SWARM_DB_USER="$(SWARM_DB_USER)" SWARM_DB_PASSWORD="$(SWARM_DB_PASSWORD)" LOG_FILE="$(LOG_FILE)" PID_FILE="$(PID_FILE)" TOKEN_FILE="$(TOKEN_FILE)" START_TIMEOUT="$(START_TIMEOUT)" SWARM_API_TOKEN="$(SWARM_API_TOKEN)" DIRECTIVE_AGENT="$(DIRECTIVE_AGENT)" DIRECTIVE_MESSAGE="$(DIRECTIVE_MESSAGE)" CORPUS_PATH="$(CORPUS_PATH)" CORPUS_MODE="$(CORPUS_MODE)" CORPUS_GEOGRAPHY="$(CORPUS_GEOGRAPHY)" RUN_CLEAR_INPUT_EVENT="$(RUN_CLEAR_INPUT_EVENT)" RUN_CLEAR_INPUT_PAYLOAD_JSON="$(RUN_CLEAR_INPUT_PAYLOAD_JSON)" SWARM_TOOL_GATEWAY_URL="$(SWARM_TOOL_GATEWAY_URL)" SWARM_TOOL_GATEWAY_CONTAINER_URL="$(SWARM_TOOL_GATEWAY_CONTAINER_URL)"

reset-dev:
	@$(RUN_CLEAR_ENV) ./scripts/run_clear.sh reset-dev

run-corpus:
	@$(RUN_CLEAR_ENV) ./scripts/run_clear.sh run-corpus

run-directive:
	@$(RUN_CLEAR_ENV) ./scripts/run_clear.sh run-directive

run-clear:
	@$(RUN_CLEAR_ENV) ./scripts/run_clear.sh run-clear

run-clear-directed:
	@$(RUN_CLEAR_ENV) ./scripts/run_clear.sh run-clear-directed
