.PHONY: run-clear

CONTRACTS_ROOT ?= /Users/youmew/swarm/empire/contracts
HEALTH_ADDR ?= 0.0.0.0:8081

SWARM_DB_HOST ?= 127.0.0.1
SWARM_DB_PORT ?= 5432
SWARM_DB_NAME ?= swarm
SWARM_DB_USER ?= postgres
SWARM_DB_PASSWORD ?= postgres

LOG_FILE ?= /tmp/swarm-empire.log
PID_FILE ?= /tmp/swarm-empire.pid
START_TIMEOUT ?= 60

DIRECTIVE_AGENT ?=
DIRECTIVE_MESSAGE ?=
CORPUS_PATH ?= /data/test-signals-25.jsonl
CORPUS_MODE ?= corpus
CORPUS_GEOGRAPHY ?= US
SWARM_TOOL_GATEWAY_URL ?=
SWARM_TOOL_GATEWAY_CONTAINER_URL ?=

run-clear:
	@CONTRACTS_ROOT="$(CONTRACTS_ROOT)" \
	HEALTH_ADDR="$(HEALTH_ADDR)" \
	SWARM_DB_HOST="$(SWARM_DB_HOST)" \
	SWARM_DB_PORT="$(SWARM_DB_PORT)" \
	SWARM_DB_NAME="$(SWARM_DB_NAME)" \
	SWARM_DB_USER="$(SWARM_DB_USER)" \
	SWARM_DB_PASSWORD="$(SWARM_DB_PASSWORD)" \
	LOG_FILE="$(LOG_FILE)" \
	PID_FILE="$(PID_FILE)" \
	START_TIMEOUT="$(START_TIMEOUT)" \
	DIRECTIVE_AGENT="$(DIRECTIVE_AGENT)" \
	DIRECTIVE_MESSAGE="$(DIRECTIVE_MESSAGE)" \
	CORPUS_PATH="$(CORPUS_PATH)" \
	CORPUS_MODE="$(CORPUS_MODE)" \
	CORPUS_GEOGRAPHY="$(CORPUS_GEOGRAPHY)" \
	SWARM_TOOL_GATEWAY_URL="$(SWARM_TOOL_GATEWAY_URL)" \
	SWARM_TOOL_GATEWAY_CONTAINER_URL="$(SWARM_TOOL_GATEWAY_CONTAINER_URL)" \
	./scripts/run_clear.sh
