name: initiator
mode: static
pins:
  inputs:
    events:
      - event: requester.setup.requested
        source: external
      - event: request.submitted
        source: external
  outputs:
    events:
      - requester.setup
      - requester.requested
