name: producer
mode: static
pins:
  inputs:
    events:
      - event: account.setup.requested
        source: external
      - event: account.work.requested
        source: external
  outputs:
    events:
      - account.setup
      - account.ready
