name: producer
mode: static
pins:
  inputs:
    events:
      - name: validation_triggered
        event: validation.triggered
        source: external
      - name: validation_started
        event: validation.started
  outputs:
    events:
      - name: validation_requested
        event: validation.requested
