name: fan-in-barrier
pins:
  inputs:
    - operating.report.triggered
    - portfolio.setup
  outputs:
    - operating.report.triggered
    - portfolio.setup
connect:
  - event: operating.report.triggered
    from: .
    to: ingress
  - event: portfolio.setup
    from: .
    to: portfolio
    resolution: select-or-create
  - event: operating.report.requested
    from: ingress
    to: operating
    resolution: create
    key_from: event.id
  - event: operating.reported
    from: operating
    to: portfolio
    resolution: select
