package main

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func fixtureRepo(t *testing.T, files map[string]string) string {
	t.Helper()
	repo := t.TempDir()
	g(t, repo, "init", "-b", "master")
	g(t, repo, "config", "user.name", "complexity-test")
	g(t, repo, "config", "user.email", "complexity-test@example.invalid")
	for path, content := range files {
		put(t, repo, path, content)
	}
	commit(t, repo)
	return repo
}

func g(t *testing.T, repo string, args ...string) string {
	t.Helper()
	b, err := git(context.Background(), repo, args...)
	if err != nil {
		t.Fatal(err)
	}
	return strings.TrimSpace(string(b))
}

func put(t *testing.T, repo, path, content string) {
	t.Helper()
	if err := writeFile(filepath.Join(repo, path), []byte(content)); err != nil {
		t.Fatal(err)
	}
}

func commit(t *testing.T, repo string) string {
	t.Helper()
	g(t, repo, "add", ".")
	g(t, repo, "commit", "-qm", "test: snapshot")
	return g(t, repo, "rev-parse", "HEAD")
}

func measured(t *testing.T, repo, ref string) baseline {
	t.Helper()
	sha := g(t, repo, "rev-parse", ref)
	b, err := measure(context.Background(), repo, sha, upstream)
	if err != nil {
		t.Fatal(err)
	}
	return b
}

func TestUpstreamPopulationAndSnapshot(t *testing.T) {
	const source = `package fixture
func init() {}
func init() { if true {} }
var A,B = func(){},func(){ if true {} }
type T[X any] struct{}
func (*T[X]) M() {}
func external()
var C = (func(){})
`
	repo := fixtureRepo(t, map[string]string{
		"testdata/.hidden/_support.go": source,
		"only_types.go":                "package fixture\ntype NoFunctions int\n",
		"tagged_windows.go":            "//go:build windows\n\npackage fixture\nfunc Windows() {}\n",
		"generated.go":                 "// Code generated by fixture. DO NOT EDIT.\npackage fixture\nfunc Excluded(){}\n",
		"not_generated.go":             "package fixture\n// Code generated by fixture. DO NOT EDIT.\nfunc Included(){}\n",
		"excluded_test.go":             "deliberately not Go",
	})
	b := measured(t, repo, "HEAD")
	if len(b.Metrics["cyclo"]) != 8 || len(b.Metrics["cognit"]) != 6 {
		t.Fatalf("populations: %#v", summaries(b))
	}
	var inits, literals, zeros int
	for _, row := range b.Metrics["cyclo"] {
		if row.Identity.Name == "init" {
			inits++
			if row.Identity.Occurrence != inits {
				t.Fatal(row)
			}
		}
		if row.Identity.Kind == "variable-literal" {
			literals++
			if row.Identity.Name != "A" || row.Identity.Occurrence != literals {
				t.Fatal(row)
			}
		}
	}
	for _, row := range b.Metrics["cognit"] {
		if row.Value == 0 {
			zeros++
		}
	}
	if inits != 2 || literals != 2 || zeros != 5 {
		t.Fatalf("init=%d literals=%d zero=%d", inits, literals, zeros)
	}
	classes := map[string]string{}
	for _, f := range b.Files {
		classes[f.Path] = f.Class
	}
	if classes["generated.go"] != "generated" || classes["not_generated.go"] != "authored" || classes["excluded_test.go"] != "test" {
		t.Fatal(classes)
	}
	put(t, repo, "testdata/.hidden/_support.go", "invalid dirty source")
	put(t, repo, "untracked.go", "invalid untracked source")
	if !reflect.DeepEqual(b, measured(t, repo, "HEAD")) {
		t.Fatal("working tree influenced measurement")
	}
	if err := os.Remove(filepath.Join(repo, "untracked.go")); err != nil {
		t.Fatal(err)
	}
	put(t, repo, "testdata/.hidden/_support.go", "\n\n"+source)
	commit(t, repo)
	if !reflect.DeepEqual(b, measured(t, repo, "HEAD")) {
		t.Fatal("line-only shifts changed identities")
	}
}

func TestSourceAdmission(t *testing.T) {
	for name, content := range map[string]string{
		"cyclo":       "package p\n//gocyclo:ignore\nfunc F(){}",
		"cyclo-space": "package p\n//gocyclo: ignore\nfunc F(){}",
		"cognit":      "package p\n//gocognit:ignore\nfunc F(){}",
		"line":        "package p\n//line imaginary.go:100\nfunc F(){}",
		"block-line":  "package p\n/*line imaginary.go:100*/func F(){}",
		"syntax":      "package p\nfunc broken(",
	} {
		t.Run(name, func(t *testing.T) {
			errCalled := false
			repo := fixtureRepo(t, map[string]string{"p.go": content})
			_, err := measure(context.Background(), repo, "HEAD", func(context.Context, string, string) ([]byte, error) { errCalled = true; return nil, nil })
			if err == nil || errCalled {
				t.Fatalf("admitted invalid source: called=%v err=%v", errCalled, err)
			}
		})
	}
	t.Run("no-functions", func(t *testing.T) {
		repo := fixtureRepo(t, map[string]string{"p.go": "package p\ntype T int"})
		b := measured(t, repo, "HEAD")
		if len(b.Metrics["cyclo"])+len(b.Metrics["cognit"]) != 0 {
			t.Fatal(b)
		}
	})
	for _, files := range []map[string]string{{"readme": "empty"}, {"p.go": "// Code generated by fixture. DO NOT EDIT.\npackage p"}} {
		repo := fixtureRepo(t, files)
		if _, err := measure(context.Background(), repo, "HEAD", upstream); err == nil {
			t.Fatal("empty authored inventory passed")
		}
	}
	t.Run("symlink", func(t *testing.T) {
		repo := fixtureRepo(t, map[string]string{"p.go": "package p"})
		if err := os.Symlink("p.go", filepath.Join(repo, "alias.go")); err != nil {
			t.Fatal(err)
		}
		commit(t, repo)
		if _, err := measure(context.Background(), repo, "HEAD", upstream); err == nil {
			t.Fatal("symlink passed")
		}
	})
}

func TestNormalizationRefusesMissingDuplicateAndForeignRows(t *testing.T) {
	expected := population{"/tmp/f.go:1:1": {identity{"f.go", "p", "declaration", "F", 1}, "F", "p"}}
	for _, raw := range []string{"", "1 p F /tmp/f.go:1:1\n1 p F /tmp/f.go:1:1", "1 p F invented.go:1:1", "1 p Wrong /tmp/f.go:1:1", "-1 p F /tmp/f.go:1:1", "no score"} {
		if _, err := normalize("cyclo", []byte(raw), expected); err == nil {
			t.Fatalf("accepted %q", raw)
		}
	}
	if _, err := normalize("cyclo", []byte("0 p F /tmp/f.go:1:1"), expected); err == nil {
		t.Fatal("zero cyclo")
	}
	if rows, err := normalize("cognit", []byte("0 p F /tmp/f.go:1:1"), expected); err != nil || len(rows) != 1 {
		t.Fatalf("%v %v", rows, err)
	}
	if _, err := normalize("cognit", []byte("1 p F /tmp/f.go:1:1"), population{}); err == nil {
		t.Fatal("unexpected nonempty output")
	}
}

func scoreFixture(metric string, value int) baseline {
	b := baseline{Policy: currentPolicy(), Files: []fileRecord{}, Metrics: map[string][]score{"cyclo": {}, "cognit": {}}}
	b.Metrics[metric] = []score{{identity{"p.go", "p", "declaration", "F", 1}, value}}
	return b
}

func TestIndependentThresholdsAndReporting(t *testing.T) {
	for _, metric := range []string{"cyclo", "cognit"} {
		for _, tc := range []struct {
			before, after int
			blocked       bool
		}{{29, 30, true}, {29, 31, true}, {30, 31, false}, {31, 29, false}, {30, 50, false}, {50, 200, false}} {
			d := compare(scoreFixture(metric, tc.before), scoreFixture(metric, tc.after))
			if d.Increased != tc.blocked || len(d.Changes) != 1 {
				t.Fatalf("%s %+v: %+v", metric, tc, d)
			}
		}
	}
	base, head := scoreFixture("cyclo", 30), scoreFixture("cognit", 30)
	if !compare(base, head).Increased || !compare(head, base).Increased {
		t.Fatal("one metric's decrease offset the other's growth")
	}
	head.Files = []fileRecord{{"p.go", "generated"}}
	base.Files = []fileRecord{{"p.go", "authored"}}
	d := compare(base, head)
	if len(d.AddedFiles) != 1 || len(d.RemovedFiles) != 1 {
		t.Fatal(d)
	}
}

func TestGitBaselineAndPolicyAdmission(t *testing.T) {
	ctx := context.Background()
	repo := fixtureRepo(t, map[string]string{"p.go": "package p\nfunc F(){}"})
	base := g(t, repo, "rev-parse", "HEAD")
	if err := run(ctx, options{repo: repo, head: "HEAD", base: base, update: true}, io.Discard); err != nil {
		t.Fatal(err)
	}
	head := commit(t, repo)
	if err := run(ctx, options{repo: repo, head: head, base: base, evidence: t.TempDir()}, io.Discard); err != nil {
		t.Fatal("first baseline:", err)
	}
	valid := measured(t, repo, head)
	data, _ := encode(valid)
	put(t, repo, baselinePath, strings.Replace(string(data), `"value":1`, `"value":999`, 1))
	inflated := commit(t, repo)
	if err := run(ctx, options{repo: repo, head: inflated, base: base}, io.Discard); err == nil {
		t.Fatal("self bump passed")
	}
	put(t, repo, baselinePath, string(data))
	commit(t, repo)
	if err := run(ctx, options{repo: repo, head: "HEAD", base: "missing-base"}, io.Discard); err == nil {
		t.Fatal("missing base passed")
	}
	valid.Policy.Threshold = 31
	changed, _ := encode(valid)
	put(t, repo, baselinePath, string(changed))
	policySHA := commit(t, repo)
	if err := checkBasePolicy(ctx, repo, policySHA, measured(t, repo, policySHA)); err == nil {
		t.Fatal("policy reset passed")
	}
	put(t, repo, baselinePath, string(data)+"{}")
	malformed := commit(t, repo)
	if err := checkBaseline(ctx, repo, malformed, data); err == nil {
		t.Fatal("trailing JSON accepted")
	}
	if err := checkBasePolicy(ctx, repo, malformed, measured(t, repo, malformed)); err == nil {
		t.Fatal("malformed base accepted")
	}
}

func TestRealGitIndependentGrowthAndPRHeadNotMerge(t *testing.T) {
	ctx := context.Background()
	for _, metric := range []string{"cyclo", "cognit"} {
		t.Run(metric, func(t *testing.T) {
			// Flat ifs yield cyclo N+1 and cognit N, exercising each boundary independently.
			n := 28
			if metric == "cognit" {
				n = 29
			}
			source := func(n int) string { return "package p\nfunc F(){" + strings.Repeat("if true {}\n", n) + "}" }
			repo := fixtureRepo(t, map[string]string{"p.go": source(n)})
			if err := run(ctx, options{repo: repo, head: "HEAD", update: true}, io.Discard); err != nil {
				t.Fatal(err)
			}
			base := commit(t, repo)
			g(t, repo, "checkout", "-qb", "feature")
			put(t, repo, "p.go", source(n+1))
			commit(t, repo)
			if err := run(ctx, options{repo: repo, head: "HEAD", update: true}, io.Discard); err != nil {
				t.Fatal(err)
			}
			head := commit(t, repo)
			var evidence bytes.Buffer
			err := run(ctx, options{repo: repo, head: head, base: base}, &evidence)
			if err == nil || !strings.Contains(err.Error(), "count increased") {
				t.Fatalf("self-raised measured baseline accepted: %v", err)
			}
			g(t, repo, "checkout", "master")
			put(t, repo, "merge_only.go", "package p\nfunc M(){}")
			commit(t, repo)
			g(t, repo, "merge", "--no-edit", "feature")
			merge := g(t, repo, "rev-parse", "HEAD")
			if merge == head {
				t.Fatal("no synthetic merge")
			}
			event := fmt.Sprintf(`{"pull_request":{"head":{"sha":%q},"base":{"sha":%q}}}`, head, base)
			put(t, repo, "event.json", event)
			evidence.Reset()
			err = run(ctx, options{repo: repo, head: merge, event: "pull_request", eventFile: filepath.Join(repo, "event.json")}, &evidence)
			if err == nil || !strings.Contains(evidence.String(), head) || strings.Contains(evidence.String(), "merge_only.go") {
				t.Fatalf("wrong PR snapshot: %v %s", err, evidence.String())
			}
		})
	}
}

func TestEventAdmission(t *testing.T) {
	head, base := strings.Repeat("a", 40), strings.Repeat("b", 40)
	for event, payload := range map[string]string{"push": fmt.Sprintf(`{"before":%q,"after":%q}`, base, head), "pull_request": fmt.Sprintf(`{"pull_request":{"head":{"sha":%q},"base":{"sha":%q}}}`, head, base)} {
		h, b, err := eventRevisions(event, []byte(payload))
		if err != nil || h != head || b != base {
			t.Fatalf("%s %s %s %v", event, h, b, err)
		}
		for _, invalid := range []string{"{}", "invalid", strings.ReplaceAll(payload, base, strings.Repeat("0", 40))} {
			if _, _, err := eventRevisions(event, []byte(invalid)); err == nil {
				t.Fatal("missing comparison accepted")
			}
		}
	}
	for _, event := range []string{"workflow_dispatch", "schedule"} {
		o := options{event: event, head: "HEAD"}
		if err := applyEvent(&o); err != nil || o.base != "" {
			t.Fatal("invented manual history", o, err)
		}
	}
	for _, o := range []options{{event: "push", update: true}, {event: "push", base: base}, {eventFile: "unexpected"}, {event: "unknown"}} {
		if err := applyEvent(&o); err == nil {
			t.Fatal("invalid options admitted", o)
		}
	}
}
