name: requester
mode: template
instance: account_id
initial_state: active
states: [active]
pins:
  inputs:
    events:
      - event: requester.setup
        resolution:
          mode: select-or-create
      - event: requester.requested
        resolution:
          mode: select
      - event: provider.replied
        resolution:
          mode: reply
          replies_to: provider.requested
  outputs:
    events:
      - provider.requested
