name: requester
instance: account_id
pins:
  inputs:
    events:
      - requester.setup
      - requester.requested
      - event: provider.replied
        resolution:
          mode: reply
          replies_to: provider.requested
  outputs:
    events:
      - provider.requested
