name: template-select-existing
pins:
  inputs:
    - account.setup.requested
    - account.work.requested
  outputs:
    - account.setup.requested
    - account.work.requested
connect:
  - event: account.setup.requested
    from: .
    to: producer
  - event: account.work.requested
    from: .
    to: producer
  - event: account.setup
    from: producer
    to: account
    resolution: select-or-create
  - event: account.ready
    from: producer
    to: account
    resolution: select
