name: template-reply
version: "1.0.0"
platform_version: ">=0.7.0 <0.8.0"
flows:
  - id: initiator
    flow: initiator
    mode: static
  - id: requester
    flow: requester
    mode: template
  - id: provider
    flow: provider
    mode: static
connect:
  - event: requester.setup
    from: initiator
    to: requester
  - event: requester.requested
    from: initiator
    to: requester
  - event: provider.requested
    from: requester
    to: provider
  - event: provider.replied
    from: provider
    to: requester
