package main

import (
	"fmt"
	"go/types"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

type method struct {
	receiver string
	field    string
	name     string
	sig      *types.Signature
	depth    int
}

type imports struct {
	byPath map[string]string
	used   map[string]string
}

func main() {
	cfg := &packages.Config{Mode: packages.NeedName | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedImports | packages.NeedSyntax | packages.NeedCompiledGoFiles}
	pkgs, err := packages.Load(cfg, "github.com/division-sh/swarm/internal/store/internal/runtimepersistence")
	if err != nil || packages.PrintErrors(pkgs) > 0 || len(pkgs) != 1 {
		panic("load runtimepersistence")
	}
	loaded := pkgs[0]
	pkg := loaded.Types
	var methods []method
	for _, typeName := range []string{"PostgresStore", "SQLiteRuntimeStore"} {
		obj, _ := pkg.Scope().Lookup(typeName).(*types.TypeName)
		named, _ := types.Unalias(obj.Type()).(*types.Named)
		strct, _ := named.Underlying().(*types.Struct)
		declared := declaredMethodNames(loaded, named)
		candidates := map[string][]method{}
		for index := 0; index < strct.NumFields(); index++ {
			field := strct.Field(index)
			if !facadeOwnerField(field.Name()) {
				continue
			}
			set := types.NewMethodSet(field.Type())
			for methodIndex := 0; methodIndex < set.Len(); methodIndex++ {
				fn, _ := set.At(methodIndex).Obj().(*types.Func)
				if fn == nil || !fn.Exported() || constructionBinding(fn.Name()) || strings.HasSuffix(fn.Name(), "ForTest") {
					continue
				}
				sig, _ := fn.Type().(*types.Signature)
				if sig == nil || containsRawSQL(sig) {
					continue
				}
				candidates[fn.Name()] = append(candidates[fn.Name()], method{receiver: typeName, field: field.Name(), name: fn.Name(), sig: sig, depth: len(set.At(methodIndex).Index())})
			}
		}
		for name, owners := range candidates {
			if declared[name] {
				continue
			}
			sort.Slice(owners, func(i, j int) bool { return owners[i].depth < owners[j].depth })
			if len(owners) > 1 && owners[0].depth == owners[1].depth {
				continue
			}
			methods = append(methods, owners[0])
		}
	}
	sort.Slice(methods, func(i, j int) bool {
		if methods[i].receiver != methods[j].receiver {
			return methods[i].receiver < methods[j].receiver
		}
		return methods[i].name < methods[j].name
	})
	imps := &imports{byPath: map[string]string{}, used: map[string]string{}}
	for _, current := range methods {
		collectPackages(current.sig.Params(), imps)
		collectPackages(current.sig.Results(), imps)
	}
	fmt.Println("// Code generated by internal/genfacade; DO NOT EDIT.")
	fmt.Println("package runtimepersistence")
	fmt.Println()
	if len(imps.byPath) > 0 {
		fmt.Println("import (")
		paths := make([]string, 0, len(imps.byPath))
		for path := range imps.byPath {
			paths = append(paths, path)
		}
		sort.Strings(paths)
		for _, path := range paths {
			fmt.Printf("\t%s %q\n", imps.byPath[path], path)
		}
		fmt.Println(")")
		fmt.Println()
	}
	for index, current := range methods {
		params, args := renderParams(current.sig, imps)
		results := renderResults(current.sig, imps)
		fmt.Printf("func (s *%s) %s(%s)%s {\n", current.receiver, current.name, params, results)
		if current.sig.Results().Len() > 0 {
			fmt.Printf("\treturn s.%s.%s(%s)\n", current.field, current.name, args)
		} else {
			fmt.Printf("\ts.%s.%s(%s)\n", current.field, current.name, args)
		}
		fmt.Println("}")
		if index < len(methods)-1 {
			fmt.Println()
		}
	}
}

func facadeOwnerField(name string) bool {
	switch name {
	case "backend", "runBundles", "workflowEntityQueries", "workflowRoutes", "workspaceLookups", "schemaOwner", "schema", "nowFn", "runLifecycleCandidates", "durableDataOwner":
		return false
	default:
		return true
	}
}

func declaredMethodNames(pkg *packages.Package, named *types.Named) map[string]bool {
	out := make(map[string]bool, named.NumMethods())
	for index := 0; index < named.NumMethods(); index++ {
		method := named.Method(index)
		if strings.HasSuffix(pkg.Fset.PositionFor(method.Pos(), false).Filename, "/facade_forwarders_generated.go") {
			continue
		}
		out[method.Name()] = true
	}
	return out
}

func constructionBinding(name string) bool {
	switch name {
	case "BindDecisionCards", "BindDelivery", "BindDirectiveDependencies", "BindPipeline", "BindRunFork", "BindSelectedForkWriter":
		return true
	default:
		return false
	}
}

func renderParams(sig *types.Signature, imps *imports) (string, string) {
	parts := make([]string, 0, sig.Params().Len())
	args := make([]string, 0, sig.Params().Len())
	used := map[string]int{}
	for index := 0; index < sig.Params().Len(); index++ {
		value := sig.Params().At(index)
		name := value.Name()
		if name == "" || name == "_" {
			name = fmt.Sprintf("arg%d", index)
		}
		if count := used[name]; count > 0 {
			name = fmt.Sprintf("%s%d", name, count)
		}
		used[value.Name()]++
		typeText := typeString(value.Type(), imps)
		if sig.Variadic() && index == sig.Params().Len()-1 {
			slice, _ := types.Unalias(value.Type()).(*types.Slice)
			typeText = "..." + typeString(slice.Elem(), imps)
			args = append(args, name+"...")
		} else {
			args = append(args, name)
		}
		parts = append(parts, name+" "+typeText)
	}
	return strings.Join(parts, ", "), strings.Join(args, ", ")
}

func renderResults(sig *types.Signature, imps *imports) string {
	if sig.Results().Len() == 0 {
		return ""
	}
	parts := make([]string, 0, sig.Results().Len())
	for index := 0; index < sig.Results().Len(); index++ {
		parts = append(parts, typeString(sig.Results().At(index).Type(), imps))
	}
	if len(parts) == 1 {
		return " " + parts[0]
	}
	return " (" + strings.Join(parts, ", ") + ")"
}

func typeString(valueType types.Type, imps *imports) string {
	return types.TypeString(valueType, func(pkg *types.Package) string { return imps.alias(pkg) })
}

func collectPackages(tuple *types.Tuple, imps *imports) {
	if tuple == nil {
		return
	}
	for index := 0; index < tuple.Len(); index++ {
		_ = types.TypeString(tuple.At(index).Type(), func(pkg *types.Package) string { return imps.alias(pkg) })
	}
}

func (i *imports) alias(pkg *types.Package) string {
	if pkg == nil || pkg.Path() == "github.com/division-sh/swarm/internal/store/internal/runtimepersistence" {
		return ""
	}
	if alias, ok := i.byPath[pkg.Path()]; ok {
		return alias
	}
	base := pkg.Name()
	alias := base
	for suffix := 2; ; suffix++ {
		if path, exists := i.used[alias]; !exists || path == pkg.Path() {
			break
		}
		alias = fmt.Sprintf("%s%d", base, suffix)
	}
	i.byPath[pkg.Path()] = alias
	i.used[alias] = pkg.Path()
	return alias
}

func containsRawSQL(valueType types.Type) bool {
	return containsRawSQLSeen(valueType, map[types.Type]bool{})
}

func containsRawSQLSeen(valueType types.Type, seen map[types.Type]bool) bool {
	if valueType == nil {
		return false
	}
	valueType = types.Unalias(valueType)
	if seen[valueType] {
		return false
	}
	seen[valueType] = true
	switch typed := valueType.(type) {
	case *types.Named:
		if object := typed.Obj(); object != nil && object.Pkg() != nil {
			path := object.Pkg().Path()
			if path == "database/sql" {
				switch object.Name() {
				case "DB", "Tx", "Conn", "Rows", "Row", "Result":
					return true
				}
			}
			if (strings.HasPrefix(path, "github.com/division-sh/swarm/internal/store/") ||
				strings.HasPrefix(path, "github.com/division-sh/swarm/internal/persistence/")) &&
				(object.Name() == "Dialect" || strings.HasSuffix(object.Name(), "Queryer") || strings.HasSuffix(object.Name(), "Execer")) {
				return true
			}
		}
		return containsRawSQLSeen(typed.Underlying(), seen)
	case *types.Pointer:
		return containsRawSQLSeen(typed.Elem(), seen)
	case *types.Slice:
		return containsRawSQLSeen(typed.Elem(), seen)
	case *types.Array:
		return containsRawSQLSeen(typed.Elem(), seen)
	case *types.Map:
		return containsRawSQLSeen(typed.Key(), seen) || containsRawSQLSeen(typed.Elem(), seen)
	case *types.Chan:
		return containsRawSQLSeen(typed.Elem(), seen)
	case *types.Signature:
		return tupleRaw(typed.Params(), seen) || tupleRaw(typed.Results(), seen)
	case *types.Struct:
		for index := 0; index < typed.NumFields(); index++ {
			if containsRawSQLSeen(typed.Field(index).Type(), seen) {
				return true
			}
		}
	case *types.Interface:
		for index := 0; index < typed.NumMethods(); index++ {
			if containsRawSQLSeen(typed.Method(index).Type(), seen) {
				return true
			}
		}
	}
	return false
}

func tupleRaw(tuple *types.Tuple, seen map[types.Type]bool) bool {
	if tuple == nil {
		return false
	}
	for index := 0; index < tuple.Len(); index++ {
		if containsRawSQLSeen(tuple.At(index).Type(), seen) {
			return true
		}
	}
	return false
}
