package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type contractEventCatalogEntry struct {
	Payload  any      `yaml:"payload"`
	Required []string `yaml:"required"`
}

type generatedEventSchema struct {
	Description string         `json:"Description"`
	Schema      map[string]any `json:"Schema"`
}

func main() {
	repoRoot, err := findRepoRoot()
	if err != nil {
		fail(err)
	}
	catalogPath := filepath.Join(repoRoot, "contracts", "event-catalog.yaml")
	outPath := filepath.Join(repoRoot, "internal", "runtime", "contracts", "schema_registry_generated.go")

	raw, err := os.ReadFile(catalogPath)
	if err != nil {
		fail(fmt.Errorf("read %s: %w", catalogPath, err))
	}
	catalog := map[string]contractEventCatalogEntry{}
	if err := yaml.Unmarshal(raw, &catalog); err != nil {
		fail(fmt.Errorf("parse %s: %w", catalogPath, err))
	}

	eventNames := make([]string, 0, len(catalog))
	generated := make(map[string]generatedEventSchema, len(catalog))
	for eventType, entry := range catalog {
		eventType = strings.TrimSpace(eventType)
		if eventType == "" {
			continue
		}
		schema, err := buildRootSchema(entry.Payload, entry.Required)
		if err != nil {
			fail(fmt.Errorf("%s: %w", eventType, err))
		}
		eventNames = append(eventNames, eventType)
		generated[eventType] = generatedEventSchema{
			Description: fmt.Sprintf("Generated from contracts/event-catalog.yaml for %s.", eventType),
			Schema:      schema,
		}
	}
	sort.Strings(eventNames)
	ordered := make(map[string]generatedEventSchema, len(eventNames))
	for _, eventType := range eventNames {
		ordered[eventType] = generated[eventType]
	}

	jsonBytes, err := json.MarshalIndent(ordered, "", "\t")
	if err != nil {
		fail(fmt.Errorf("marshal generated schemas: %w", err))
	}

	var buf bytes.Buffer
	buf.WriteString("package contracts\n\n")
	buf.WriteString("// Code generated by scripts/generate_event_schema_registry/main.go; DO NOT EDIT.\n")
	buf.WriteString("// Source: contracts/event-catalog.yaml\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"encoding/json\"\n")
	buf.WriteString("\t\"fmt\"\n")
	buf.WriteString(")\n\n")
	buf.WriteString("//go:generate go run ../../../scripts/generate_event_schema_registry\n")
	buf.WriteString("var generatedContractEventSchemaRegistry = mustLoadGeneratedContractEventSchemaRegistry(`\n")
	buf.Write(jsonBytes)
	buf.WriteString("\n`)\n\n")
	buf.WriteString("func mustLoadGeneratedContractEventSchemaRegistry(raw string) map[string]EventSchema {\n")
	buf.WriteString("\tout := map[string]EventSchema{}\n")
	buf.WriteString("\tif err := json.Unmarshal([]byte(raw), &out); err != nil {\n")
	buf.WriteString("\t\tpanic(fmt.Sprintf(\"parse generated event schema registry: %v\", err))\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn out\n")
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fail(fmt.Errorf("gofmt generated output: %w", err))
	}
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		fail(fmt.Errorf("write %s: %w", outPath, err))
	}
}

func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not locate repo root from %s", dir)
		}
		dir = parent
	}
}

func buildRootSchema(payload any, required []string) (map[string]any, error) {
	props, ok, err := buildObjectProperties(payload)
	if err != nil {
		return nil, err
	}
	if !ok {
		return map[string]any{
			"type":                 "object",
			"properties":           map[string]any{},
			"additionalProperties": false,
		}, nil
	}
	out := map[string]any{
		"type":                 "object",
		"properties":           props,
		"additionalProperties": false,
	}
	if len(required) > 0 {
		out["required"] = required
	}
	return out, nil
}

func buildObjectProperties(raw any) (map[string]any, bool, error) {
	m, ok := raw.(map[string]any)
	if !ok || m == nil {
		return nil, false, nil
	}
	props := make(map[string]any, len(m))
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		schema, err := normalizeSchemaValue(m[key])
		if err != nil {
			return nil, false, fmt.Errorf("field %s: %w", key, err)
		}
		props[key] = schema
	}
	return props, true, nil
}

func normalizeSchemaValue(raw any) (map[string]any, error) {
	switch v := raw.(type) {
	case string:
		return map[string]any{"type": strings.TrimSpace(v)}, nil
	case map[string]any:
		return normalizeSchemaMap(v)
	default:
		return nil, fmt.Errorf("unsupported schema node type %T", raw)
	}
}

func normalizeSchemaMap(in map[string]any) (map[string]any, error) {
	out := map[string]any{}
	typ := strings.TrimSpace(asString(in["type"]))
	switch typ {
	case "":
		props, ok, err := buildObjectProperties(in["properties"])
		if err != nil {
			return nil, err
		}
		if ok {
			out["type"] = "object"
			out["properties"] = props
			out["additionalProperties"] = false
			copySchemaConstraint(out, in, "required")
			return out, nil
		}
		return map[string]any{}, nil
	case "object":
		out["type"] = "object"
		props, ok, err := buildObjectProperties(in["properties"])
		if err != nil {
			return nil, err
		}
		if ok {
			out["properties"] = props
			if _, present := in["additionalProperties"]; present {
				copySchemaConstraint(out, in, "additionalProperties")
			} else {
				out["additionalProperties"] = false
			}
			copySchemaConstraint(out, in, "required")
		} else {
			if _, present := in["additionalProperties"]; present {
				copySchemaConstraint(out, in, "additionalProperties")
			} else {
				out["additionalProperties"] = true
			}
		}
		return out, nil
	case "array":
		out["type"] = "array"
		if items, ok := in["items"]; ok {
			itemSchema, err := normalizeSchemaValue(items)
			if err != nil {
				return nil, fmt.Errorf("items: %w", err)
			}
			out["items"] = itemSchema
		}
		copySchemaConstraint(out, in, "minItems", "maxItems")
		return out, nil
	default:
		out["type"] = typ
		copySchemaConstraint(out, in, "enum", "minimum", "maximum", "description", "default")
		return out, nil
	}
}

func copySchemaConstraint(dst, src map[string]any, keys ...string) {
	for _, key := range keys {
		if value, ok := src[key]; ok {
			dst[key] = value
		}
	}
}

func asString(v any) string {
	switch t := v.(type) {
	case string:
		return t
	default:
		return fmt.Sprint(v)
	}
}

func fail(err error) {
	fmt.Fprintf(os.Stderr, "generate_event_schema_registry: %v\n", err)
	os.Exit(1)
}
