package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	runtimecontracts "empireai/internal/runtime/contracts"
)

type generatedEventSchema struct {
	Description string         `json:"Description"`
	Schema      map[string]any `json:"Schema"`
}

func main() {
	repoRoot, err := findRepoRoot()
	if err != nil {
		fail(err)
	}
	bundle, err := runtimecontracts.LoadWorkflowContractBundle(repoRoot)
	if err != nil {
		fail(fmt.Errorf("load resolved workflow contract bundle: %w", err))
	}
	relativeContractsRoot := filepath.ToSlash(bundle.Paths.ContractsRoot)
	if rel, err := filepath.Rel(repoRoot, bundle.Paths.ContractsRoot); err == nil {
		relativeContractsRoot = filepath.ToSlash(rel)
	}
	outPath := filepath.Join(repoRoot, "internal", "runtime", "contracts", "schema_registry_generated.go")

	resolvedEvents := bundle.ResolvedEventCatalog()
	eventNames := make([]string, 0, len(resolvedEvents))
	generated := make(map[string]generatedEventSchema, len(resolvedEvents))
	for eventType, entry := range resolvedEvents {
		eventType = strings.TrimSpace(eventType)
		if eventType == "" {
			continue
		}
		schema, err := buildRootSchema(entry.Payload, entry.Required)
		if err != nil {
			fail(fmt.Errorf("%s: %w", eventType, err))
		}
		eventNames = append(eventNames, eventType)
		generated[eventType] = generatedEventSchema{
			Description: fmt.Sprintf("Generated from resolved MAS contract bundle rooted at %s for %s.", relativeContractsRoot, eventType),
			Schema:      schema,
		}
	}
	sort.Strings(eventNames)
	ordered := make(map[string]generatedEventSchema, len(eventNames))
	for _, eventType := range eventNames {
		ordered[eventType] = generated[eventType]
	}

	jsonBytes, err := json.MarshalIndent(ordered, "", "\t")
	if err != nil {
		fail(fmt.Errorf("marshal generated schemas: %w", err))
	}

	var buf bytes.Buffer
	buf.WriteString("package contracts\n\n")
	buf.WriteString("// Code generated by scripts/generate_event_schema_registry/main.go; DO NOT EDIT.\n")
	buf.WriteString(fmt.Sprintf("// Source: resolved MAS contract bundle rooted at %s\n\n", relativeContractsRoot))
	buf.WriteString("import (\n")
	buf.WriteString("\t\"encoding/json\"\n")
	buf.WriteString("\t\"fmt\"\n")
	buf.WriteString(")\n\n")
	buf.WriteString("//go:generate go run ../../../scripts/generate_event_schema_registry\n")
	buf.WriteString("var generatedContractEventSchemaRegistry = mustLoadGeneratedContractEventSchemaRegistry(`\n")
	buf.Write(jsonBytes)
	buf.WriteString("\n`)\n\n")
	buf.WriteString("func mustLoadGeneratedContractEventSchemaRegistry(raw string) map[string]EventSchema {\n")
	buf.WriteString("\tout := map[string]EventSchema{}\n")
	buf.WriteString("\tif err := json.Unmarshal([]byte(raw), &out); err != nil {\n")
	buf.WriteString("\t\tpanic(fmt.Sprintf(\"parse generated event schema registry: %v\", err))\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn out\n")
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fail(fmt.Errorf("gofmt generated output: %w", err))
	}
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		fail(fmt.Errorf("write %s: %w", outPath, err))
	}
}

func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not locate repo root from %s", dir)
		}
		dir = parent
	}
}

func buildRootSchema(payload runtimecontracts.EventPayloadSpec, required []string) (map[string]any, error) {
	props := buildEventObjectProperties(payload.Properties)
	rootType := strings.TrimSpace(payload.Type)
	if rootType == "" {
		rootType = "object"
	}
	out := map[string]any{
		"type":                 rootType,
		"properties":           props,
		"additionalProperties": false,
	}
	if len(required) > 0 {
		out["required"] = required
	}
	return out, nil
}

func buildEventObjectProperties(fields map[string]runtimecontracts.EventFieldSpec) map[string]any {
	if len(fields) == 0 {
		return map[string]any{}
	}
	props := make(map[string]any, len(fields))
	keys := make([]string, 0, len(fields))
	for key := range fields {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		props[key] = normalizeFieldSpec(fields[key])
	}
	return props
}

func normalizeFieldSpec(field runtimecontracts.EventFieldSpec) map[string]any {
	out := map[string]any{}
	if typ := strings.TrimSpace(field.Type); typ != "" {
		out["type"] = typ
	}
	if desc := strings.TrimSpace(field.Description); desc != "" {
		out["description"] = desc
	}
	return out
}

func fail(err error) {
	fmt.Fprintf(os.Stderr, "generate_event_schema_registry: %v\n", err)
	os.Exit(1)
}
