package runtimepersistence

import storebundlecatalog "github.com/division-sh/swarm/internal/store/internal/bundlecatalog"

type BundleCatalogAgentDefinition = storebundlecatalog.BundleCatalogAgentDefinition
type BundleCatalogAgentsResult = storebundlecatalog.BundleCatalogAgentsResult
type BundleCatalogConflictError = storebundlecatalog.BundleCatalogConflictError
type BundleCatalogDetail = storebundlecatalog.BundleCatalogDetail
type BundleCatalogListOptions = storebundlecatalog.BundleCatalogListOptions
type BundleCatalogListResult = storebundlecatalog.BundleCatalogListResult
type BundleCatalogSummary = storebundlecatalog.BundleCatalogSummary
type BundleCatalogUpsert = storebundlecatalog.BundleCatalogUpsert
type BundleCatalogUpsertResult = storebundlecatalog.BundleCatalogUpsertResult
