name: worker
mode: static
pins:
  inputs:
    events:
      - name: work_requested
        event: work.requested
        source: harness
  outputs:
    events:
      - name: work_completed
        event: work.completed
        sink: harness
