package contracts

// Code generated by scripts/generate_event_schema_registry/main.go; DO NOT EDIT.
// Source: contracts/event-catalog.yaml

import (
	"encoding/json"
	"fmt"
)

//go:generate go run ../../scripts/generate_event_schema_registry
var generatedContractEventSchemaRegistry = mustLoadGeneratedContractEventSchemaRegistry(`
{
	"analyst.anti_pattern_advisory": {
		"Description": "Generated from contracts/event-catalog.yaml for analyst.anti_pattern_advisory.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"affected_verticals": {
					"type": "array"
				},
				"pattern": {
					"type": "string"
				},
				"recommendation": {
					"type": "string"
				},
				"severity": {
					"type": "number"
				}
			},
			"type": "object"
		}
	},
	"analyst.bootstrap_upgrade_proposal": {
		"Description": "Generated from contracts/event-catalog.yaml for analyst.bootstrap_upgrade_proposal.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"affected_routes": {
					"type": "array"
				},
				"evidence": {
					"type": "object"
				},
				"proposal_type": {
					"type": "string"
				},
				"recommendation": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"analyst.prompt_refinement_proposal": {
		"Description": "Generated from contracts/event-catalog.yaml for analyst.prompt_refinement_proposal.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"agent_role": {
					"type": "string"
				},
				"current_behavior": {
					"type": "string"
				},
				"evidence": {
					"type": "object"
				},
				"proposed_change": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"board.chat": {
		"Description": "Generated from contracts/event-catalog.yaml for board.chat.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"context": {
					"type": "object"
				},
				"message": {
					"type": "string"
				},
				"response_requested": {
					"type": "boolean"
				}
			},
			"type": "object"
		}
	},
	"board.directive": {
		"Description": "Generated from contracts/event-catalog.yaml for board.directive.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"directive_type": {
					"type": "string"
				},
				"parameters": {
					"type": "object"
				},
				"priority": {
					"type": "string"
				},
				"target": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"brand.candidates_ready": {
		"Description": "Generated from contracts/event-catalog.yaml for brand.candidates_ready.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"candidates": {
					"type": "array"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"brand.requested": {
		"Description": "Generated from contracts/event-catalog.yaml for brand.requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"business_brief": {
					"type": "object"
				},
				"geography": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				},
				"vertical_name": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"brand.revision_needed": {
		"Description": "Generated from contracts/event-catalog.yaml for brand.revision_needed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"feedback": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"budget.emergency": {
		"Description": "Generated from contracts/event-catalog.yaml for budget.emergency.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"action_taken": {
					"type": "string"
				},
				"level": {
					"type": "string"
				},
				"message": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"budget.resumed": {
		"Description": "Generated from contracts/event-catalog.yaml for budget.resumed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"message": {
					"type": "string"
				},
				"previous_level": {
					"type": "number"
				}
			},
			"type": "object"
		}
	},
	"budget.threshold_crossed": {
		"Description": "Generated from contracts/event-catalog.yaml for budget.threshold_crossed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"budget_cap": {
					"type": "number"
				},
				"current_spend": {
					"type": "number"
				},
				"level": {
					"type": "string"
				},
				"percentage": {
					"type": "number"
				}
			},
			"type": "object"
		}
	},
	"budget.throttle": {
		"Description": "Generated from contracts/event-catalog.yaml for budget.throttle.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"affected_agents": {
					"type": "array"
				},
				"throttle_level": {
					"type": "number"
				}
			},
			"type": "object"
		}
	},
	"budget.warning": {
		"Description": "Generated from contracts/event-catalog.yaml for budget.warning.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"level": {
					"type": "string"
				},
				"message": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"bug_fix_deployed": {
		"Description": "Generated from contracts/event-catalog.yaml for bug_fix_deployed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"bug_id": {
					"type": "string"
				},
				"resolution": {
					"type": "string"
				},
				"version": {
					"type": "number"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"bug_reported": {
		"Description": "Generated from contracts/event-catalog.yaml for bug_reported.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"description": {
					"type": "string"
				},
				"reproduction_steps": {
					"type": "string"
				},
				"severity": {
					"type": "number"
				}
			},
			"type": "object"
		}
	},
	"build_blocked": {
		"Description": "Generated from contracts/event-catalog.yaml for build_blocked.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"blocked_task": {
					"type": "string"
				},
				"blocker": {
					"type": "string"
				},
				"severity": {
					"type": "number"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"build_complete": {
		"Description": "Generated from contracts/event-catalog.yaml for build_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"environment": {
					"type": "string"
				},
				"feature": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"build_progress": {
		"Description": "Generated from contracts/event-catalog.yaml for build_progress.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"completion_pct": {
					"type": "string"
				},
				"milestone": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"campaign.completed": {
		"Description": "Generated from contracts/event-catalog.yaml for campaign.completed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"campaign_id": {
					"type": "string"
				},
				"geography": {
					"type": "string"
				},
				"modes_completed": {
					"type": "string"
				},
				"verticals_discovered": {
					"type": "integer"
				},
				"verticals_shortlisted": {
					"type": "integer"
				},
				"verticals_skipped": {
					"type": "integer"
				}
			},
			"type": "object"
		}
	},
	"category.assessed": {
		"Description": "Generated from contracts/event-catalog.yaml for category.assessed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"build_sketch": {
					"additionalProperties": false,
					"properties": {
						"core_features": {
							"items": {
								"type": "string"
							},
							"type": "array"
						},
						"key_integrations": {
							"items": {
								"type": "string"
							},
							"type": "array"
						},
						"red_flags": {
							"items": {
								"additionalProperties": false,
								"properties": {
									"notes": {
										"type": "string"
									},
									"source_url": {
										"type": "string"
									},
									"type": {
										"type": "string"
									}
								},
								"type": "object"
							},
							"type": "array"
						}
					},
					"type": "object"
				},
				"category": {
					"type": "string"
				},
				"evidence": {
					"additionalProperties": false,
					"properties": {
						"buyer_communities": {
							"items": {
								"additionalProperties": false,
								"properties": {
									"name": {
										"type": "string"
									},
									"source_url": {
										"type": "string"
									}
								},
								"type": "object"
							},
							"type": "array"
						},
						"competitors": {
							"items": {
								"additionalProperties": false,
								"properties": {
									"name": {
										"type": "string"
									},
									"pricing": {
										"type": "string"
									},
									"source_url": {
										"type": "string"
									}
								},
								"type": "object"
							},
							"type": "array"
						},
						"pain_signals": {
							"items": {
								"additionalProperties": false,
								"properties": {
									"signal": {
										"type": "string"
									},
									"source_url": {
										"type": "string"
									}
								},
								"type": "object"
							},
							"type": "array"
						},
						"regulatory": {
							"items": {
								"additionalProperties": false,
								"properties": {
									"detail": {
										"type": "string"
									},
									"source_url": {
										"type": "string"
									}
								},
								"type": "object"
							},
							"type": "array"
						}
					},
					"type": "object"
				},
				"geographic_scope": {
					"type": "string"
				},
				"geography": {
					"type": "string"
				},
				"opportunity_hypothesis": {
					"type": "string"
				},
				"opportunity_name": {
					"type": "string"
				},
				"opportunity_pattern": {
					"type": "string"
				},
				"preliminary_icp": {
					"type": "string"
				},
				"required_capabilities": {
					"additionalProperties": false,
					"properties": {
						"automation_with_unlock": {
							"type": "number"
						},
						"current": {
							"items": {
								"type": "string"
							},
							"type": "array"
						},
						"would_unlock": {
							"type": "string"
						}
					},
					"type": "object"
				},
				"scan_id": {
					"type": "string"
				},
				"signal_sources": {
					"items": {
						"additionalProperties": false,
						"properties": {
							"signal_type": {
								"type": "string"
							},
							"source": {
								"type": "string"
							},
							"url": {
								"type": "string"
							}
						},
						"type": "object"
					},
					"type": "array"
				},
				"signal_strength": {
					"type": "integer"
				},
				"subcategory": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"channel_blocked": {
		"Description": "Generated from contracts/event-catalog.yaml for channel_blocked.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"channel": {
					"type": "string"
				},
				"reason": {
					"type": "string"
				},
				"severity": {
					"type": "number"
				}
			},
			"type": "object"
		}
	},
	"channel_update": {
		"Description": "Generated from contracts/event-catalog.yaml for channel_update.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"channel": {
					"type": "string"
				},
				"metrics": {
					"type": "object"
				},
				"status": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"churn_risk": {
		"Description": "Generated from contracts/event-catalog.yaml for churn_risk.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"customer_id": {
					"type": "string"
				},
				"indicators": {
					"type": "string"
				},
				"risk_level": {
					"type": "number"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"cross_domain_report": {
		"Description": "Generated from contracts/event-catalog.yaml for cross_domain_report.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"growth_status": {
					"type": "string"
				},
				"product_status": {
					"type": "string"
				},
				"recommendations": {
					"type": "string"
				},
				"risks": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"cto.architecture_directive": {
		"Description": "Generated from contracts/event-catalog.yaml for cto.architecture_directive.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"affected_verticals": {
					"type": "array"
				},
				"directive": {
					"type": "string"
				},
				"rationale": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"cto.extraction_recommended": {
		"Description": "Generated from contracts/event-catalog.yaml for cto.extraction_recommended.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"affected_verticals": {
					"type": "array"
				},
				"pattern_id": {
					"type": "string"
				},
				"recommendation": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"cto.pattern_detected": {
		"Description": "Generated from contracts/event-catalog.yaml for cto.pattern_detected.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"description": {
					"type": "string"
				},
				"pattern_type": {
					"type": "string"
				},
				"verticals": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"cto.spec_approved": {
		"Description": "Generated from contracts/event-catalog.yaml for cto.spec_approved.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"cto_notes": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"cto.spec_review_requested": {
		"Description": "Generated from contracts/event-catalog.yaml for cto.spec_review_requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"business_brief": {
					"type": "object"
				},
				"mvp_spec": {
					"type": "string"
				},
				"vertical_context": {
					"type": "object"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"cto.spec_revision_needed": {
		"Description": "Generated from contracts/event-catalog.yaml for cto.spec_revision_needed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"technical_issues": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"cto.spec_vetoed": {
		"Description": "Generated from contracts/event-catalog.yaml for cto.spec_vetoed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"reason": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"cto.tech_spec_feedback": {
		"Description": "Generated from contracts/event-catalog.yaml for cto.tech_spec_feedback.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"feedback": {
					"type": "string"
				},
				"severity": {
					"type": "number"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"cto.tech_spec_review_requested": {
		"Description": "Generated from contracts/event-catalog.yaml for cto.tech_spec_review_requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"spec_content": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"cycle_limit_reached": {
		"Description": "Generated from contracts/event-catalog.yaml for cycle_limit_reached.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"agents_involved": {
					"items": {
						"type": "string"
					},
					"type": "array"
				},
				"count": {
					"type": "integer"
				},
				"event_pattern": {
					"type": "string"
				},
				"recommendation": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				},
				"window_hours": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"cycle_reset": {
		"Description": "Generated from contracts/event-catalog.yaml for cycle_reset.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"event_pattern": {
					"type": "string"
				},
				"reason": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"dedup.ambiguous": {
		"Description": "Generated from contracts/event-catalog.yaml for dedup.ambiguous.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"dedup_id": {
					"type": "string"
				},
				"existing_vertical": {
					"type": "string"
				},
				"new_candidate": {
					"type": "string"
				},
				"similarity": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"dedup.resolved": {
		"Description": "Generated from contracts/event-catalog.yaml for dedup.resolved.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"action": {
					"type": "string"
				},
				"dedup_id": {
					"type": "string"
				},
				"reasoning": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"deploy_requested": {
		"Description": "Generated from contracts/event-catalog.yaml for deploy_requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"component": {
					"type": "string"
				},
				"deploy_config": {
					"type": "string"
				},
				"version": {
					"type": "number"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"devops.capacity_warning": {
		"Description": "Generated from contracts/event-catalog.yaml for devops.capacity_warning.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"current_usage": {
					"type": "string"
				},
				"recommendation": {
					"type": "string"
				},
				"resource": {
					"type": "string"
				},
				"threshold": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"devops.deploy_complete": {
		"Description": "Generated from contracts/event-catalog.yaml for devops.deploy_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"environment": {
					"type": "string"
				},
				"url": {
					"type": "string"
				},
				"version": {
					"type": "number"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"devops.deploy_failed": {
		"Description": "Generated from contracts/event-catalog.yaml for devops.deploy_failed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"environment": {
					"type": "string"
				},
				"error": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"devops.deploy_requested": {
		"Description": "Generated from contracts/event-catalog.yaml for devops.deploy_requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"environment": {
					"type": "string"
				},
				"manifest": {
					"additionalProperties": true,
					"type": "object"
				},
				"requesting_agent": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"devops.health_check_failed": {
		"Description": "Generated from contracts/event-catalog.yaml for devops.health_check_failed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"endpoint": {
					"type": "string"
				},
				"error": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"devops.infra_change_needed": {
		"Description": "Generated from contracts/event-catalog.yaml for devops.infra_change_needed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"change_type": {
					"type": "string"
				},
				"estimated_cost": {
					"type": "number"
				},
				"reason": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"devops.rollback_complete": {
		"Description": "Generated from contracts/event-catalog.yaml for devops.rollback_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"active_version": {
					"type": "integer"
				},
				"environment": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"devops.rollback_failed": {
		"Description": "Generated from contracts/event-catalog.yaml for devops.rollback_failed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"environment": {
					"type": "string"
				},
				"error": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"devops.rollback_requested": {
		"Description": "Generated from contracts/event-catalog.yaml for devops.rollback_requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"requesting_agent": {
					"type": "string"
				},
				"target_version": {
					"type": "integer"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"devops.ssl_provisioned": {
		"Description": "Generated from contracts/event-catalog.yaml for devops.ssl_provisioned.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"domain": {
					"type": "string"
				},
				"expiry": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"feature_deployed": {
		"Description": "Generated from contracts/event-catalog.yaml for feature_deployed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"feature_id": {
					"type": "string"
				},
				"release_notes": {
					"type": "string"
				},
				"version": {
					"type": "number"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"feature_request": {
		"Description": "Generated from contracts/event-catalog.yaml for feature_request.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"description": {
					"type": "string"
				},
				"requester_context": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"founder_input.response": {
		"Description": "Generated from contracts/event-catalog.yaml for founder_input.response.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"decision": {
					"type": "string"
				},
				"item_id": {
					"type": "string"
				},
				"notes": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"growth_escalation": {
		"Description": "Generated from contracts/event-catalog.yaml for growth_escalation.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"issue": {
					"type": "string"
				},
				"recommendation": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"growth_report": {
		"Description": "Generated from contracts/event-catalog.yaml for growth_report.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"decisions": {
					"type": "string"
				},
				"metrics": {
					"type": "object"
				},
				"phase": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"human_task.approved": {
		"Description": "Generated from contracts/event-catalog.yaml for human_task.approved.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"notes": {
					"type": "string"
				},
				"task_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"human_task.assigned": {
		"Description": "Generated from contracts/event-catalog.yaml for human_task.assigned.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"assigned_to": {
					"type": "string"
				},
				"requesting_agent": {
					"type": "string"
				},
				"task_id": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"human_task.completed": {
		"Description": "Generated from contracts/event-catalog.yaml for human_task.completed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"result": {
					"type": "object"
				},
				"task_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"human_task.deferred": {
		"Description": "Generated from contracts/event-catalog.yaml for human_task.deferred.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"defer_until": {
					"type": "string"
				},
				"reason": {
					"type": "string"
				},
				"task_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"human_task.expired": {
		"Description": "Generated from contracts/event-catalog.yaml for human_task.expired.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"task_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"human_task.rejected": {
		"Description": "Generated from contracts/event-catalog.yaml for human_task.rejected.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"reason": {
					"type": "string"
				},
				"task_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"human_task.requested": {
		"Description": "Generated from contracts/event-catalog.yaml for human_task.requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"description": {
					"type": "string"
				},
				"requesting_agent": {
					"type": "string"
				},
				"task_id": {
					"type": "string"
				},
				"task_type": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"inbound.email": {
		"Description": "Generated from contracts/event-catalog.yaml for inbound.email.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"attachments": {
					"items": {
						"type": "string"
					},
					"type": "array"
				},
				"body": {
					"type": "string"
				},
				"from": {
					"type": "string"
				},
				"subject": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"inbound.whatsapp_message": {
		"Description": "Generated from contracts/event-catalog.yaml for inbound.whatsapp_message.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"from": {
					"type": "string"
				},
				"media_urls": {
					"items": {
						"type": "string"
					},
					"type": "array"
				},
				"message": {
					"type": "string"
				},
				"timestamp": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"launch_ready": {
		"Description": "Generated from contracts/event-catalog.yaml for launch_ready.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"deploy_url": {
					"type": "string"
				},
				"test_results": {
					"type": "object"
				},
				"version": {
					"type": "number"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"mailbox.item_decided": {
		"Description": "Generated from contracts/event-catalog.yaml for mailbox.item_decided.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"decided_by": {
					"type": "string"
				},
				"decision": {
					"type": "string"
				},
				"item_id": {
					"type": "string"
				},
				"original_event_type": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"mandate_updated": {
		"Description": "Generated from contracts/event-catalog.yaml for mandate_updated.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"budget_allocation": {
					"type": "object"
				},
				"mandate": {
					"type": "object"
				},
				"priorities": {
					"type": "array"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"market_feedback": {
		"Description": "Generated from contracts/event-catalog.yaml for market_feedback.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"feedback_type": {
					"type": "string"
				},
				"frequency": {
					"type": "number"
				},
				"severity": {
					"type": "number"
				},
				"summary": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"market_research.scan_assigned": {
		"Description": "Generated from contracts/event-catalog.yaml for market_research.scan_assigned.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"corpus_signals": {
					"items": {
						"additionalProperties": true,
						"type": "object"
					},
					"type": "array"
				},
				"geography": {
					"type": "string"
				},
				"mode": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"shard": {
					"additionalProperties": true,
					"type": "object"
				},
				"taxonomy_categories": {
					"items": {
						"type": "string"
					},
					"type": "array"
				}
			},
			"type": "object"
		}
	},
	"market_research.scan_complete": {
		"Description": "Generated from contracts/event-catalog.yaml for market_research.scan_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"categories_assessed": {
					"type": "integer"
				},
				"geography": {
					"type": "string"
				},
				"high_signal_count": {
					"type": "integer"
				},
				"scan_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"market_signals": {
		"Description": "Generated from contracts/event-catalog.yaml for market_signals.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"description": {
					"type": "string"
				},
				"evidence": {
					"type": "object"
				},
				"signal_type": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.ceo_ready": {
		"Description": "Generated from contracts/event-catalog.yaml for opco.ceo_ready.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"agent_count": {
					"type": "number"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.ceo_report": {
		"Description": "Generated from contracts/event-catalog.yaml for opco.ceo_report.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"decisions": {
					"type": "string"
				},
				"metrics": {
					"type": "object"
				},
				"phase": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.deploy_review": {
		"Description": "Generated from contracts/event-catalog.yaml for opco.deploy_review.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"deploy_id": {
					"type": "string"
				},
				"review_type": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.escalation": {
		"Description": "Generated from contracts/event-catalog.yaml for opco.escalation.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"issue": {
					"type": "string"
				},
				"recommendation": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.escalation_response": {
		"Description": "Generated from contracts/event-catalog.yaml for opco.escalation_response.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"directive": {
					"type": "string"
				},
				"original_escalation_id": {
					"type": "string"
				},
				"priority": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.founder_input": {
		"Description": "Generated from contracts/event-catalog.yaml for opco.founder_input.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"context": {
					"type": "object"
				},
				"question": {
					"type": "string"
				},
				"urgency": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.launched": {
		"Description": "Generated from contracts/event-catalog.yaml for opco.launched.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"launch_url": {
					"type": "string"
				},
				"metrics": {
					"type": "object"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.product_spec_review": {
		"Description": "Generated from contracts/event-catalog.yaml for opco.product_spec_review.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"review_request": {
					"type": "string"
				},
				"spec_summary": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.routing_updated": {
		"Description": "Generated from contracts/event-catalog.yaml for opco.routing_updated.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"bootstrap_version": {
					"type": "integer"
				},
				"event_pattern": {
					"type": "string"
				},
				"installed_by": {
					"type": "string"
				},
				"reason": {
					"type": "string"
				},
				"runtime_tool_event": {
					"type": "boolean"
				},
				"source": {
					"type": "string"
				},
				"status": {
					"type": "string"
				},
				"subscriber_id": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.spend_request": {
		"Description": "Generated from contracts/event-catalog.yaml for opco.spend_request.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"amount": {
					"type": "string"
				},
				"purpose": {
					"type": "string"
				},
				"vendor": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.spinup_requested": {
		"Description": "Generated from contracts/event-catalog.yaml for opco.spinup_requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"brand": {
					"additionalProperties": true,
					"type": "object"
				},
				"founder_directives": {
					"type": "string"
				},
				"mandate": {
					"additionalProperties": true,
					"type": "object"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.steady_state_reached": {
		"Description": "Generated from contracts/event-catalog.yaml for opco.steady_state_reached.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.teardown_complete": {
		"Description": "Generated from contracts/event-catalog.yaml for opco.teardown_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.teardown_requested": {
		"Description": "Generated from contracts/event-catalog.yaml for opco.teardown_requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"reason": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"ops.agent_failed": {
		"Description": "Generated from contracts/event-catalog.yaml for ops.agent_failed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"agent_id": {
					"type": "string"
				},
				"error": {
					"type": "string"
				},
				"last_event_type": {
					"type": "string"
				},
				"retry_count": {
					"type": "number"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"ops.agent_panic": {
		"Description": "Generated from contracts/event-catalog.yaml for ops.agent_panic.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"agent_id": {
					"type": "string"
				},
				"conversation_id": {
					"type": "string"
				},
				"error": {
					"type": "string"
				},
				"stack_trace": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"outreach_digest": {
		"Description": "Generated from contracts/event-catalog.yaml for outreach_digest.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"best_channel": {
					"type": "string"
				},
				"intelligence": {
					"type": "string"
				},
				"leads_converted": {
					"type": "string"
				},
				"messages_sent": {
					"type": "string"
				},
				"response_rate": {
					"type": "string"
				},
				"responses": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"pipeline.dead_letter": {
		"Description": "Generated from contracts/event-catalog.yaml for pipeline.dead_letter.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"event_id": {
					"type": "string"
				},
				"event_type": {
					"type": "string"
				},
				"last_error": {
					"type": "string"
				},
				"node_id": {
					"type": "string"
				},
				"retry_count": {
					"type": "integer"
				}
			},
			"type": "object"
		}
	},
	"portfolio.digest_compiled": {
		"Description": "Generated from contracts/event-catalog.yaml for portfolio.digest_compiled.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"action_required_count": {
					"type": "integer"
				},
				"digest_text": {
					"type": "string"
				},
				"trigger_reason": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"prelaunch_ready": {
		"Description": "Generated from contracts/event-catalog.yaml for prelaunch_ready.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"channels_ready": {
					"type": "string"
				},
				"landing_page_url": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"product_escalation": {
		"Description": "Generated from contracts/event-catalog.yaml for product_escalation.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"issue": {
					"type": "string"
				},
				"recommendation": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"product_report": {
		"Description": "Generated from contracts/event-catalog.yaml for product_report.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"decisions": {
					"type": "string"
				},
				"metrics": {
					"type": "object"
				},
				"phase": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"product_spec_ready": {
		"Description": "Generated from contracts/event-catalog.yaml for product_spec_ready.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"acceptance_criteria": {
					"type": "string"
				},
				"features": {
					"type": "string"
				},
				"spec_version": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"qa.validation_failed": {
		"Description": "Generated from contracts/event-catalog.yaml for qa.validation_failed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"expected_vs_actual": {
					"type": "string"
				},
				"failures": {
					"type": "string"
				},
				"reproduction_steps": {
					"type": "string"
				},
				"severity": {
					"type": "number"
				}
			},
			"type": "object"
		}
	},
	"qa.validation_passed": {
		"Description": "Generated from contracts/event-catalog.yaml for qa.validation_passed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"coverage_notes": {
					"type": "string"
				},
				"staging_url": {
					"type": "string"
				},
				"test_summary": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"research.completed": {
		"Description": "Generated from contracts/event-catalog.yaml for research.completed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"business_brief": {
					"type": "object"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"research.vertical_rejected": {
		"Description": "Generated from contracts/event-catalog.yaml for research.vertical_rejected.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"evidence": {
					"type": "object"
				},
				"rejection_reason": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"review.deploy_feedback": {
		"Description": "Generated from contracts/event-catalog.yaml for review.deploy_feedback.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"feedback": {
					"type": "string"
				},
				"reviewer": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"review.product_spec_feedback": {
		"Description": "Generated from contracts/event-catalog.yaml for review.product_spec_feedback.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"feedback": {
					"type": "string"
				},
				"reviewer": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"runtime.reset": {
		"Description": "Generated from contracts/event-catalog.yaml for runtime.reset.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"source": {
					"type": "string"
				},
				"timestamp": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scan.completed": {
		"Description": "Generated from contracts/event-catalog.yaml for scan.completed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"agents_complete": {
					"type": "integer"
				},
				"agents_expected": {
					"type": "integer"
				},
				"campaign_id": {
					"type": "string"
				},
				"geography": {
					"type": "string"
				},
				"mode": {
					"type": "string"
				},
				"reports_received": {
					"type": "integer"
				},
				"verticals_discovered": {
					"type": "integer"
				},
				"verticals_skipped": {
					"type": "integer"
				}
			},
			"type": "object"
		}
	},
	"scan.requested": {
		"Description": "Generated from contracts/event-catalog.yaml for scan.requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"campaign_context": {
					"additionalProperties": false,
					"properties": {
						"directive_id": {
							"type": "string"
						},
						"modes": {
							"items": {
								"type": "string"
							},
							"type": "array"
						},
						"strategic_context": {
							"type": "string"
						}
					},
					"type": "object"
				},
				"campaign_id": {
					"type": "string"
				},
				"corpus_path": {
					"type": "string"
				},
				"depth": {
					"type": "string"
				},
				"geography": {
					"type": "string"
				},
				"mode": {
					"type": "string"
				},
				"sources": {
					"items": {
						"type": "string"
					},
					"type": "array"
				},
				"taxonomy_categories": {
					"items": {
						"type": "string"
					},
					"type": "array"
				}
			},
			"type": "object"
		}
	},
	"scanner.directories.scan_assigned": {
		"Description": "Generated from contracts/event-catalog.yaml for scanner.directories.scan_assigned.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"geography": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"source_config": {
					"type": "string"
				},
				"subcategory": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scanner.directories.scan_complete": {
		"Description": "Generated from contracts/event-catalog.yaml for scanner.directories.scan_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"errors": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"sources_found": {
					"type": "string"
				},
				"sources_scraped": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scanner.google_maps.scan_assigned": {
		"Description": "Generated from contracts/event-catalog.yaml for scanner.google_maps.scan_assigned.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"geography": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"source_config": {
					"type": "string"
				},
				"subcategory": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scanner.google_maps.scan_complete": {
		"Description": "Generated from contracts/event-catalog.yaml for scanner.google_maps.scan_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"errors": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"sources_found": {
					"type": "string"
				},
				"sources_scraped": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scanner.instagram.scan_assigned": {
		"Description": "Generated from contracts/event-catalog.yaml for scanner.instagram.scan_assigned.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"geography": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"source_config": {
					"type": "string"
				},
				"subcategory": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scanner.instagram.scan_complete": {
		"Description": "Generated from contracts/event-catalog.yaml for scanner.instagram.scan_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"errors": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"sources_found": {
					"type": "string"
				},
				"sources_scraped": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scanner.reviews.scan_assigned": {
		"Description": "Generated from contracts/event-catalog.yaml for scanner.reviews.scan_assigned.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"geography": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"source_config": {
					"type": "string"
				},
				"subcategory": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scanner.reviews.scan_complete": {
		"Description": "Generated from contracts/event-catalog.yaml for scanner.reviews.scan_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"errors": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"sources_found": {
					"type": "string"
				},
				"sources_scraped": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scanner.yelp.scan_assigned": {
		"Description": "Generated from contracts/event-catalog.yaml for scanner.yelp.scan_assigned.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"geography": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"source_config": {
					"type": "string"
				},
				"subcategory": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scanner.yelp.scan_complete": {
		"Description": "Generated from contracts/event-catalog.yaml for scanner.yelp.scan_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"errors": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"sources_found": {
					"type": "string"
				},
				"sources_scraped": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"score.dimension_complete": {
		"Description": "Generated from contracts/event-catalog.yaml for score.dimension_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"confidence": {
					"type": "string"
				},
				"dimension": {
					"type": "string"
				},
				"evidence": {
					"type": "string"
				},
				"score": {
					"type": "integer"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scoring.contest_resolved": {
		"Description": "Generated from contracts/event-catalog.yaml for scoring.contest_resolved.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"dimension": {
					"type": "string"
				},
				"reasoning": {
					"type": "string"
				},
				"resolved_score": {
					"type": "integer"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scoring.contested": {
		"Description": "Generated from contracts/event-catalog.yaml for scoring.contested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"dimension": {
					"type": "string"
				},
				"evidence": {
					"items": {
						"type": "string"
					},
					"type": "array"
				},
				"scores": {
					"items": {
						"type": "integer"
					},
					"type": "array"
				},
				"spread": {
					"type": "integer"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scoring.requested": {
		"Description": "Generated from contracts/event-catalog.yaml for scoring.requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"assigned_analysis_agent_id": {
					"type": "string"
				},
				"dimensions_requested": {
					"items": {
						"type": "string"
					},
					"type": "array"
				},
				"discovery_context": {
					"additionalProperties": true,
					"type": "object"
				},
				"excluded_analysis_agent_id": {
					"type": "string"
				},
				"geography": {
					"type": "string"
				},
				"mode": {
					"type": "string"
				},
				"rubric": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				},
				"vertical_name": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"source.scraped": {
		"Description": "Generated from contracts/event-catalog.yaml for source.scraped.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"evidence": {
					"type": "string"
				},
				"geography": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"source": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spec.approved": {
		"Description": "Generated from contracts/event-catalog.yaml for spec.approved.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"final_spec": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spec.contradiction_detected": {
		"Description": "Generated from contracts/event-catalog.yaml for spec.contradiction_detected.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"agent_id": {
					"type": "string"
				},
				"contradiction_type": {
					"type": "string"
				},
				"detail": {
					"type": "object"
				}
			},
			"type": "object"
		}
	},
	"spec.draft_ready": {
		"Description": "Generated from contracts/event-catalog.yaml for spec.draft_ready.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"mvp_spec": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spec.requested": {
		"Description": "Generated from contracts/event-catalog.yaml for spec.requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"business_brief": {
					"type": "object"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spec.revision_needed": {
		"Description": "Generated from contracts/event-catalog.yaml for spec.revision_needed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"misalignment_details": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spec.revision_requested": {
		"Description": "Generated from contracts/event-catalog.yaml for spec.revision_requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"cto_feedback": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spec.validation_failed": {
		"Description": "Generated from contracts/event-catalog.yaml for spec.validation_failed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"issues": {
					"items": {
						"additionalProperties": true,
						"type": "object"
					},
					"type": "array"
				},
				"severity": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spec.validation_passed": {
		"Description": "Generated from contracts/event-catalog.yaml for spec.validation_passed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"validation_notes": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spec.validation_requested": {
		"Description": "Generated from contracts/event-catalog.yaml for spec.validation_requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"spec_content": {
					"type": "string"
				},
				"spec_tier": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spec_review.issues_found": {
		"Description": "Generated from contracts/event-catalog.yaml for spec_review.issues_found.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"issues": {
					"type": "array"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spec_review.passed": {
		"Description": "Generated from contracts/event-catalog.yaml for spec_review.passed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"review_notes": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spec_review.requested": {
		"Description": "Generated from contracts/event-catalog.yaml for spec_review.requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"business_brief": {
					"type": "object"
				},
				"mvp_spec": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spend.approved": {
		"Description": "Generated from contracts/event-catalog.yaml for spend.approved.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"amount": {
					"type": "string"
				},
				"purpose": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spend.rejected": {
		"Description": "Generated from contracts/event-catalog.yaml for spend.rejected.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"reason": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spend_needed": {
		"Description": "Generated from contracts/event-catalog.yaml for spend_needed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"amount": {
					"type": "string"
				},
				"purpose": {
					"type": "string"
				},
				"vendor": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spend_request": {
		"Description": "Generated from contracts/event-catalog.yaml for spend_request.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"amount": {
					"type": "string"
				},
				"currency": {
					"type": "string"
				},
				"justification": {
					"type": "string"
				},
				"purpose": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"support_critical": {
		"Description": "Generated from contracts/event-catalog.yaml for support_critical.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"customer_impact": {
					"type": "string"
				},
				"description": {
					"type": "string"
				},
				"severity": {
					"type": "number"
				}
			},
			"type": "object"
		}
	},
	"support_digest": {
		"Description": "Generated from contracts/event-catalog.yaml for support_digest.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"churn_risk_signals": {
					"type": "string"
				},
				"common_issues": {
					"type": "string"
				},
				"csat": {
					"type": "string"
				},
				"open_tickets": {
					"type": "string"
				},
				"resolved": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"synthesis.needed": {
		"Description": "Generated from contracts/event-catalog.yaml for synthesis.needed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"conflicting_reports": {
					"type": "string"
				},
				"context": {
					"type": "object"
				}
			},
			"type": "object"
		}
	},
	"synthesis.resolved": {
		"Description": "Generated from contracts/event-catalog.yaml for synthesis.resolved.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"resolved_assessment": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"system.directive": {
		"Description": "Generated from contracts/event-catalog.yaml for system.directive.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"directive_text": {
					"type": "string"
				},
				"timestamp": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"system.started": {
		"Description": "Generated from contracts/event-catalog.yaml for system.started.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"agent_count": {
					"type": "number"
				},
				"config_version": {
					"type": "string"
				},
				"is_cold_start": {
					"type": "boolean"
				},
				"timestamp": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"technical_spec_ready": {
		"Description": "Generated from contracts/event-catalog.yaml for technical_spec_ready.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"api_contracts": {
					"type": "string"
				},
				"components": {
					"type": "string"
				},
				"spec_version": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"template.migration_approved": {
		"Description": "Generated from contracts/event-catalog.yaml for template.migration_approved.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"template_version": {
					"type": "string"
				},
				"verticals": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"template.migration_completed": {
		"Description": "Generated from contracts/event-catalog.yaml for template.migration_completed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"result": {
					"type": "object"
				},
				"template_version": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"template.migration_failed": {
		"Description": "Generated from contracts/event-catalog.yaml for template.migration_failed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"error": {
					"type": "string"
				},
				"template_version": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"template.migration_planned": {
		"Description": "Generated from contracts/event-catalog.yaml for template.migration_planned.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"affected_verticals": {
					"items": {
						"type": "string"
					},
					"type": "array"
				},
				"migration_plan": {
					"additionalProperties": true,
					"type": "object"
				},
				"template_version": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"template.publish_requested": {
		"Description": "Generated from contracts/event-catalog.yaml for template.publish_requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"changes": {
					"type": "string"
				},
				"template_version": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"template.version_published": {
		"Description": "Generated from contracts/event-catalog.yaml for template.version_published.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"changelog": {
					"type": "string"
				},
				"template_version": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"timer.infra_health_check": {
		"Description": "Generated from contracts/event-catalog.yaml for timer.infra_health_check.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"check_type": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"timer.marginal_review": {
		"Description": "Generated from contracts/event-catalog.yaml for timer.marginal_review.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"parked_marginals_summary": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"timer.portfolio_digest": {
		"Description": "Generated from contracts/event-catalog.yaml for timer.portfolio_digest.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"trigger_reason": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"trend.identified": {
		"Description": "Generated from contracts/event-catalog.yaml for trend.identified.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"build_sketch": {
					"additionalProperties": false,
					"properties": {
						"core_features": {
							"items": {
								"type": "string"
							},
							"type": "array"
						},
						"key_integrations": {
							"items": {
								"type": "string"
							},
							"type": "array"
						},
						"red_flags": {
							"items": {
								"additionalProperties": false,
								"properties": {
									"notes": {
										"type": "string"
									},
									"source_url": {
										"type": "string"
									},
									"type": {
										"type": "string"
									}
								},
								"type": "object"
							},
							"type": "array"
						}
					},
					"type": "object"
				},
				"evidence": {
					"additionalProperties": false,
					"properties": {
						"buyer_communities": {
							"items": {
								"additionalProperties": false,
								"properties": {
									"name": {
										"type": "string"
									},
									"source_url": {
										"type": "string"
									}
								},
								"type": "object"
							},
							"type": "array"
						},
						"competitors": {
							"items": {
								"additionalProperties": false,
								"properties": {
									"name": {
										"type": "string"
									},
									"pricing": {
										"type": "string"
									},
									"source_url": {
										"type": "string"
									}
								},
								"type": "object"
							},
							"type": "array"
						},
						"pain_signals": {
							"items": {
								"additionalProperties": false,
								"properties": {
									"signal": {
										"type": "string"
									},
									"source_url": {
										"type": "string"
									}
								},
								"type": "object"
							},
							"type": "array"
						},
						"regulatory": {
							"items": {
								"additionalProperties": false,
								"properties": {
									"detail": {
										"type": "string"
									},
									"source_url": {
										"type": "string"
									}
								},
								"type": "object"
							},
							"type": "array"
						}
					},
					"type": "object"
				},
				"geographic_scope": {
					"type": "string"
				},
				"geography": {
					"type": "string"
				},
				"opportunity_hypothesis": {
					"type": "string"
				},
				"opportunity_name": {
					"type": "string"
				},
				"preliminary_icp": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"signal_strength": {
					"type": "integer"
				},
				"trend_category": {
					"type": "string"
				},
				"trend_description": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"trend_research.scan_assigned": {
		"Description": "Generated from contracts/event-catalog.yaml for trend_research.scan_assigned.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"geography": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"trend_research.scan_complete": {
		"Description": "Generated from contracts/event-catalog.yaml for trend_research.scan_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"geography": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"trends_identified": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"user_onboarded": {
		"Description": "Generated from contracts/event-catalog.yaml for user_onboarded.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"channel": {
					"type": "string"
				},
				"user_id": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"validation.more_data_needed": {
		"Description": "Generated from contracts/event-catalog.yaml for validation.more_data_needed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"questions": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"validation.package_ready": {
		"Description": "Generated from contracts/event-catalog.yaml for validation.package_ready.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"brand": {
					"type": "string"
				},
				"cto_notes": {
					"type": "string"
				},
				"research": {
					"type": "string"
				},
				"spec": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"validation.started": {
		"Description": "Generated from contracts/event-catalog.yaml for validation.started.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"geography": {
					"type": "string"
				},
				"scoring_context": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				},
				"vertical_name": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"vertical.approved": {
		"Description": "Generated from contracts/event-catalog.yaml for vertical.approved.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"brand_choice": {
					"type": "string"
				},
				"founder_directives": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"vertical.derived": {
		"Description": "Generated from contracts/event-catalog.yaml for vertical.derived.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"build_sketch": {
					"additionalProperties": true,
					"type": "object"
				},
				"campaign_id": {
					"type": "string"
				},
				"derivation_rationale": {
					"additionalProperties": true,
					"type": "object"
				},
				"discovery_context": {
					"additionalProperties": true,
					"type": "object"
				},
				"evidence": {
					"additionalProperties": true,
					"type": "object"
				},
				"generation_depth": {
					"type": "integer"
				},
				"generator_agent_id": {
					"type": "string"
				},
				"geographic_scope": {
					"type": "string"
				},
				"opportunity_id": {
					"type": "string"
				},
				"opportunity_name": {
					"type": "string"
				},
				"parent_id": {
					"type": "string"
				},
				"preliminary_icp": {
					"type": "string"
				},
				"signal_strength": {
					"type": "number"
				}
			},
			"type": "object"
		}
	},
	"vertical.discovered": {
		"Description": "Generated from contracts/event-catalog.yaml for vertical.discovered.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"discovery_context": {
					"additionalProperties": true,
					"type": "object"
				},
				"geographic_scope": {
					"type": "string"
				},
				"geography": {
					"type": "string"
				},
				"mode": {
					"type": "string"
				},
				"raw_signals": {
					"additionalProperties": true,
					"type": "object"
				},
				"vertical_name": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"vertical.health_warning": {
		"Description": "Generated from contracts/event-catalog.yaml for vertical.health_warning.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"metrics": {
					"type": "object"
				},
				"recommendation": {
					"type": "string"
				},
				"severity": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"vertical.killed": {
		"Description": "Generated from contracts/event-catalog.yaml for vertical.killed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"reason": {
					"type": "string"
				},
				"source": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"vertical.marginal": {
		"Description": "Generated from contracts/event-catalog.yaml for vertical.marginal.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"composite_score": {
					"type": "number"
				},
				"dimensions": {
					"additionalProperties": true,
					"type": "object"
				},
				"promotion_eligible": {
					"type": "boolean"
				},
				"vertical_id": {
					"type": "string"
				},
				"viability_score": {
					"type": "number"
				}
			},
			"type": "object"
		}
	},
	"vertical.needs_more_data": {
		"Description": "Generated from contracts/event-catalog.yaml for vertical.needs_more_data.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"questions": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"vertical.ready_for_review": {
		"Description": "Generated from contracts/event-catalog.yaml for vertical.ready_for_review.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"validation_kit": {
					"additionalProperties": true,
					"type": "object"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"vertical.rejected": {
		"Description": "Generated from contracts/event-catalog.yaml for vertical.rejected.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"reason": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"vertical.resumed": {
		"Description": "Generated from contracts/event-catalog.yaml for vertical.resumed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"vertical.scored": {
		"Description": "Generated from contracts/event-catalog.yaml for vertical.scored.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"composite_score": {
					"type": "number"
				},
				"dimensions": {
					"additionalProperties": true,
					"type": "object"
				},
				"market_score": {
					"type": "number"
				},
				"result": {
					"type": "string"
				},
				"rubric": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				},
				"viability_score": {
					"type": "number"
				}
			},
			"type": "object"
		}
	},
	"vertical.shortlisted": {
		"Description": "Generated from contracts/event-catalog.yaml for vertical.shortlisted.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"composite_score": {
					"type": "number"
				},
				"scoring_payload": {
					"additionalProperties": true,
					"type": "object"
				},
				"vertical_id": {
					"type": "string"
				},
				"viability_score": {
					"type": "number"
				}
			},
			"type": "object"
		}
	}
}
`)

func mustLoadGeneratedContractEventSchemaRegistry(raw string) map[string]EventSchema {
	out := map[string]EventSchema{}
	if err := json.Unmarshal([]byte(raw), &out); err != nil {
		panic(fmt.Sprintf("parse generated event schema registry: %v", err))
	}
	return out
}
