package contracts

// Code generated by scripts/generate_event_schema_registry/main.go; DO NOT EDIT.
// Source: resolved MAS contract bundle

import (
	"encoding/json"
	"fmt"
)

//go:generate go run ../../../scripts/generate_event_schema_registry
var generatedContractEventSchemaRegistry = mustLoadGeneratedContractEventSchemaRegistry(`
{
	"analyst.anti_pattern_advisory": {
		"Description": "Generated from the resolved MAS contract bundle for analyst.anti_pattern_advisory.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"affected_verticals": {
					"type": "array"
				},
				"pattern": {
					"type": "string"
				},
				"recommendation": {
					"type": "string"
				},
				"severity": {
					"type": "number"
				}
			},
			"type": "object"
		}
	},
	"analyst.bootstrap_upgrade_proposal": {
		"Description": "Generated from the resolved MAS contract bundle for analyst.bootstrap_upgrade_proposal.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"affected_routes": {
					"type": "array"
				},
				"evidence": {
					"type": "object"
				},
				"proposal_type": {
					"type": "string"
				},
				"recommendation": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"analyst.prompt_refinement_proposal": {
		"Description": "Generated from the resolved MAS contract bundle for analyst.prompt_refinement_proposal.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"agent_role": {
					"type": "string"
				},
				"current_behavior": {
					"type": "string"
				},
				"evidence": {
					"type": "object"
				},
				"proposed_change": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"backend.blocked": {
		"Description": "Generated from the resolved MAS contract bundle for backend.blocked.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"details": {
					"type": "string"
				},
				"status": {
					"type": "string"
				},
				"task": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"backend.task_complete": {
		"Description": "Generated from the resolved MAS contract bundle for backend.task_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"details": {
					"type": "string"
				},
				"status": {
					"type": "string"
				},
				"task": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"board.chat": {
		"Description": "Generated from the resolved MAS contract bundle for board.chat.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"context": {
					"type": "object"
				},
				"message": {
					"type": "string"
				},
				"response_requested": {
					"type": "boolean"
				}
			},
			"type": "object"
		}
	},
	"board.directive": {
		"Description": "Generated from the resolved MAS contract bundle for board.directive.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"directive_type": {
					"type": "string"
				},
				"parameters": {
					"type": "object"
				},
				"priority": {
					"type": "string"
				},
				"target": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"brand.candidates_ready": {
		"Description": "Generated from the resolved MAS contract bundle for brand.candidates_ready.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"candidates": {
					"type": "array"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"brand.requested": {
		"Description": "Generated from the resolved MAS contract bundle for brand.requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"business_brief": {
					"type": "object"
				},
				"geography": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				},
				"vertical_name": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"brand.revision_needed": {
		"Description": "Generated from the resolved MAS contract bundle for brand.revision_needed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"feedback": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"budget.adjustment_requested": {
		"Description": "Generated from the resolved MAS contract bundle for budget.adjustment_requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"adjustment_type": {
					"type": "string"
				},
				"amount": {
					"type": "number"
				},
				"reason": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"budget.alert_sent": {
		"Description": "Generated from the resolved MAS contract bundle for budget.alert_sent.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"alert_type": {
					"type": "string"
				},
				"details": {
					"type": "object"
				},
				"entity_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"budget.emergency": {
		"Description": "Generated from the resolved MAS contract bundle for budget.emergency.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"action_taken": {
					"type": "string"
				},
				"level": {
					"type": "string"
				},
				"message": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"budget.resumed": {
		"Description": "Generated from the resolved MAS contract bundle for budget.resumed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"message": {
					"type": "string"
				},
				"previous_level": {
					"type": "number"
				}
			},
			"type": "object"
		}
	},
	"budget.threshold_crossed": {
		"Description": "Generated from the resolved MAS contract bundle for budget.threshold_crossed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"budget_cap": {
					"type": "number"
				},
				"current_spend": {
					"type": "number"
				},
				"level": {
					"type": "string"
				},
				"percentage": {
					"type": "number"
				}
			},
			"type": "object"
		}
	},
	"budget.throttle": {
		"Description": "Generated from the resolved MAS contract bundle for budget.throttle.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"affected_agents": {
					"type": "array"
				},
				"throttle_level": {
					"type": "number"
				}
			},
			"type": "object"
		}
	},
	"budget.warning": {
		"Description": "Generated from the resolved MAS contract bundle for budget.warning.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"level": {
					"type": "string"
				},
				"message": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"bug_fix_deployed": {
		"Description": "Generated from the resolved MAS contract bundle for bug_fix_deployed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"bug_id": {
					"type": "string"
				},
				"resolution": {
					"type": "string"
				},
				"version": {
					"type": "number"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"bug_reported": {
		"Description": "Generated from the resolved MAS contract bundle for bug_reported.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"description": {
					"type": "string"
				},
				"reproduction_steps": {
					"type": "string"
				},
				"severity": {
					"type": "number"
				}
			},
			"type": "object"
		}
	},
	"build.escalation": {
		"Description": "Generated from the resolved MAS contract bundle for build.escalation.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"blocker": {
					"type": "string"
				},
				"severity": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"build_blocked": {
		"Description": "Generated from the resolved MAS contract bundle for build_blocked.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"blocker": {
					"type": "string"
				},
				"severity": {
					"type": "string"
				},
				"task": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"build_complete": {
		"Description": "Generated from the resolved MAS contract bundle for build_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"environment": {
					"type": "string"
				},
				"feature": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"build_progress": {
		"Description": "Generated from the resolved MAS contract bundle for build_progress.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"progress_pct": {
					"type": "integer"
				},
				"status": {
					"type": "string"
				},
				"task": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"campaign.completed": {
		"Description": "Generated from the resolved MAS contract bundle for campaign.completed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"campaign_id": {
					"type": "string"
				},
				"geography": {
					"type": "string"
				},
				"modes_completed": {
					"type": "string"
				},
				"verticals_discovered": {
					"type": "integer"
				},
				"verticals_shortlisted": {
					"type": "integer"
				},
				"verticals_skipped": {
					"type": "integer"
				}
			},
			"type": "object"
		}
	},
	"category.assessed": {
		"Description": "Generated from the resolved MAS contract bundle for category.assessed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"build_sketch": {
					"type": "object"
				},
				"category": {
					"type": "string"
				},
				"evidence": {
					"type": "object"
				},
				"geographic_scope": {
					"type": "string"
				},
				"geography": {
					"type": "string"
				},
				"opportunity_hypothesis": {
					"type": "string"
				},
				"opportunity_name": {
					"type": "string"
				},
				"opportunity_pattern": {
					"type": "string"
				},
				"preliminary_icp": {
					"type": "string"
				},
				"required_capabilities": {
					"type": "object"
				},
				"scan_id": {
					"type": "string"
				},
				"signal_sources": {
					"type": "array"
				},
				"signal_strength": {
					"type": "integer"
				},
				"subcategory": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"channel_blocked": {
		"Description": "Generated from the resolved MAS contract bundle for channel_blocked.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"channel": {
					"type": "string"
				},
				"reason": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"channel_update": {
		"Description": "Generated from the resolved MAS contract bundle for channel_update.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"channel": {
					"type": "string"
				},
				"metrics": {
					"type": "object"
				},
				"status": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"churn_risk": {
		"Description": "Generated from the resolved MAS contract bundle for churn_risk.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"customer_id": {
					"type": "string"
				},
				"risk_score": {
					"type": "number"
				},
				"signals": {
					"type": "array"
				}
			},
			"type": "object"
		}
	},
	"cross_domain_report": {
		"Description": "Generated from the resolved MAS contract bundle for cross_domain_report.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"domains": {
					"type": "array"
				},
				"summary": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"cto.architecture_directive": {
		"Description": "Generated from the resolved MAS contract bundle for cto.architecture_directive.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"affected_verticals": {
					"type": "array"
				},
				"directive": {
					"type": "string"
				},
				"rationale": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"cto.extraction_recommended": {
		"Description": "Generated from the resolved MAS contract bundle for cto.extraction_recommended.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"affected_verticals": {
					"type": "array"
				},
				"pattern_id": {
					"type": "string"
				},
				"recommendation": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"cto.pattern_detected": {
		"Description": "Generated from the resolved MAS contract bundle for cto.pattern_detected.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"description": {
					"type": "string"
				},
				"pattern_type": {
					"type": "string"
				},
				"verticals": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"cto.spec_approved": {
		"Description": "Generated from the resolved MAS contract bundle for cto.spec_approved.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"cto_notes": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"cto.spec_review_requested": {
		"Description": "Generated from the resolved MAS contract bundle for cto.spec_review_requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"business_brief": {
					"type": "object"
				},
				"mvp_spec": {
					"type": "string"
				},
				"vertical_context": {
					"type": "object"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"cto.spec_revision_needed": {
		"Description": "Generated from the resolved MAS contract bundle for cto.spec_revision_needed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"technical_issues": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"cto.spec_vetoed": {
		"Description": "Generated from the resolved MAS contract bundle for cto.spec_vetoed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"reason": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"cto.tech_spec_feedback": {
		"Description": "Generated from the resolved MAS contract bundle for cto.tech_spec_feedback.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"feedback": {
					"type": "string"
				},
				"severity": {
					"type": "number"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"cto.tech_spec_review_requested": {
		"Description": "Generated from the resolved MAS contract bundle for cto.tech_spec_review_requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"spec_content": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"cycle_limit_reached": {
		"Description": "Generated from the resolved MAS contract bundle for cycle_limit_reached.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"agents_involved": {
					"type": "array"
				},
				"count": {
					"type": "integer"
				},
				"event_pattern": {
					"type": "string"
				},
				"recommendation": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				},
				"window_hours": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"cycle_reset": {
		"Description": "Generated from the resolved MAS contract bundle for cycle_reset.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"reason": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"dedup.ambiguous": {
		"Description": "Generated from the resolved MAS contract bundle for dedup.ambiguous.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"dedup_id": {
					"type": "string"
				},
				"existing_vertical": {
					"type": "string"
				},
				"new_candidate": {
					"type": "string"
				},
				"similarity": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"dedup.resolved": {
		"Description": "Generated from the resolved MAS contract bundle for dedup.resolved.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"best_signal": {
					"type": "object (populated when strategy=keep_best)"
				},
				"dedup_id": {
					"type": "string"
				},
				"merged": {
					"type": "object (populated when strategy=merge_fields)"
				},
				"reasoning": {
					"type": "string"
				},
				"signal_a": {
					"type": "object"
				},
				"signal_b": {
					"type": "object"
				},
				"strategy": {
					"type": "string (keep_first | keep_best | merge_fields)"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"deploy.authorized": {
		"Description": "Generated from the resolved MAS contract bundle for deploy.authorized.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"authorized_by": {
					"type": "string"
				},
				"deployment_id": {
					"type": "string"
				},
				"environment": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"deploy.requested": {
		"Description": "Generated from the resolved MAS contract bundle for deploy.requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"deployment_id": {
					"type": "string"
				},
				"environment": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"deploy_requested": {
		"Description": "Generated from the resolved MAS contract bundle for deploy_requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"component": {
					"type": "string"
				},
				"deploy_config": {
					"type": "string"
				},
				"version": {
					"type": "number"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"devops.capacity_warning": {
		"Description": "Generated from the resolved MAS contract bundle for devops.capacity_warning.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"current_usage": {
					"type": "string"
				},
				"recommendation": {
					"type": "string"
				},
				"resource": {
					"type": "string"
				},
				"threshold": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"devops.deploy_complete": {
		"Description": "Generated from the resolved MAS contract bundle for devops.deploy_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"environment": {
					"type": "string"
				},
				"url": {
					"type": "string"
				},
				"version": {
					"type": "number"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"devops.deploy_failed": {
		"Description": "Generated from the resolved MAS contract bundle for devops.deploy_failed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"environment": {
					"type": "string"
				},
				"error": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"devops.deploy_requested": {
		"Description": "Generated from the resolved MAS contract bundle for devops.deploy_requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"environment": {
					"type": "string"
				},
				"manifest": {
					"type": "object"
				},
				"requesting_agent": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"devops.health_check_failed": {
		"Description": "Generated from the resolved MAS contract bundle for devops.health_check_failed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"endpoint": {
					"type": "string"
				},
				"error": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"devops.infra_change_needed": {
		"Description": "Generated from the resolved MAS contract bundle for devops.infra_change_needed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"change_type": {
					"type": "string"
				},
				"estimated_cost": {
					"type": "number"
				},
				"reason": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"devops.rollback_complete": {
		"Description": "Generated from the resolved MAS contract bundle for devops.rollback_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"active_version": {
					"type": "integer"
				},
				"environment": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"devops.rollback_failed": {
		"Description": "Generated from the resolved MAS contract bundle for devops.rollback_failed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"environment": {
					"type": "string"
				},
				"error": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"devops.rollback_requested": {
		"Description": "Generated from the resolved MAS contract bundle for devops.rollback_requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"requesting_agent": {
					"type": "string"
				},
				"target_version": {
					"type": "integer"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"devops.ssl_provisioned": {
		"Description": "Generated from the resolved MAS contract bundle for devops.ssl_provisioned.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"domain": {
					"type": "string"
				},
				"expiry": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"directive.unhandled": {
		"Description": "Generated from the resolved MAS contract bundle for directive.unhandled.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"directive_text": {
					"type": "string"
				},
				"directive_type": {
					"type": "string"
				},
				"reason": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"feature_deployed": {
		"Description": "Generated from the resolved MAS contract bundle for feature_deployed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"feature": {
					"type": "string"
				},
				"version": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"feature_request": {
		"Description": "Generated from the resolved MAS contract bundle for feature_request.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"description": {
					"type": "string"
				},
				"priority": {
					"type": "string"
				},
				"source": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"founder_input.response": {
		"Description": "Generated from the resolved MAS contract bundle for founder_input.response.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"decision": {
					"type": "string"
				},
				"request_id": {
					"type": "string"
				},
				"response": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"frontend.blocked": {
		"Description": "Generated from the resolved MAS contract bundle for frontend.blocked.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"details": {
					"type": "string"
				},
				"status": {
					"type": "string"
				},
				"task": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"frontend.task_complete": {
		"Description": "Generated from the resolved MAS contract bundle for frontend.task_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"details": {
					"type": "string"
				},
				"status": {
					"type": "string"
				},
				"task": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"growth_escalation": {
		"Description": "Generated from the resolved MAS contract bundle for growth_escalation.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"issue": {
					"type": "string"
				},
				"severity": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"growth_report": {
		"Description": "Generated from the resolved MAS contract bundle for growth_report.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"experiments": {
					"type": "array"
				},
				"metrics": {
					"type": "object"
				},
				"period": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"human_task.approved": {
		"Description": "Generated from the resolved MAS contract bundle for human_task.approved.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"notes": {
					"type": "string"
				},
				"task_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"human_task.assigned": {
		"Description": "Generated from the resolved MAS contract bundle for human_task.assigned.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"assigned_to": {
					"type": "string"
				},
				"requesting_agent": {
					"type": "string"
				},
				"task_id": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"human_task.completed": {
		"Description": "Generated from the resolved MAS contract bundle for human_task.completed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"result": {
					"type": "object"
				},
				"task_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"human_task.deferred": {
		"Description": "Generated from the resolved MAS contract bundle for human_task.deferred.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"defer_until": {
					"type": "string"
				},
				"reason": {
					"type": "string"
				},
				"task_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"human_task.expired": {
		"Description": "Generated from the resolved MAS contract bundle for human_task.expired.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"task_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"human_task.rejected": {
		"Description": "Generated from the resolved MAS contract bundle for human_task.rejected.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"reason": {
					"type": "string"
				},
				"task_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"human_task.requested": {
		"Description": "Generated from the resolved MAS contract bundle for human_task.requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"description": {
					"type": "string"
				},
				"requesting_agent": {
					"type": "string"
				},
				"task_id": {
					"type": "string"
				},
				"task_type": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"inbound.chat": {
		"Description": "Generated from the resolved MAS contract bundle for inbound.chat.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"from": {
					"type": "string"
				},
				"media_urls": {
					"type": "array"
				},
				"message": {
					"type": "string"
				},
				"timestamp": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"inbound.email": {
		"Description": "Generated from the resolved MAS contract bundle for inbound.email.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"attachments": {
					"type": "array"
				},
				"body": {
					"type": "string"
				},
				"from": {
					"type": "string"
				},
				"subject": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"launch_ready": {
		"Description": "Generated from the resolved MAS contract bundle for launch_ready.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"deploy_url": {
					"type": "string"
				},
				"test_results": {
					"type": "object"
				},
				"version": {
					"type": "number"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"mailbox.item_decided": {
		"Description": "Generated from the resolved MAS contract bundle for mailbox.item_decided.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"decided_by": {
					"type": "string"
				},
				"decision": {
					"type": "string"
				},
				"item_id": {
					"type": "string"
				},
				"original_event_type": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"mailbox.review_requested": {
		"Description": "Generated from the resolved MAS contract bundle for mailbox.review_requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"entity_id": {
					"type": "string"
				},
				"review_type": {
					"type": "string"
				},
				"validation_kit": {
					"type": "object"
				}
			},
			"type": "object"
		}
	},
	"mandate_updated": {
		"Description": "Generated from the resolved MAS contract bundle for mandate_updated.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"changes": {
					"type": "object"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"market_feedback": {
		"Description": "Generated from the resolved MAS contract bundle for market_feedback.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"feedback": {
					"type": "string"
				},
				"sentiment": {
					"type": "string"
				},
				"source": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"market_signals": {
		"Description": "Generated from the resolved MAS contract bundle for market_signals.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"data": {
					"type": "object"
				},
				"signal_type": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.ceo_ready": {
		"Description": "Generated from the resolved MAS contract bundle for opco.ceo_ready.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"agent_count": {
					"type": "number"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.ceo_report": {
		"Description": "Generated from the resolved MAS contract bundle for opco.ceo_report.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"decisions": {
					"type": "string"
				},
				"metrics": {
					"type": "object"
				},
				"phase": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.deploy_review": {
		"Description": "Generated from the resolved MAS contract bundle for opco.deploy_review.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"deployment_id": {
					"type": "string"
				},
				"review_notes": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.escalation": {
		"Description": "Generated from the resolved MAS contract bundle for opco.escalation.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"issue": {
					"type": "string"
				},
				"recommendation": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.escalation_response": {
		"Description": "Generated from the resolved MAS contract bundle for opco.escalation_response.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"directive": {
					"type": "string"
				},
				"original_escalation_id": {
					"type": "string"
				},
				"priority": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.founder_input": {
		"Description": "Generated from the resolved MAS contract bundle for opco.founder_input.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"context": {
					"type": "string"
				},
				"question": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.growth_stabilized": {
		"Description": "Generated from the resolved MAS contract bundle for opco.growth_stabilized.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"stabilization_metrics": {
					"type": "object"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.growth_triggered": {
		"Description": "Generated from the resolved MAS contract bundle for opco.growth_triggered.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"trigger_reason": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.launched": {
		"Description": "Generated from the resolved MAS contract bundle for opco.launched.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"launch_url": {
					"type": "string"
				},
				"metrics": {
					"type": "object"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.product_spec_review": {
		"Description": "Generated from the resolved MAS contract bundle for opco.product_spec_review.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"feedback": {
					"type": "string"
				},
				"review_result": {
					"type": "string"
				},
				"spec_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.routing_updated": {
		"Description": "Generated from the resolved MAS contract bundle for opco.routing_updated.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"bootstrap_version": {
					"type": "integer"
				},
				"event_pattern": {
					"type": "string"
				},
				"installed_by": {
					"type": "string"
				},
				"reason": {
					"type": "string"
				},
				"runtime_tool_event": {
					"type": "boolean"
				},
				"source": {
					"type": "string"
				},
				"status": {
					"type": "string"
				},
				"subscriber_id": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.spend_request": {
		"Description": "Generated from the resolved MAS contract bundle for opco.spend_request.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"amount": {
					"type": "number"
				},
				"reason": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.spinup_requested": {
		"Description": "Generated from the resolved MAS contract bundle for opco.spinup_requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"brand": {
					"type": "object"
				},
				"founder_directives": {
					"type": "string"
				},
				"mandate": {
					"type": "object"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.steady_state_reached": {
		"Description": "Generated from the resolved MAS contract bundle for opco.steady_state_reached.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.teardown_complete": {
		"Description": "Generated from the resolved MAS contract bundle for opco.teardown_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.teardown_requested": {
		"Description": "Generated from the resolved MAS contract bundle for opco.teardown_requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"reason": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"opco.terminated": {
		"Description": "Generated from the resolved MAS contract bundle for opco.terminated.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"instance_id": {
					"type": "string"
				},
				"teardown_summary": {
					"type": "string"
				},
				"terminated_at": {
					"type": "timestamp"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"operating.timeout_escalation": {
		"Description": "Generated from the resolved MAS contract bundle for operating.timeout_escalation.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"action": {
					"type": "string"
				},
				"stuck_state": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"ops.agent_failed": {
		"Description": "Generated from the resolved MAS contract bundle for ops.agent_failed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"agent_id": {
					"type": "string"
				},
				"error": {
					"type": "string"
				},
				"last_event_type": {
					"type": "string"
				},
				"retry_count": {
					"type": "number"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"ops.agent_panic": {
		"Description": "Generated from the resolved MAS contract bundle for ops.agent_panic.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"agent_id": {
					"type": "string"
				},
				"conversation_id": {
					"type": "string"
				},
				"error": {
					"type": "string"
				},
				"stack_trace": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"outreach_digest": {
		"Description": "Generated from the resolved MAS contract bundle for outreach_digest.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"best_channel": {
					"type": "string"
				},
				"intelligence": {
					"type": "string"
				},
				"leads_converted": {
					"type": "string"
				},
				"messages_sent": {
					"type": "string"
				},
				"response_rate": {
					"type": "string"
				},
				"responses": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"pipeline.dead_letter": {
		"Description": "Generated from the resolved MAS contract bundle for pipeline.dead_letter.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"error": {
					"type": "string"
				},
				"flow": {
					"type": "string"
				},
				"original_event": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"policy.change_requested": {
		"Description": "Generated from the resolved MAS contract bundle for policy.change_requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"new_value": {
					"type": "string"
				},
				"policy_key": {
					"type": "string"
				},
				"reason": {
					"type": "string"
				},
				"requested_by": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"portfolio.digest_compiled": {
		"Description": "Generated from the resolved MAS contract bundle for portfolio.digest_compiled.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"action_required_count": {
					"type": "integer"
				},
				"digest_text": {
					"type": "string"
				},
				"trigger_reason": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"prelaunch_ready": {
		"Description": "Generated from the resolved MAS contract bundle for prelaunch_ready.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"blockers": {
					"type": "array"
				},
				"checklist": {
					"type": "object"
				}
			},
			"type": "object"
		}
	},
	"primary.scan_assigned": {
		"Description": "Generated from the resolved MAS contract bundle for primary.scan_assigned.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"corpus_signals": {
					"type": "array"
				},
				"geography": {
					"type": "string"
				},
				"mode": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"shard": {
					"type": "object"
				},
				"taxonomy_categories": {
					"type": "array"
				}
			},
			"type": "object"
		}
	},
	"primary.scan_complete": {
		"Description": "Generated from the resolved MAS contract bundle for primary.scan_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"categories_assessed": {
					"type": "integer"
				},
				"geography": {
					"type": "string"
				},
				"high_signal_count": {
					"type": "integer"
				},
				"scan_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"product_escalation": {
		"Description": "Generated from the resolved MAS contract bundle for product_escalation.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"context": {
					"type": "object"
				},
				"issue": {
					"type": "string"
				},
				"severity": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"product_report": {
		"Description": "Generated from the resolved MAS contract bundle for product_report.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"highlights": {
					"type": "string"
				},
				"metrics": {
					"type": "object"
				},
				"period": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"product_spec_ready": {
		"Description": "Generated from the resolved MAS contract bundle for product_spec_ready.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"feature": {
					"type": "string"
				},
				"spec_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"qa.validation_failed": {
		"Description": "Generated from the resolved MAS contract bundle for qa.validation_failed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"expected_vs_actual": {
					"type": "string"
				},
				"failures": {
					"type": "string"
				},
				"reproduction_steps": {
					"type": "string"
				},
				"severity": {
					"type": "number"
				}
			},
			"type": "object"
		}
	},
	"qa.validation_passed": {
		"Description": "Generated from the resolved MAS contract bundle for qa.validation_passed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"coverage_notes": {
					"type": "string"
				},
				"staging_url": {
					"type": "string"
				},
				"test_summary": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"research.additional_requested": {
		"Description": "Generated from the resolved MAS contract bundle for research.additional_requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"entity_id": {
					"type": "string"
				},
				"focus_areas": {
					"type": "array"
				},
				"requested_by": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"research.completed": {
		"Description": "Generated from the resolved MAS contract bundle for research.completed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"business_brief": {
					"type": "object"
				},
				"research_context": {
					"type": "object"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"research.vertical_rejected": {
		"Description": "Generated from the resolved MAS contract bundle for research.vertical_rejected.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"evidence": {
					"type": "object"
				},
				"rejection_reason": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"review.deploy_feedback": {
		"Description": "Generated from the resolved MAS contract bundle for review.deploy_feedback.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"feedback": {
					"type": "string"
				},
				"reviewer": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"review.product_spec_feedback": {
		"Description": "Generated from the resolved MAS contract bundle for review.product_spec_feedback.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"feedback": {
					"type": "string"
				},
				"reviewer": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"runtime.reset": {
		"Description": "Generated from the resolved MAS contract bundle for runtime.reset.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"source": {
					"type": "string"
				},
				"timestamp": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scan.category_dispatch": {
		"Description": "Generated from the resolved MAS contract bundle for scan.category_dispatch.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"geography": {
					"type": "string"
				},
				"mode": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"sources": {
					"type": "array"
				},
				"subcategories": {
					"type": "array"
				}
			},
			"type": "object"
		}
	},
	"scan.completed": {
		"Description": "Generated from the resolved MAS contract bundle for scan.completed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"agents_complete": {
					"type": "integer"
				},
				"agents_expected": {
					"type": "integer"
				},
				"campaign_id": {
					"type": "string"
				},
				"geography": {
					"type": "string"
				},
				"mode": {
					"type": "string"
				},
				"reports_received": {
					"type": "integer"
				},
				"verticals_discovered": {
					"type": "integer"
				},
				"verticals_skipped": {
					"type": "integer"
				}
			},
			"type": "object"
		}
	},
	"scan.requested": {
		"Description": "Generated from the resolved MAS contract bundle for scan.requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"campaign_context": {
					"type": "object"
				},
				"campaign_id": {
					"type": "string"
				},
				"corpus_path": {
					"type": "string"
				},
				"depth": {
					"type": "string"
				},
				"geography": {
					"type": "string"
				},
				"mode": {
					"type": "string"
				},
				"sources": {
					"type": "array"
				},
				"taxonomy_categories": {
					"type": "array"
				}
			},
			"type": "object"
		}
	},
	"scan.source_dispatch": {
		"Description": "Generated from the resolved MAS contract bundle for scan.source_dispatch.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"geography": {
					"type": "string"
				},
				"mode": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"sources": {
					"type": "array"
				},
				"subcategories": {
					"type": "array"
				}
			},
			"type": "object"
		}
	},
	"scan.trend_dispatch": {
		"Description": "Generated from the resolved MAS contract bundle for scan.trend_dispatch.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"geography": {
					"type": "string"
				},
				"mode": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"sources": {
					"type": "array"
				},
				"subcategories": {
					"type": "array"
				},
				"trend_topics": {
					"type": "array"
				}
			},
			"type": "object"
		}
	},
	"scanner.directories.scan_assigned": {
		"Description": "Generated from the resolved MAS contract bundle for scanner.directories.scan_assigned.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"geography": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"source_config": {
					"type": "string"
				},
				"subcategory": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scanner.directories.scan_complete": {
		"Description": "Generated from the resolved MAS contract bundle for scanner.directories.scan_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"errors": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"sources_found": {
					"type": "string"
				},
				"sources_scraped": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scanner.google_maps.scan_assigned": {
		"Description": "Generated from the resolved MAS contract bundle for scanner.google_maps.scan_assigned.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"geography": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"source_config": {
					"type": "string"
				},
				"subcategory": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scanner.google_maps.scan_complete": {
		"Description": "Generated from the resolved MAS contract bundle for scanner.google_maps.scan_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"errors": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"sources_found": {
					"type": "string"
				},
				"sources_scraped": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scanner.instagram.scan_assigned": {
		"Description": "Generated from the resolved MAS contract bundle for scanner.instagram.scan_assigned.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"geography": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"source_config": {
					"type": "string"
				},
				"subcategory": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scanner.instagram.scan_complete": {
		"Description": "Generated from the resolved MAS contract bundle for scanner.instagram.scan_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"errors": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"sources_found": {
					"type": "string"
				},
				"sources_scraped": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scanner.reviews.scan_assigned": {
		"Description": "Generated from the resolved MAS contract bundle for scanner.reviews.scan_assigned.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"geography": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"source_config": {
					"type": "string"
				},
				"subcategory": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scanner.reviews.scan_complete": {
		"Description": "Generated from the resolved MAS contract bundle for scanner.reviews.scan_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"errors": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"sources_found": {
					"type": "string"
				},
				"sources_scraped": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scanner.scan_assigned": {
		"Description": "Generated from the resolved MAS contract bundle for scanner.scan_assigned.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"geography": {
					"type": "string"
				},
				"partition": {
					"type": "object"
				},
				"scan_id": {
					"type": "string"
				},
				"source": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scanner.yelp.scan_assigned": {
		"Description": "Generated from the resolved MAS contract bundle for scanner.yelp.scan_assigned.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"geography": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"source_config": {
					"type": "string"
				},
				"subcategory": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scanner.yelp.scan_complete": {
		"Description": "Generated from the resolved MAS contract bundle for scanner.yelp.scan_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"errors": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"sources_found": {
					"type": "string"
				},
				"sources_scraped": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"score.dimension_complete": {
		"Description": "Generated from the resolved MAS contract bundle for score.dimension_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"confidence": {
					"type": "string"
				},
				"dimension": {
					"type": "string"
				},
				"evidence": {
					"type": "string"
				},
				"score": {
					"type": "integer"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scoring.derived_requested": {
		"Description": "Generated from the resolved MAS contract bundle for scoring.derived_requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"dimensions_requested": {
					"type": "array"
				},
				"mode": {
					"type": "string"
				},
				"rubric": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"scoring.requested": {
		"Description": "Generated from the resolved MAS contract bundle for scoring.requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"assigned_analysis_agent_id": {
					"type": "string"
				},
				"dimensions_requested": {
					"type": "array"
				},
				"discovery_context": {
					"type": "object"
				},
				"excluded_analysis_agent_id": {
					"type": "string"
				},
				"geography": {
					"type": "string"
				},
				"mode": {
					"type": "string"
				},
				"rubric": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				},
				"vertical_name": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"secondary.scan_assigned": {
		"Description": "Generated from the resolved MAS contract bundle for secondary.scan_assigned.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"geography": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"secondary.scan_complete": {
		"Description": "Generated from the resolved MAS contract bundle for secondary.scan_complete.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"geography": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"trends_identified": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"source.scraped": {
		"Description": "Generated from the resolved MAS contract bundle for source.scraped.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"evidence": {
					"type": "string"
				},
				"geography": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"source": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spec.approved": {
		"Description": "Generated from the resolved MAS contract bundle for spec.approved.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"final_spec": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spec.contradiction_detected": {
		"Description": "Generated from the resolved MAS contract bundle for spec.contradiction_detected.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"agent_id": {
					"type": "string"
				},
				"contradiction_type": {
					"type": "string"
				},
				"detail": {
					"type": "object"
				}
			},
			"type": "object"
		}
	},
	"spec.draft_ready": {
		"Description": "Generated from the resolved MAS contract bundle for spec.draft_ready.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"mvp_spec": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spec.requested": {
		"Description": "Generated from the resolved MAS contract bundle for spec.requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"business_brief": {
					"type": "object"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spec.revision_needed": {
		"Description": "Generated from the resolved MAS contract bundle for spec.revision_needed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"misalignment_details": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spec.revision_requested": {
		"Description": "Generated from the resolved MAS contract bundle for spec.revision_requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"cto_feedback": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spec.validation_failed": {
		"Description": "Generated from the resolved MAS contract bundle for spec.validation_failed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"issues": {
					"type": "array"
				},
				"severity": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spec.validation_passed": {
		"Description": "Generated from the resolved MAS contract bundle for spec.validation_passed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"validation_notes": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spec.validation_requested": {
		"Description": "Generated from the resolved MAS contract bundle for spec.validation_requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"spec_content": {
					"type": "string"
				},
				"spec_tier": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spec_review.issues_found": {
		"Description": "Generated from the resolved MAS contract bundle for spec_review.issues_found.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"issues": {
					"type": "array"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spec_review.passed": {
		"Description": "Generated from the resolved MAS contract bundle for spec_review.passed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"entity_id": {
					"type": "string"
				},
				"final_spec": {
					"type": "string"
				},
				"review_notes": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spec_review.requested": {
		"Description": "Generated from the resolved MAS contract bundle for spec_review.requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"business_brief": {
					"type": "object"
				},
				"mvp_spec": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spend.approved": {
		"Description": "Generated from the resolved MAS contract bundle for spend.approved.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"amount": {
					"type": "string"
				},
				"purpose": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spend.rejected": {
		"Description": "Generated from the resolved MAS contract bundle for spend.rejected.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"reason": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spend_needed": {
		"Description": "Generated from the resolved MAS contract bundle for spend_needed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"amount": {
					"type": "number"
				},
				"reason": {
					"type": "string"
				},
				"requester": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"spend_request": {
		"Description": "Generated from the resolved MAS contract bundle for spend_request.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"amount": {
					"type": "string"
				},
				"currency": {
					"type": "string"
				},
				"justification": {
					"type": "string"
				},
				"purpose": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"support_critical": {
		"Description": "Generated from the resolved MAS contract bundle for support_critical.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"customer": {
					"type": "string"
				},
				"issue": {
					"type": "string"
				},
				"ticket_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"support_digest": {
		"Description": "Generated from the resolved MAS contract bundle for support_digest.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"period": {
					"type": "string"
				},
				"themes": {
					"type": "array"
				},
				"ticket_count": {
					"type": "integer"
				}
			},
			"type": "object"
		}
	},
	"synthesis.needed": {
		"Description": "Generated from the resolved MAS contract bundle for synthesis.needed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"conflicting_reports": {
					"type": "string"
				},
				"context": {
					"type": "object"
				}
			},
			"type": "object"
		}
	},
	"synthesis.resolved": {
		"Description": "Generated from the resolved MAS contract bundle for synthesis.resolved.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"reasoning": {
					"type": "string"
				},
				"resolution": {
					"type": "string (accept_a | accept_b | synthesize)"
				},
				"signal_a": {
					"type": "object"
				},
				"signal_b": {
					"type": "object"
				},
				"synthesis_id": {
					"type": "string"
				},
				"synthesized": {
					"type": "object (populated when resolution=synthesize)"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"system.directive": {
		"Description": "Generated from the resolved MAS contract bundle for system.directive.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"directive": {
					"type": "string (scan | budget_adjust | policy_change | vertical_override)"
				},
				"timestamp": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"system.started": {
		"Description": "Generated from the resolved MAS contract bundle for system.started.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"agent_count": {
					"type": "number"
				},
				"config_version": {
					"type": "string"
				},
				"is_cold_start": {
					"type": "boolean"
				},
				"timestamp": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"technical_spec_ready": {
		"Description": "Generated from the resolved MAS contract bundle for technical_spec_ready.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"feature": {
					"type": "string"
				},
				"spec_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"template.migration_approved": {
		"Description": "Generated from the resolved MAS contract bundle for template.migration_approved.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"template_version": {
					"type": "string"
				},
				"verticals": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"template.migration_completed": {
		"Description": "Generated from the resolved MAS contract bundle for template.migration_completed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"result": {
					"type": "object"
				},
				"template_version": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"template.migration_failed": {
		"Description": "Generated from the resolved MAS contract bundle for template.migration_failed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"error": {
					"type": "string"
				},
				"template_version": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"template.migration_planned": {
		"Description": "Generated from the resolved MAS contract bundle for template.migration_planned.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"affected_verticals": {
					"type": "array"
				},
				"migration_plan": {
					"type": "object"
				},
				"template_version": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"template.publish_requested": {
		"Description": "Generated from the resolved MAS contract bundle for template.publish_requested.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"changes": {
					"type": "string"
				},
				"template_version": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"template.version_published": {
		"Description": "Generated from the resolved MAS contract bundle for template.version_published.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"changelog": {
					"type": "string"
				},
				"template_version": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"timer.campaign_deadline": {
		"Description": "Generated from the resolved MAS contract bundle for timer.campaign_deadline.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"campaign_id": {
					"type": "string"
				},
				"elapsed_hours": {
					"type": "integer"
				}
			},
			"type": "object"
		}
	},
	"timer.infra_health_check": {
		"Description": "Generated from the resolved MAS contract bundle for timer.infra_health_check.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"check_type": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"timer.instance_digest": {
		"Description": "Generated from the resolved MAS contract bundle for timer.instance_digest.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"trigger_reason": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"timer.marginal_kill": {
		"Description": "Generated from the resolved MAS contract bundle for timer.marginal_kill.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"parked_days": {
					"type": "integer"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"timer.marginal_review": {
		"Description": "Generated from the resolved MAS contract bundle for timer.marginal_review.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"parked_marginals_summary": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"timer.operating_timeout": {
		"Description": "Generated from the resolved MAS contract bundle for timer.operating_timeout.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"elapsed_hours": {
					"type": "integer"
				},
				"stuck_state": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"timer.scan_timeout": {
		"Description": "Generated from the resolved MAS contract bundle for timer.scan_timeout.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"elapsed_minutes": {
					"type": "integer"
				},
				"scan_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"timer.validation_timeout": {
		"Description": "Generated from the resolved MAS contract bundle for timer.validation_timeout.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"elapsed_hours": {
					"type": "integer"
				},
				"stuck_state": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"trend.identified": {
		"Description": "Generated from the resolved MAS contract bundle for trend.identified.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"build_sketch": {
					"type": "object"
				},
				"evidence": {
					"type": "object"
				},
				"geographic_scope": {
					"type": "string"
				},
				"geography": {
					"type": "string"
				},
				"opportunity_hypothesis": {
					"type": "string"
				},
				"opportunity_name": {
					"type": "string"
				},
				"preliminary_icp": {
					"type": "string"
				},
				"scan_id": {
					"type": "string"
				},
				"signal_strength": {
					"type": "integer"
				},
				"trend_category": {
					"type": "string"
				},
				"trend_description": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"user_onboarded": {
		"Description": "Generated from the resolved MAS contract bundle for user_onboarded.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"channel": {
					"type": "string"
				},
				"user_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"validation.more_data_needed": {
		"Description": "Generated from the resolved MAS contract bundle for validation.more_data_needed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"questions": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"validation.package_ready": {
		"Description": "Generated from the resolved MAS contract bundle for validation.package_ready.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"brand": {
					"type": "string"
				},
				"cto_notes": {
					"type": "string"
				},
				"research": {
					"type": "string"
				},
				"spec": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"validation.revision_limit_reached": {
		"Description": "Generated from the resolved MAS contract bundle for validation.revision_limit_reached.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"gate": {
					"type": "string"
				},
				"revision_count": {
					"type": "integer"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"validation.started": {
		"Description": "Generated from the resolved MAS contract bundle for validation.started.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"geography": {
					"type": "string"
				},
				"scoring_context": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				},
				"vertical_name": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"validation.timeout_escalation": {
		"Description": "Generated from the resolved MAS contract bundle for validation.timeout_escalation.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"action": {
					"type": "string"
				},
				"stuck_state": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"vertical.approved": {
		"Description": "Generated from the resolved MAS contract bundle for vertical.approved.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"brand_choice": {
					"type": "string"
				},
				"founder_directives": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"vertical.derived": {
		"Description": "Generated from the resolved MAS contract bundle for vertical.derived.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"build_sketch": {
					"type": "object"
				},
				"campaign_id": {
					"type": "string"
				},
				"derivation_rationale": {
					"type": "object"
				},
				"discovery_context": {
					"type": "object"
				},
				"evidence": {
					"type": "object"
				},
				"generation_depth": {
					"type": "integer"
				},
				"generator_agent_id": {
					"type": "string"
				},
				"geographic_scope": {
					"type": "string"
				},
				"opportunity_id": {
					"type": "string"
				},
				"opportunity_name": {
					"type": "string"
				},
				"parent_id": {
					"type": "string"
				},
				"preliminary_icp": {
					"type": "string"
				},
				"signal_strength": {
					"type": "number"
				}
			},
			"type": "object"
		}
	},
	"vertical.discovered": {
		"Description": "Generated from the resolved MAS contract bundle for vertical.discovered.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"discovery_context": {
					"type": "object"
				},
				"geographic_scope": {
					"type": "string"
				},
				"geography": {
					"type": "string"
				},
				"mode": {
					"type": "string"
				},
				"opportunity_pattern": {
					"type": "string"
				},
				"raw_signals": {
					"type": "object"
				},
				"signal_strength": {
					"type": "integer"
				},
				"vertical_name": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"vertical.health_warning": {
		"Description": "Generated from the resolved MAS contract bundle for vertical.health_warning.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"metrics": {
					"type": "object"
				},
				"recommendation": {
					"type": "string"
				},
				"severity": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"vertical.killed": {
		"Description": "Generated from the resolved MAS contract bundle for vertical.killed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"reason": {
					"type": "string"
				},
				"source": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"vertical.killed_backprop": {
		"Description": "Generated from the resolved MAS contract bundle for vertical.killed_backprop.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"kill_reason": {
					"type": "string"
				},
				"killed_by_flow": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"vertical.marginal": {
		"Description": "Generated from the resolved MAS contract bundle for vertical.marginal.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"composite_score": {
					"type": "number"
				},
				"dimensions": {
					"type": "object"
				},
				"promotion_eligible": {
					"type": "boolean"
				},
				"vertical_id": {
					"type": "string"
				},
				"viability_score": {
					"type": "number"
				}
			},
			"type": "object"
		}
	},
	"vertical.marginal_review_due": {
		"Description": "Generated from the resolved MAS contract bundle for vertical.marginal_review_due.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"entity_id": {
					"type": "string"
				},
				"parked_days": {
					"type": "integer"
				}
			},
			"type": "object"
		}
	},
	"vertical.needs_more_data": {
		"Description": "Generated from the resolved MAS contract bundle for vertical.needs_more_data.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"questions": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"vertical.ready_for_review": {
		"Description": "Generated from the resolved MAS contract bundle for vertical.ready_for_review.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"validation_kit": {
					"type": "object"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"vertical.rejected": {
		"Description": "Generated from the resolved MAS contract bundle for vertical.rejected.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"reason": {
					"type": "string"
				},
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"vertical.resumed": {
		"Description": "Generated from the resolved MAS contract bundle for vertical.resumed.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"vertical_id": {
					"type": "string"
				}
			},
			"type": "object"
		}
	},
	"vertical.shortlisted": {
		"Description": "Generated from the resolved MAS contract bundle for vertical.shortlisted.",
		"Schema": {
			"additionalProperties": false,
			"properties": {
				"composite_score": {
					"type": "number"
				},
				"scoring_payload": {
					"type": "object"
				},
				"vertical_id": {
					"type": "string"
				},
				"viability_score": {
					"type": "number"
				}
			},
			"type": "object"
		}
	}
}
`)

func mustLoadGeneratedContractEventSchemaRegistry(raw string) map[string]EventSchema {
	out := map[string]EventSchema{}
	if err := json.Unmarshal([]byte(raw), &out); err != nil {
		panic(fmt.Sprintf("parse generated event schema registry: %v", err))
	}
	return out
}
