package store

import (
	"github.com/division-sh/swarm/internal/store/construction"
	private "github.com/division-sh/swarm/internal/store/internal/runtimepersistence"
)

type APIIdempotencyCompletion = private.APIIdempotencyCompletion
type APIIdempotencyConflictError = private.APIIdempotencyConflictError
type APIIdempotencyRequest = private.APIIdempotencyRequest
type AgentDeliveryDiagnosticsCursorError = private.AgentDeliveryDiagnosticsCursorError
type AgentDeliveryLifecycleCursorError = private.AgentDeliveryLifecycleCursorError
type AgentDeliveryLifecycleFacts = private.AgentDeliveryLifecycleFacts
type AgentDeliveryLifecycleStatusError = private.AgentDeliveryLifecycleStatusError
type BundleCatalogAgentDefinition = private.BundleCatalogAgentDefinition
type BundleCatalogAgentsResult = private.BundleCatalogAgentsResult
type BundleCatalogConflictError = private.BundleCatalogConflictError
type BundleCatalogDetail = private.BundleCatalogDetail
type BundleCatalogListOptions = private.BundleCatalogListOptions
type BundleCatalogListResult = private.BundleCatalogListResult
type BundleCatalogSummary = private.BundleCatalogSummary
type BundleCatalogUpsert = private.BundleCatalogUpsert
type BundleCatalogUpsertResult = private.BundleCatalogUpsertResult
type ConversationForkChatExecution = private.ConversationForkChatExecution
type ConversationForkChatFailureRequest = private.ConversationForkChatFailureRequest
type ConversationForkChatPrepareRequest = private.ConversationForkChatPrepareRequest
type ConversationForkChatPrepared = private.ConversationForkChatPrepared
type ConversationForkChatRecordRequest = private.ConversationForkChatRecordRequest
type ConversationForkChatReplayStateError = private.ConversationForkChatReplayStateError
type ConversationForkChatResult = private.ConversationForkChatResult
type ConversationForkCreateRequest = private.ConversationForkCreateRequest
type ConversationForkDeleteResult = private.ConversationForkDeleteResult
type ConversationForkEntitySnapshot = private.ConversationForkEntitySnapshot
type ConversationForkListOptions = private.ConversationForkListOptions
type ConversationForkListResult = private.ConversationForkListResult
type ConversationForkPointDescriptor = private.ConversationForkPointDescriptor
type ConversationForkPointSelector = private.ConversationForkPointSelector
type ConversationForkSandboxPolicy = private.ConversationForkSandboxPolicy
type ConversationForkSnapshot = private.ConversationForkSnapshot
type ConversationForkSourceTurn = private.ConversationForkSourceTurn
type ConversationRuntimeLastTurnDescriptor = private.ConversationRuntimeLastTurnDescriptor
type ConversationRuntimeStateDescriptor = private.ConversationRuntimeStateDescriptor
type ConversationRuntimeWatchdogDescriptor = private.ConversationRuntimeWatchdogDescriptor
type DatabasePasswordResolver = private.DatabasePasswordResolver
type EntityReadParamError = private.EntityReadParamError
type EventPayloadValidator = private.EventPayloadValidator
type MailboxStore = private.MailboxStore
type MailboxV1DecisionSheet = private.MailboxV1DecisionSheet
type MailboxV1DownstreamPreview = private.MailboxV1DownstreamPreview
type MailboxV1EntityContext = private.MailboxV1EntityContext
type MailboxV1HistoryEntry = private.MailboxV1HistoryEntry
type MailboxV1Item = private.MailboxV1Item
type MailboxV1ItemDetail = private.MailboxV1ItemDetail
type MailboxV1ListOptions = private.MailboxV1ListOptions
type OperatorAgentConversationReadSource = private.OperatorAgentConversationReadSource
type OperatorAgentConversationReadSurface = private.OperatorAgentConversationReadSurface
type OperatorAgentDeadLetterDelivery = private.OperatorAgentDeadLetterDelivery
type OperatorAgentDeliveryDiagnostics = private.OperatorAgentDeliveryDiagnostics
type OperatorAgentDeliveryDiagnosticsOptions = private.OperatorAgentDeliveryDiagnosticsOptions
type OperatorAgentDeliveryDiagnosticsSummary = private.OperatorAgentDeliveryDiagnosticsSummary
type OperatorAgentDeliveryFailure = private.OperatorAgentDeliveryFailure
type OperatorAgentDeliveryLifecycle = private.OperatorAgentDeliveryLifecycle
type OperatorAgentDeliveryLifecycleList = private.OperatorAgentDeliveryLifecycleList
type OperatorAgentDeliveryLifecycleOptions = private.OperatorAgentDeliveryLifecycleOptions
type OperatorAgentDeliveryLifecycleRow = private.OperatorAgentDeliveryLifecycleRow
type OperatorAgentDetail = private.OperatorAgentDetail
type OperatorAgentDiagnosis = private.OperatorAgentDiagnosis
type OperatorAgentDiagnosisActive = private.OperatorAgentDiagnosisActive
type OperatorAgentDiagnosisOptions = private.OperatorAgentDiagnosisOptions
type OperatorAgentDiagnosisQueue = private.OperatorAgentDiagnosisQueue
type OperatorAgentDiagnosisRuntimeState = private.OperatorAgentDiagnosisRuntimeState
type OperatorAgentDiagnosisWatchdog = private.OperatorAgentDiagnosisWatchdog
type OperatorAgentLastToolOutcome = private.OperatorAgentLastToolOutcome
type OperatorAgentListOptions = private.OperatorAgentListOptions
type OperatorAgentListResult = private.OperatorAgentListResult
type OperatorAgentPendingDelivery = private.OperatorAgentPendingDelivery
type OperatorAgentSummary = private.OperatorAgentSummary
type OperatorAgentTool = private.OperatorAgentTool
type OperatorAgentUsage = private.OperatorAgentUsage
type OperatorAgentUsageBreakdown = private.OperatorAgentUsageBreakdown
type OperatorAgentUsageByAccounting = private.OperatorAgentUsageByAccounting
type OperatorAgentUsageOptions = private.OperatorAgentUsageOptions
type OperatorAgentUsageReadStore = private.OperatorAgentUsageReadStore
type OperatorAgentUsageTotals = private.OperatorAgentUsageTotals
type OperatorAgentUsageWindow = private.OperatorAgentUsageWindow
type OperatorConversationActivity = private.OperatorConversationActivity
type OperatorConversationActivityCounts = private.OperatorConversationActivityCounts
type OperatorConversationForkSession = private.OperatorConversationForkSession
type OperatorConversationListOptions = private.OperatorConversationListOptions
type OperatorConversationListResult = private.OperatorConversationListResult
type OperatorConversationReadSource = private.OperatorConversationReadSource
type OperatorConversationSummary = private.OperatorConversationSummary
type OperatorConversationSummaryMetadata = private.OperatorConversationSummaryMetadata
type OperatorConversationTokenUsage = private.OperatorConversationTokenUsage
type OperatorConversationToolCall = private.OperatorConversationToolCall
type OperatorConversationToolResult = private.OperatorConversationToolResult
type OperatorConversationTurn = private.OperatorConversationTurn
type OperatorConversationTurnBlock = private.OperatorConversationTurnBlock
type OperatorConversationTurnListItem = private.OperatorConversationTurnListItem
type OperatorConversationTurnListOptions = private.OperatorConversationTurnListOptions
type OperatorConversationTurnListResult = private.OperatorConversationTurnListResult
type OperatorConversationWatchdog = private.OperatorConversationWatchdog
type OperatorDeadLetterRecord = private.OperatorDeadLetterRecord
type OperatorEntityAggregateOptions = private.OperatorEntityAggregateOptions
type OperatorEntityAggregateResult = private.OperatorEntityAggregateResult
type OperatorEntityFull = private.OperatorEntityFull
type OperatorEntityListOptions = private.OperatorEntityListOptions
type OperatorEntityListResult = private.OperatorEntityListResult
type OperatorEntitySummary = private.OperatorEntitySummary
type OperatorEventDelivery = private.OperatorEventDelivery
type OperatorEventFull = private.OperatorEventFull
type OperatorEventListFilter = private.OperatorEventListFilter
type OperatorEventListOptions = private.OperatorEventListOptions
type OperatorEventListResult = private.OperatorEventListResult
type OperatorLiveTurn = private.OperatorLiveTurn
type OperatorObservabilityReadOwner = private.OperatorObservabilityReadOwner
type OperatorObservabilityReadSurface = private.OperatorObservabilityReadSurface
type OperatorPublicConversationTurn = private.OperatorPublicConversationTurn
type OperatorPublicConversationTurnDetail = private.OperatorPublicConversationTurnDetail
type OperatorRuntimeIncident = private.OperatorRuntimeIncident
type OperatorRuntimeIncidentListOptions = private.OperatorRuntimeIncidentListOptions
type OperatorRuntimeIncidentListResult = private.OperatorRuntimeIncidentListResult
type OperatorRuntimeLogEntry = private.OperatorRuntimeLogEntry
type OperatorRuntimeLogListOptions = private.OperatorRuntimeLogListOptions
type OperatorRuntimeLogListResult = private.OperatorRuntimeLogListResult
type OperatorSessionRef = private.OperatorSessionRef
type OperatorTurnRef = private.OperatorTurnRef
type PendingAgentDeliveryDetail = private.PendingAgentDeliveryDetail
type PendingAgentDeliveryFacts = private.PendingAgentDeliveryFacts
type PendingAgentDeliveryListOptions = private.PendingAgentDeliveryListOptions
type PendingAgentDeliveryPage = private.PendingAgentDeliveryPage
type PostgresStore = private.PostgresStore
type RunDebugAgentTurn = private.RunDebugAgentTurn
type RunDebugDeadLetter = private.RunDebugDeadLetter
type RunDebugDeliveryCount = private.RunDebugDeliveryCount
type RunDebugEvent = private.RunDebugEvent
type RunDebugEventCount = private.RunDebugEventCount
type RunDebugFailureDelivery = private.RunDebugFailureDelivery
type RunDebugMutation = private.RunDebugMutation
type RunDebugQueryOptions = private.RunDebugQueryOptions
type RunDebugReport = private.RunDebugReport
type RunDebugRunSummary = private.RunDebugRunSummary
type RunDebugRuntimeLog = private.RunDebugRuntimeLog
type RunDebugRuntimeSummary = private.RunDebugRuntimeSummary
type RunDebugTraceFilter = private.RunDebugTraceFilter
type RunDebugTraceQueryOptions = private.RunDebugTraceQueryOptions
type RunDebugTraceRow = private.RunDebugTraceRow
type RunHeader = private.RunHeader
type RunHeaderListOptions = private.RunHeaderListOptions
type RunOperationalStatus = private.RunOperationalStatus
type RunTestQuiescence = private.RunTestQuiescence
type RuntimeStoreOrigin = private.RuntimeStoreOrigin
type SQLiteRuntimeStore = private.SQLiteRuntimeStore
type ScenarioSetupEntityRequest = private.ScenarioSetupEntityRequest
type ScenarioSetupEntityResult = private.ScenarioSetupEntityResult
type ScenarioSetupRequest = private.ScenarioSetupRequest
type ScenarioSetupResult = private.ScenarioSetupResult
type SchemaBootstrapRequest = private.SchemaBootstrapRequest
type SchemaBootstrapper = private.SchemaBootstrapper
type SchemaCompatibilityError = private.SchemaCompatibilityError
type SchemaDialect = private.SchemaDialect
type SchemaTableDDL = private.SchemaTableDDL

var CanonicalConversationForkSandboxPolicy = private.CanonicalConversationForkSandboxPolicy
var CanonicalStatelessConversationVisibilitySourceSQL = private.CanonicalStatelessConversationVisibilitySourceSQL
var DSNFromConfig = private.DSNFromConfig
var DecodeConversationRuntimeStateDescriptor = private.DecodeConversationRuntimeStateDescriptor
var EncodeMailboxV1Cursor = private.EncodeMailboxV1Cursor
var EnrichOperatorDeliveryFailureEvidence = private.EnrichOperatorDeliveryFailureEvidence
var EnrichOperatorEventFailureEvidence = private.EnrichOperatorEventFailureEvidence
var FlattenSchemaTableDDLs = private.FlattenSchemaTableDDLs
var GenerateNodeStateTableDDLs = private.GenerateNodeStateTableDDLs
var GeneratePlatformTableDDLs = private.GeneratePlatformTableDDLs
var IsAgentTargetAmbiguous = private.IsAgentTargetAmbiguous
var NewOperatorEventFull = private.NewOperatorEventFull
var NewPostgresStore = construction.NewPostgres
var NewSQLiteRuntimeStore = construction.NewSQLiteRuntime
var NodeStateFieldTypeToDDL = private.NodeStateFieldTypeToDDL
var ProjectRunOperationalStatus = private.ProjectRunOperationalStatus
var QuoteIdent = private.QuoteIdent
var ResolveDatabasePassword = private.ResolveDatabasePassword
var SQLiteStatementsForPlan = private.SQLiteStatementsForPlan
var SchemaFieldTypeToDDL = private.SchemaFieldTypeToDDL
var StatementsForSchemaDialect = private.StatementsForSchemaDialect
var ValidateConversationRuntimeWatchdogDescriptor = private.ValidateConversationRuntimeWatchdogDescriptor

const (
	AgentUsageAccountingEstimated          = private.AgentUsageAccountingEstimated
	AgentUsageAccountingExact              = private.AgentUsageAccountingExact
	ConversationForkChatSandboxOwner       = private.ConversationForkChatSandboxOwner
	ConversationForkChatSnapshotOwner      = private.ConversationForkChatSnapshotOwner
	ConversationForkLifecycleTTL           = private.ConversationForkLifecycleTTL
	DefaultAgentDeliveryDiagnosticsLimit   = private.DefaultAgentDeliveryDiagnosticsLimit
	DefaultAgentDeliveryLifecycleLimit     = private.DefaultAgentDeliveryLifecycleLimit
	DefaultPendingAgentDeliveryDetailLimit = private.DefaultPendingAgentDeliveryDetailLimit
	MaxAgentDeliveryDiagnosticsLimit       = private.MaxAgentDeliveryDiagnosticsLimit
	MaxAgentDeliveryLifecycleLimit         = private.MaxAgentDeliveryLifecycleLimit
	MaxAgentDiagnosisQueueLimit            = private.MaxAgentDiagnosisQueueLimit
	MaxPendingAgentDeliveryDetailLimit     = private.MaxPendingAgentDeliveryDetailLimit
	RuntimeStoreMetadataTable              = private.RuntimeStoreMetadataTable
	SchemaDialectPostgres                  = private.SchemaDialectPostgres
	SchemaDialectSQLite                    = private.SchemaDialectSQLite
)

var (
	ErrAPIIdempotencyConflict                = private.ErrAPIIdempotencyConflict
	ErrAgentNotFound                         = private.ErrAgentNotFound
	ErrAgentTargetAmbiguous                  = private.ErrAgentTargetAmbiguous
	ErrAmbiguousEntityRunID                  = private.ErrAmbiguousEntityRunID
	ErrBundleCatalogConflict                 = private.ErrBundleCatalogConflict
	ErrBundleNotFound                        = private.ErrBundleNotFound
	ErrConversationForkNotFound              = private.ErrConversationForkNotFound
	ErrEntityNotFound                        = private.ErrEntityNotFound
	ErrEventIdentityConflict                 = private.ErrEventIdentityConflict
	ErrEventNotFound                         = private.ErrEventNotFound
	ErrInvalidAgentDeliveryDiagnosticsCursor = private.ErrInvalidAgentDeliveryDiagnosticsCursor
	ErrInvalidAgentDeliveryLifecycleCursor   = private.ErrInvalidAgentDeliveryLifecycleCursor
	ErrInvalidAgentDeliveryLifecycleStatus   = private.ErrInvalidAgentDeliveryLifecycleStatus
	ErrInvalidBundleCatalogCursor            = private.ErrInvalidBundleCatalogCursor
	ErrInvalidConversationCursor             = private.ErrInvalidConversationCursor
	ErrInvalidConversationForkCursor         = private.ErrInvalidConversationForkCursor
	ErrInvalidEntityCursor                   = private.ErrInvalidEntityCursor
	ErrInvalidEntityReadParam                = private.ErrInvalidEntityReadParam
	ErrInvalidObservabilityCursor            = private.ErrInvalidObservabilityCursor
	ErrInvalidPendingAgentDeliveryCursor     = private.ErrInvalidPendingAgentDeliveryCursor
	ErrInvalidRunListCursor                  = private.ErrInvalidRunListCursor
	ErrMailboxV1InvalidCursor                = private.ErrMailboxV1InvalidCursor
	ErrMailboxV1NotFound                     = private.ErrMailboxV1NotFound
	ErrRunNotFound                           = private.ErrRunNotFound
	ErrSessionNotFound                       = private.ErrSessionNotFound
	ErrTurnNotFound                          = private.ErrTurnNotFound
	ErrUnknownSchemaType                     = private.ErrUnknownSchemaType
)
