import { useMemo } from "react";

export function useGraphController({
  verticals,
  graph,
  graphViewGraph,
  agents,
  graphMode,
  graphVertical,
  selectedGraphNodeID,
  selectedGraphEdgeID,
  graphFullscreen,
  setGraphMode,
  setGraphVertical,
  setSelectedGraphNodeID,
  setSelectedGraphEdgeID,
  setGraphFullscreen,
  refreshGraph,
  setGraphViewGraph,
  restartAgent,
  openControl,
  inspectAgent,
  navigateToTask,
}) {
  return useMemo(() => ({
    state: {
      verticals,
      graph,
      graphViewGraph,
      agents,
      graphMode,
      graphVertical,
      selectedGraphNodeID,
      selectedGraphEdgeID,
      graphFullscreen,
    },
    actions: {
      setGraphMode,
      setGraphVertical,
      setSelectedGraphNodeID,
      setSelectedGraphEdgeID,
      setGraphFullscreen,
      refreshGraph,
      setGraphViewGraph,
      restartAgent,
      openControl,
      inspectAgent,
      navigateToTask,
    },
  }), [
    agents,
    graph,
    graphFullscreen,
    graphMode,
    graphVertical,
    graphViewGraph,
    inspectAgent,
    navigateToTask,
    openControl,
    refreshGraph,
    restartAgent,
    selectedGraphEdgeID,
    selectedGraphNodeID,
    setGraphFullscreen,
    setGraphMode,
    setGraphVertical,
    setGraphViewGraph,
    setSelectedGraphEdgeID,
    setSelectedGraphNodeID,
    verticals,
  ]);
}
