name: operating
mode: template
instance:
  by: operating_id
pins:
  inputs:
    events:
      - name: operating_report_requested
        event: operating.report.requested
        resolution:
          mode: create
        carries:
          operating_id:
            from: event.id
            type: text
  outputs:
    events:
      - name: operating_reported
        event: operating.reported
