package main

import (
	"archive/zip"
	"bytes"
	"crypto/sha256"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"path"
	"sort"
	"strconv"
	"strings"
)

type manifestFile struct {
	path   string
	size   int64
	digest [sha256.Size]byte
}

func main() {
	archivePath := flag.String("archive", "", "path to the pinned interpreter ZIP")
	outputPath := flag.String("output", "", "generated Go output path")
	flag.Parse()
	if *archivePath == "" || *outputPath == "" {
		fatalf("both -archive and -output are required")
	}
	raw, err := os.ReadFile(*archivePath)
	if err != nil {
		fatalf("read archive: %v", err)
	}
	reader, err := zip.NewReader(bytes.NewReader(raw), int64(len(raw)))
	if err != nil {
		fatalf("open archive: %v", err)
	}
	directories := map[string]struct{}{}
	var files []manifestFile
	for _, file := range reader.File {
		trimmed := strings.TrimSuffix(file.Name, "/")
		for _, segment := range strings.Split(trimmed, "/") {
			if segment == "" || segment == "." || segment == ".." {
				fatalf("unsafe archive path %q", file.Name)
			}
		}
		name := path.Clean(file.Name)
		if name == "." || name == ".." || path.IsAbs(name) || strings.HasPrefix(name, "../") || strings.Contains(name, "\\") {
			fatalf("unsafe archive path %q", file.Name)
		}
		if file.Mode()&os.ModeSymlink != 0 || (!file.FileInfo().IsDir() && !file.Mode().IsRegular()) {
			fatalf("unsupported archive entry %q", file.Name)
		}
		if file.FileInfo().IsDir() {
			directories[name] = struct{}{}
			continue
		}
		for parent := path.Dir(name); parent != "."; parent = path.Dir(parent) {
			directories[parent] = struct{}{}
		}
		src, err := file.Open()
		if err != nil {
			fatalf("open %q: %v", file.Name, err)
		}
		hasher := sha256.New()
		size, copyErr := io.Copy(hasher, src)
		closeErr := src.Close()
		if copyErr != nil || closeErr != nil {
			fatalf("hash %q: copy=%v close=%v", file.Name, copyErr, closeErr)
		}
		var digest [sha256.Size]byte
		copy(digest[:], hasher.Sum(nil))
		files = append(files, manifestFile{path: name, size: size, digest: digest})
	}
	dirs := make([]string, 0, len(directories))
	for directory := range directories {
		dirs = append(dirs, directory)
	}
	sort.Strings(dirs)
	sort.Slice(files, func(i, j int) bool { return files[i].path < files[j].path })

	var source bytes.Buffer
	fmt.Fprintln(&source, "// Code generated by internal/genartifactmanifest; DO NOT EDIT.")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "package pythonmodule")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "var embeddedArtifactManifest = artifactManifest{")
	fmt.Fprintln(&source, "\tdirectories: []string{")
	for _, directory := range dirs {
		fmt.Fprintf(&source, "\t\t%s,\n", strconv.Quote(directory))
	}
	fmt.Fprintln(&source, "\t},")
	fmt.Fprintln(&source, "\tfiles: []artifactManifestFile{")
	for _, file := range files {
		fmt.Fprintf(&source, "\t\t{path: %s, size: %d, digest: [32]byte{%s}},\n", strconv.Quote(file.path), file.size, byteLiterals(file.digest[:]))
	}
	fmt.Fprintln(&source, "\t},")
	fmt.Fprintln(&source, "}")
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		fatalf("format generated source: %v", err)
	}
	if err := os.WriteFile(*outputPath, formatted, 0o644); err != nil {
		fatalf("write generated source: %v", err)
	}
}

func byteLiterals(value []byte) string {
	parts := make([]string, len(value))
	for index, item := range value {
		parts[index] = fmt.Sprintf("0x%02x", item)
	}
	return strings.Join(parts, ", ")
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
