package empire

import empirepayloads "empireai/internal/empire/payloads"

type ValidationContextSnapshot = empirepayloads.ValidationContextSnapshot
type ScoreDimensionResult = empirepayloads.ScoreDimensionResult
type ContestedDimension = empirepayloads.ContestedDimension
type ScoringComposite = empirepayloads.ScoringComposite
type ScoringAccumulatorInput = empirepayloads.ScoringAccumulatorInput

type ValidationStartedPayload = empirepayloads.ValidationStartedPayload
type BrandRequestedPayload = empirepayloads.BrandRequestedPayload
type ValidationPackageReadyPayload = empirepayloads.ValidationPackageReadyPayload
type SpecValidationRequestedPayload = empirepayloads.SpecValidationRequestedPayload
type CTOSpecReviewRequestedPayload = empirepayloads.CTOSpecReviewRequestedPayload
type SpecRevisionRequestedPayload = empirepayloads.SpecRevisionRequestedPayload
type ValidationMoreDataNeededPayload = empirepayloads.ValidationMoreDataNeededPayload
type BrandRevisionNeededPayload = empirepayloads.BrandRevisionNeededPayload
type VerticalKilledPayload = empirepayloads.VerticalKilledPayload
type ScanAssignedPayload = empirepayloads.ScanAssignedPayload
type SynthesisNeededPayload = empirepayloads.SynthesisNeededPayload
type DedupCandidatePayload = empirepayloads.DedupCandidatePayload
type DedupAmbiguousPayload = empirepayloads.DedupAmbiguousPayload
type VerticalDiscoveredPayload = empirepayloads.VerticalDiscoveredPayload
type ScanCompletedBuildInput = empirepayloads.ScanCompletedBuildInput
type ScanCompletedPayload = empirepayloads.ScanCompletedPayload
type ScoringRequestedPayload = empirepayloads.ScoringRequestedPayload
type ScoringContestedPayload = empirepayloads.ScoringContestedPayload
type VerticalScoredPayload = empirepayloads.VerticalScoredPayload
type VerticalShortlistedPayload = empirepayloads.VerticalShortlistedPayload
type VerticalMarginalPayload = empirepayloads.VerticalMarginalPayload
type VerticalRejectedPayload = empirepayloads.VerticalRejectedPayload
type PortfolioDigestTimerPayload = empirepayloads.PortfolioDigestTimerPayload
