package empire

import runtimepipeline "empireai/internal/runtime/pipeline"

type ValidationContextSnapshot = runtimepipeline.ValidationContextSnapshot
type ScoreDimensionResult = runtimepipeline.ScoreDimensionResult
type ContestedDimension = runtimepipeline.ContestedDimension
type ScoringComposite = runtimepipeline.ScoringComposite
type ScoringAccumulatorInput = runtimepipeline.ScoringAccumulatorInput

type ValidationStartedPayload = runtimepipeline.ValidationStartedPayload
type BrandRequestedPayload = runtimepipeline.BrandRequestedPayload
type ValidationPackageReadyPayload = runtimepipeline.ValidationPackageReadyPayload
type SpecValidationRequestedPayload = runtimepipeline.SpecValidationRequestedPayload
type CTOSpecReviewRequestedPayload = runtimepipeline.CTOSpecReviewRequestedPayload
type SpecRevisionRequestedPayload = runtimepipeline.SpecRevisionRequestedPayload
type ValidationMoreDataNeededPayload = runtimepipeline.ValidationMoreDataNeededPayload
type BrandRevisionNeededPayload = runtimepipeline.BrandRevisionNeededPayload
type VerticalKilledPayload = runtimepipeline.VerticalKilledPayload
type ScanAssignedPayload = runtimepipeline.ScanAssignedPayload
type SynthesisNeededPayload = runtimepipeline.SynthesisNeededPayload
type DedupCandidatePayload = runtimepipeline.DedupCandidatePayload
type DedupAmbiguousPayload = runtimepipeline.DedupAmbiguousPayload
type VerticalDiscoveredPayload = runtimepipeline.VerticalDiscoveredPayload
type ScanCompletedBuildInput = runtimepipeline.ScanCompletedBuildInput
type ScanCompletedPayload = runtimepipeline.ScanCompletedPayload
type ScoringRequestedPayload = runtimepipeline.ScoringRequestedPayload
type ScoringContestedPayload = runtimepipeline.ScoringContestedPayload
type VerticalScoredPayload = runtimepipeline.VerticalScoredPayload
type VerticalShortlistedPayload = runtimepipeline.VerticalShortlistedPayload
type VerticalMarginalPayload = runtimepipeline.VerticalMarginalPayload
type VerticalRejectedPayload = runtimepipeline.VerticalRejectedPayload
type PortfolioDigestTimerPayload = runtimepipeline.PortfolioDigestTimerPayload
